export interface Question {
  id: number;
  categoria: string;
  pregunta: string;
  opciones: string[];
  respuestaCorrecta: number;
  explicacionTexto: string;
  urlAudio: string | null;
}

export const categorias = [
  'Ley de Tránsito',
  'Señalización',
  'Mecánica Básica',
  'Primeros Auxilios',
  'Conducción Segura',
  'Medio Ambiente',
];

export const mockQuestions: Question[] = [
  {
    id: 1,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida en zonas urbanas en Chile?',
    opciones: ['40 km/h', '50 km/h', '60 km/h', '80 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Según la Ley de Tránsito chilena, la velocidad máxima en zonas urbanas es de 60 km/h, salvo que la señalización indique lo contrario.',
    urlAudio: null,
  },
  {
    id: 2,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una señal de tránsito con forma de triángulo invertido?',
    opciones: ['Pare', 'Ceda el paso', 'Zona de escuela', 'Curva peligrosa'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El triángulo invertido con borde rojo es la señal de "Ceda el Paso". Indica que debes dar preferencia de paso a los vehículos que circulan por la vía a la que te incorporas.',
    urlAudio: null,
  },
  {
    id: 3,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuándo es obligatorio el uso del cinturón de seguridad?',
    opciones: ['Solo en carretera', 'Solo el conductor', 'Todos los ocupantes siempre', 'Solo en asientos delanteros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La ley establece que todos los ocupantes del vehículo deben usar cinturón de seguridad en todo momento, tanto en zona urbana como rural.',
    urlAudio: null,
  },
  {
    id: 4,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cada cuántos kilómetros se recomienda cambiar el aceite del motor?',
    opciones: ['Cada 3.000 km', 'Cada 5.000 km', 'Cada 10.000 km', 'Cada 20.000 km'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se recomienda cambiar el aceite del motor cada 5.000 km o según las indicaciones del fabricante del vehículo para mantener el motor en buen estado.',
    urlAudio: null,
  },
  {
    id: 5,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué es lo primero que se debe hacer al llegar a un accidente de tránsito?',
    opciones: ['Mover a los heridos', 'Señalizar la zona', 'Llamar al seguro', 'Tomar fotos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Lo primero es señalizar la zona del accidente para evitar nuevos siniestros. Luego llamar a emergencias (131 Ambulancia, 133 Carabineros) y asistir a los heridos sin moverlos innecesariamente.',
    urlAudio: null,
  },
  {
    id: 6,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la distancia mínima de seguimiento recomendada?',
    opciones: ['1 segundo', '2 segundos', '3 segundos', '5 segundos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La regla de los 2 segundos es la distancia mínima de seguimiento recomendada en condiciones normales. En lluvia o mala visibilidad, debe aumentarse a 4 segundos.',
    urlAudio: null,
  },
  {
    id: 7,
    categoria: 'Señalización',
    pregunta: '¿Qué significa una línea continua amarilla en el centro de la calzada?',
    opciones: ['Se puede adelantar', 'Prohibido adelantar', 'Zona de estacionamiento', 'Carril exclusivo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La línea continua amarilla en el centro de la calzada indica que está prohibido adelantar. No se puede cruzar ni pisar esta línea.',
    urlAudio: null,
  },
  {
    id: 8,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es el límite legal de alcohol en la sangre para conducir en Chile?',
    opciones: ['0.0 g/l', '0.3 g/l', '0.5 g/l', '0.8 g/l'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En Chile, el límite es de 0.3 g/l de alcohol en la sangre. Sobre este nivel se considera estado de ebriedad y es sancionado por la Ley Emilia.',
    urlAudio: null,
  },
  {
    id: 9,
    categoria: 'Medio Ambiente',
    pregunta: '¿Qué se debe hacer con el aceite usado del motor?',
    opciones: ['Tirarlo al desagüe', 'Dejarlo en la basura', 'Llevarlo a un punto de reciclaje', 'Quemarlo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El aceite usado es un residuo peligroso y debe llevarse a un punto de reciclaje autorizado. Tirarlo al desagüe contamina gravemente el agua.',
    urlAudio: null,
  },
  {
    id: 10,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué se debe hacer cuando hay neblina espesa?',
    opciones: ['Usar luces altas', 'Usar luces bajas y reducir velocidad', 'Detenerse en la pista', 'Usar balizas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Con neblina se deben usar las luces bajas (nunca altas porque el reflejo empeora la visibilidad) y reducir la velocidad considerablemente.',
    urlAudio: null,
  },
  {
    id: 11,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una señal de fondo azul con una flecha blanca?',
    opciones: ['Dirección obligatoria', 'Sentido sugerido', 'Zona de estacionamiento', 'Hospital cercano'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las señales con fondo azul y flecha blanca son señales reglamentarias que indican la dirección obligatoria que deben seguir los vehículos.',
    urlAudio: null,
  },
  {
    id: 12,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Quién tiene preferencia en un cruce no regulado?',
    opciones: ['El que viene por la derecha', 'El que viene por la izquierda', 'El que llega primero', 'El vehículo más grande'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En un cruce no regulado por señales ni semáforos, tiene preferencia el vehículo que viene por la derecha del conductor.',
    urlAudio: null,
  },
  {
    id: 13,
    categoria: 'Mecánica Básica',
    pregunta: '¿Para qué sirve el líquido refrigerante del motor?',
    opciones: ['Lubricar el motor', 'Mantener la temperatura del motor', 'Limpiar los inyectores', 'Mejorar el combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El líquido refrigerante circula por el motor absorbiendo el calor generado por la combustión, manteniendo la temperatura en un rango óptimo y evitando el sobrecalentamiento.',
    urlAudio: null,
  },
  {
    id: 14,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cuál es el número de emergencias de Carabineros en Chile?',
    opciones: ['131', '132', '133', '134'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El 133 es el número de Carabineros de Chile. El 131 es Ambulancia (SAMU), el 132 es Bomberos.',
    urlAudio: null,
  },
  {
    id: 15,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene conducir con sueño?',
    opciones: ['Mejora los reflejos', 'No afecta la conducción', 'Equivale a conducir ebrio', 'Solo afecta la visión'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Conducir con sueño produce efectos similares a conducir bajo los efectos del alcohol: disminuye los reflejos, la atención y la capacidad de reacción.',
    urlAudio: null,
  },
  {
    id: 16,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida en autopistas en Chile?',
    opciones: ['100 km/h', '110 km/h', '120 km/h', '130 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad máxima en autopistas chilenas es de 120 km/h, salvo que la señalización indique un límite diferente.',
    urlAudio: null,
  },
  {
    id: 17,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una señal de tránsito octagonal (8 lados)?',
    opciones: ['Ceda el paso', 'Pare', 'No estacionar', 'Zona escolar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal octagonal (8 lados) de color rojo con letras blancas es la señal de PARE. Indica detención obligatoria antes de continuar.',
    urlAudio: null,
  },
  {
    id: 18,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica que la presión de los neumáticos es incorrecta?',
    opciones: ['El auto vibra al frenar', 'Desgaste irregular de los neumáticos', 'El motor hace ruido', 'Las luces parpadean'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un desgaste irregular de los neumáticos es señal de presión incorrecta. Si se desgastan más al centro, hay exceso de presión; si se desgastan a los lados, falta presión.',
    urlAudio: null,
  },
  {
    id: 19,
    categoria: 'Medio Ambiente',
    pregunta: '¿Qué vehículos están sujetos a restricción vehicular en Santiago?',
    opciones: ['Solo vehículos diésel', 'Vehículos sin sello verde', 'Todos los vehículos', 'Solo camiones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos sin sello verde (catalíticos anteriores a cierta norma de emisión) están sujetos a restricción vehicular permanente y en episodios de contaminación.',
    urlAudio: null,
  },
  {
    id: 20,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se debe actuar al tener un reventón de neumático?',
    opciones: ['Frenar bruscamente', 'Acelerar para estabilizar', 'Sujetar firme el volante y desacelerar gradualmente', 'Girar hacia el lado del reventón'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Ante un reventón, se debe sujetar firmemente el volante, no frenar bruscamente, y desacelerar gradualmente para orillarse de forma segura.',
    urlAudio: null,
  },
  {
    id: 21,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Desde qué edad se puede obtener licencia de conducir clase B en Chile?',
    opciones: ['16 años', '17 años', '18 años', '21 años'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En Chile, la edad mínima para obtener una licencia de conducir clase B (vehículos particulares) es de 18 años.',
    urlAudio: null,
  },
  {
    id: 22,
    categoria: 'Señalización',
    pregunta: '¿Qué color de semáforo indica precaución y prepararse para detenerse?',
    opciones: ['Rojo', 'Verde', 'Amarillo', 'Azul'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La luz amarilla del semáforo indica precaución. Si puedes detenerte de forma segura, debes hacerlo. Si ya estás en la intersección, debes continuar con precaución.',
    urlAudio: null,
  },
  {
    id: 23,
    categoria: 'Mecánica Básica',
    pregunta: '¿Para qué sirve el sistema ABS en un vehículo?',
    opciones: ['Acelerar más rápido', 'Evitar el bloqueo de las ruedas al frenar', 'Mejorar la suspensión', 'Ahorrar combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El sistema ABS (Anti-lock Braking System) impide que las ruedas se bloqueen durante una frenada brusca, permitiendo mantener el control de la dirección.',
    urlAudio: null,
  },
  {
    id: 24,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué posición se recomienda para un accidentado inconsciente que respira?',
    opciones: ['Boca arriba', 'Sentado', 'Posición lateral de seguridad', 'Boca abajo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La posición lateral de seguridad mantiene las vías aéreas despejadas y evita que el accidentado se ahogue con sus propios fluidos si vomita.',
    urlAudio: null,
  },
  {
    id: 25,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué distancia mínima se debe dejar al estacionarse de un grifo (hidrante)?',
    opciones: ['3 metros', '5 metros', '10 metros', '15 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se debe dejar al menos 10 metros de distancia al estacionarse cerca de un grifo (hidrante) para no obstruir el acceso de los bomberos en caso de emergencia.',
    urlAudio: null,
  },
  {
    id: 26,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuándo se debe usar la luz intermitente (señalero)?',
    opciones: ['Solo al girar', 'Al girar y cambiar de pista', 'Solo en carretera', 'Solo de noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El señalero debe usarse siempre al girar, cambiar de pista o incorporarse al tránsito, con suficiente anticipación para alertar a los demás conductores.',
    urlAudio: null,
  },
  {
    id: 27,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una señal circular con borde rojo y fondo blanco?',
    opciones: ['Señal informativa', 'Señal de advertencia', 'Señal reglamentaria de prohibición', 'Señal turística'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Las señales circulares con borde rojo y fondo blanco son señales reglamentarias de prohibición o restricción, como velocidad máxima o prohibido adelantar.',
    urlAudio: null,
  },
  {
    id: 28,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué elemento del vehículo transforma la energía del combustible en movimiento?',
    opciones: ['La transmisión', 'El motor', 'El alternador', 'El embrague'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El motor es el encargado de transformar la energía química del combustible en energía mecánica (movimiento) que impulsa el vehículo.',
    urlAudio: null,
  },
  {
    id: 29,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cuál es la principal causa de contaminación por vehículos?',
    opciones: ['El ruido', 'Los gases de escape', 'El desgaste de neumáticos', 'Las luces'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los gases de escape (CO2, CO, NOx, material particulado) son la principal fuente de contaminación vehicular y contribuyen al cambio climático y problemas de salud.',
    urlAudio: null,
  },
  {
    id: 30,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué se debe hacer antes de retroceder con el vehículo?',
    opciones: ['Tocar la bocina', 'Mirar los espejos y girar la cabeza', 'Encender las luces', 'Bajar la ventanilla'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de retroceder, se deben revisar todos los espejos y girar la cabeza para verificar que no hay peatones, ciclistas u obstáculos detrás del vehículo.',
    urlAudio: null,
  },
  {
    id: 31,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Es obligatorio llevar el triángulo de seguridad en el vehículo?',
    opciones: ['No, es opcional', 'Solo en carretera', 'Sí, siempre', 'Solo de noche'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Es obligatorio llevar al menos un triángulo de seguridad reflectante en el vehículo. Debe colocarse a una distancia de al menos 50 metros del vehículo detenido.',
    urlAudio: null,
  },
  {
    id: 32,
    categoria: 'Señalización',
    pregunta: '¿Qué señal tiene forma de diamante (rombo) y fondo amarillo?',
    opciones: ['Señal de prohibición', 'Señal de advertencia de peligro', 'Señal informativa', 'Señal de prioridad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las señales en forma de diamante con fondo amarillo son señales de advertencia o prevención. Alertan sobre peligros o situaciones especiales adelante.',
    urlAudio: null,
  },
  {
    id: 33,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumple el embrague en un vehículo mecánico?',
    opciones: ['Frenar las ruedas', 'Conectar y desconectar el motor de la transmisión', 'Enfriar el motor', 'Dirigir las ruedas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El embrague permite conectar y desconectar el motor de la caja de cambios para poder cambiar de marcha o detener el vehículo sin apagar el motor.',
    urlAudio: null,
  },
  {
    id: 34,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué NO se debe hacer con un herido en un accidente de tránsito?',
    opciones: ['Llamar a emergencias', 'Darle agua o alimentos', 'Señalizar la zona', 'Abrigarlo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No se debe dar agua ni alimentos a un herido, ya que podría necesitar cirugía de emergencia y el estómago debe estar vacío. También podría aspirar líquidos si está semiconsciente.',
    urlAudio: null,
  },
  {
    id: 35,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el principal factor de riesgo en la conducción?',
    opciones: ['El estado del camino', 'El factor humano', 'Las condiciones climáticas', 'El estado del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El factor humano (distracción, fatiga, exceso de velocidad, alcohol) es responsable de más del 90% de los accidentes de tránsito.',
    urlAudio: null,
  },
  {
    id: 36,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Se puede usar el teléfono celular mientras se conduce?',
    opciones: ['Sí, con manos libres', 'Sí, si es rápido', 'No, bajo ninguna circunstancia', 'Solo para GPS'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Solo se permite usar el teléfono celular con sistema manos libres mientras se conduce. Manipularlo con las manos está prohibido y es sancionado con multa.',
    urlAudio: null,
  },
  {
    id: 37,
    categoria: 'Señalización',
    pregunta: '¿Qué indica la demarcación de líneas peatonales (cebra) en la calzada?',
    opciones: ['Zona de estacionamiento', 'Cruce de peatones', 'Zona de carga y descarga', 'Inicio de ciclovía'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las líneas tipo cebra en la calzada indican un cruce peatonal. Los vehículos deben ceder el paso a los peatones que estén cruzando o esperando para cruzar.',
    urlAudio: null,
  },
  {
    id: 38,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica el testigo de temperatura del motor encendido en rojo?',
    opciones: ['Motor frío', 'Temperatura normal', 'Motor sobrecalentado', 'Falta de aceite'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El testigo de temperatura en rojo indica que el motor está sobrecalentado. Se debe detener el vehículo inmediatamente y esperar que se enfríe antes de verificar el nivel de refrigerante.',
    urlAudio: null,
  },
  {
    id: 39,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cómo se puede reducir la contaminación al conducir?',
    opciones: ['Acelerando bruscamente', 'Manteniendo una conducción eficiente', 'Usando siempre el aire acondicionado', 'Llevando más carga'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La conducción eficiente (velocidad constante, evitar acelerones y frenazos bruscos, mantener el vehículo en buen estado) reduce significativamente las emisiones contaminantes.',
    urlAudio: null,
  },
  {
    id: 40,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo afecta la lluvia a la conducción?',
    opciones: ['No la afecta', 'Reduce la adherencia al pavimento', 'Mejora la visibilidad', 'Aumenta la tracción'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La lluvia reduce la adherencia de los neumáticos al pavimento, aumenta la distancia de frenado y puede causar aquaplaning. Se debe reducir la velocidad y aumentar la distancia de seguimiento.',
    urlAudio: null,
  },
  {
    id: 41,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué documentos debe portar siempre el conductor?',
    opciones: ['Solo la licencia', 'Licencia y cédula de identidad', 'Licencia, permiso de circulación, seguro obligatorio y revisión técnica', 'Solo el permiso de circulación'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El conductor debe portar siempre: licencia de conducir vigente, permiso de circulación al día, seguro obligatorio (SOAP) vigente y certificado de revisión técnica al día.',
    urlAudio: null,
  },
  {
    id: 42,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una señal con fondo verde en carreteras?',
    opciones: ['Prohibición', 'Información de destinos y distancias', 'Advertencia', 'Zona de descanso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las señales con fondo verde en carreteras son señales informativas que indican destinos, distancias, nombres de rutas y servicios al conductor.',
    urlAudio: null,
  },
  {
    id: 43,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál es la función principal de los amortiguadores?',
    opciones: ['Sostener el peso del auto', 'Absorber las irregularidades del terreno', 'Frenar las ruedas', 'Dirigir el vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los amortiguadores absorben las irregularidades del terreno, manteniendo el contacto de los neumáticos con el suelo y proporcionando estabilidad y confort.',
    urlAudio: null,
  },
  {
    id: 44,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cómo se debe actuar ante una hemorragia externa?',
    opciones: ['Aplicar un torniquete inmediatamente', 'Hacer presión directa sobre la herida', 'Lavar con alcohol', 'No hacer nada y esperar ayuda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante una hemorragia externa, se debe hacer presión directa y firme sobre la herida con un paño limpio. El torniquete solo se usa como último recurso en hemorragias que amenazan la vida.',
    urlAudio: null,
  },
  {
    id: 45,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es el punto ciego de un vehículo?',
    opciones: ['La parte trasera del auto', 'Zonas no visibles por los espejos retrovisores', 'El capó del motor', 'La zona debajo del auto'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El punto ciego son las zonas alrededor del vehículo que no son visibles a través de los espejos retrovisores. Siempre se debe girar la cabeza para verificar estos puntos antes de cambiar de pista.',
    urlAudio: null,
  },
  {
    id: 46,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanciones contempla la Ley Emilia?',
    opciones: ['Solo multa económica', 'Cárcel efectiva por conducir ebrio causando lesiones graves o muerte', 'Suspensión de licencia por 6 meses', 'Trabajo comunitario'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Ley Emilia (N° 20.770) establece pena de cárcel efectiva (al menos 1 año) para quienes conduzcan en estado de ebriedad y causen lesiones gravísimas o muerte.',
    urlAudio: null,
  },
  {
    id: 47,
    categoria: 'Señalización',
    pregunta: '¿Qué significa un semáforo con flecha verde hacia la derecha?',
    opciones: ['Se puede girar a la derecha', 'Se puede girar a la izquierda', 'Se puede seguir recto', 'Precaución al girar'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La flecha verde en el semáforo indica que está permitido girar en la dirección que señala la flecha, siempre cediendo el paso a peatones.',
    urlAudio: null,
  },
  {
    id: 48,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cada cuánto tiempo se debe realizar la revisión técnica de un vehículo particular?',
    opciones: ['Cada 6 meses', 'Cada año', 'Cada 2 años', 'Cada 3 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos particulares deben realizar la revisión técnica cada año en una planta autorizada. Los vehículos nuevos tienen plazo desde el segundo año.',
    urlAudio: null,
  },
  {
    id: 49,
    categoria: 'Medio Ambiente',
    pregunta: '¿Qué es la restricción vehicular?',
    opciones: ['Prohibición de circular en ciertas calles', 'Medida que impide circular a vehículos según su patente', 'Límite de pasajeros', 'Horario de circulación'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La restricción vehicular es una medida medioambiental que impide circular a ciertos vehículos según el último dígito de su patente, especialmente en episodios de alta contaminación.',
    urlAudio: null,
  },
  {
    id: 50,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué hacer si el vehículo comienza a patinar en una curva?',
    opciones: ['Frenar bruscamente', 'Acelerar', 'Soltar el acelerador y girar suavemente en la dirección del patinaje', 'Apagar el motor'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Si el vehículo patina, se debe soltar el acelerador sin frenar bruscamente y girar suavemente el volante en la dirección hacia donde patina la parte trasera para recuperar el control.',
    urlAudio: null,
  },
];

export function getQuestionsByCategory(categoria: string): Question[] {
  return mockQuestions.filter(q => q.categoria === categoria);
}

export function getRandomExam(count: number = 35): Question[] {
  const shuffled = [...mockQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export const EXAM_CONFIG = {
  questionsPerExam: 35,
  passingScore: 0.75,
  timeLimit: 45 * 60,
  freeExamsAllowed: 1,
};
