import type { Question } from './questionsData';

export const questionsOficialPart1: Question[] = [
  {
    id: 2001,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué parte de la vía se debe utilizar exclusivamente al conducir un vehículo?',
    opciones: ['La berma', 'La calzada', 'La acera'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos deben circular exclusivamente por la calzada. La berma es solo para emergencias y la acera es de uso peatonal.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2002,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué casos puedes circular por la berma con tu vehículo?',
    opciones: ['Cuando por averías tengas que circular lentamente', 'Al estar las pistas ocupadas por otros vehículos', 'En ninguno de los casos anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No está permitido circular por la berma bajo ninguna circunstancia. La berma es exclusivamente para detenciones de emergencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2003,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué debes hacer cuando te adelanta otro vehículo?',
    opciones: ['Encender las luces bajas', 'Frenar bruscamente', 'Mantener tu velocidad o disminuirla para permitir el adelantamiento'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al ser adelantado, debes mantener o reducir tu velocidad para facilitar la maniobra de forma segura. Nunca aceleres ni frenes bruscamente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2004,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué obligación especial te corresponde cuando circulas en tu vehículo en una vía de doble sentido de tránsito, al enfrentar a otro vehículo que transita en sentido contrario?',
    opciones: ['Circular por la derecha alejándose del eje de la calzada', 'Encender el intermitente', 'Reducir la velocidad'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Al enfrentar un vehículo en sentido contrario, debes circular por la derecha alejándote del eje de la calzada para evitar una colisión frontal.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2005,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Por dónde debes circular con tu vehículo por norma general?',
    opciones: ['Por el centro de la calzada', 'Por la izquierda de la calzada', 'Por la derecha de la calzada'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La norma general establece que los vehículos deben circular por la derecha de la calzada, respetando el sentido del tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2006,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al estar las pistas de la calzada demarcadas, ¿por dónde debes circular con tu vehículo?',
    opciones: ['Por el centro de la calzada', 'Por la derecha de la calzada, sin considerar las pistas', 'Dentro de la franja demarcada para la pista'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Cuando las pistas están demarcadas, debes circular dentro de la franja correspondiente a tu pista, respetando la demarcación vial.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2007,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al circular por una calzada con varias pistas demarcadas en un sentido de tránsito, para virar a la derecha, ¿qué maniobra se debe efectuar?',
    opciones: ['Acercarse al eje central de la calzada', 'Ubicarse en la pista de la derecha de la calzada tan cerca como sea posible de la cuneta o del borde de la misma', 'Ubicarse en la pista de la izquierda de la calzada tan cerca como sea posible de la cuneta o del borde de la misma'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para virar a la derecha, debes ubicarte en la pista derecha lo más cerca posible de la cuneta o borde de la calzada antes de realizar el viraje.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2008,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Dónde es posible realizar la maniobra viraje en U?',
    opciones: ['Pasos peatonales', 'A mitad de cuadra, si no está prohibido', 'En la intersección'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El viraje en U puede realizarse a mitad de cuadra siempre que no esté prohibido por señalización. Está prohibido hacerlo en pasos peatonales.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2009,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al encontrarse la calzada húmeda, con hielo o con pavimento resbaladizo por la lluvia, ¿qué debe hacer la persona que conduce?',
    opciones: ['Conducir lenta y suavemente, sin hacer movimientos bruscos con el volante ni con los pedales', 'Aumentar la velocidad sin hacer movimientos bruscos con el volante', 'Estar atenta a frenar'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En pavimento resbaladizo se debe conducir lenta y suavemente, evitando movimientos bruscos del volante y los pedales para mantener el control del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2010,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al aproximarse a una curva con visibilidad reducida, ¿qué debe hacer la persona que conduce?',
    opciones: ['Adaptar la velocidad y ceñirse al borde derecho de la calzada', 'Circular por el centro de la calzada', 'Disminuir la velocidad hasta detenerse'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En curvas con visibilidad reducida, se debe adaptar la velocidad y mantenerse lo más a la derecha posible para evitar colisiones con vehículos en sentido contrario.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2011,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si observas que en la parte trasera de un vehículo se encienden las luces blancas, ¿qué indica?',
    opciones: ['Que el vehículo va a adelantar a otro vehículo', 'Que está retrocediendo', 'Que está virando a la derecha'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las luces blancas traseras indican que el vehículo está en marcha atrás (retrocediendo). Debes estar atento y mantener distancia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2012,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué distancia tiene permitida recorrer un vehículo en marcha atrás por la calzada?',
    opciones: ['100 metros', '150 metros', 'Ninguna de las anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La marcha atrás solo está permitida para la distancia mínima necesaria para maniobrar (estacionar, incorporarse al tránsito). No se permiten 100 ni 150 metros.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2013,
    categoria: 'Ley de Tránsito',
    pregunta: 'Para adelantar, ¿qué norma general debes considerar?',
    opciones: ['Adelantar por la derecha', 'Adelantar por la izquierda', 'En zonas rurales adelantar por la berma, al estar el vehículo que antecede detenido'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La norma general establece que el adelantamiento debe realizarse siempre por la izquierda del vehículo que se va a adelantar.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2014,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué maniobra debe realizar una persona conductora, al circular por una vía de dos sentidos, si va a girar hacia la izquierda?',
    opciones: ['Situarse al costado derecho de la calzada', 'Situarse progresivamente al costado derecho del eje o línea central de la vía por donde transita', 'Situarse al costado izquierdo de la calzada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para girar a la izquierda en una vía de doble sentido, debes acercarte progresivamente al eje o línea central de la vía, sin cruzarlo hasta iniciar el viraje.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2015,
    categoria: 'Ley de Tránsito',
    pregunta: 'Por regla general, ¿cómo debes estacionar tu vehículo?',
    opciones: ['Con dos ruedas sobre la acera', 'Sobre la acera', 'Al lado derecho en el sentido del tránsito, sobre la calzada'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La regla general es estacionar al lado derecho en el sentido del tránsito, sobre la calzada. Nunca sobre la acera ni parcialmente sobre ella.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2016,
    categoria: 'Ley de Tránsito',
    pregunta: 'Por regla general, ¿cómo debes estacionar tu vehículo en las vías rurales?',
    opciones: ['Con toda la estructura del vehículo sobre la berma', 'Sobre la calzada en el sentido contrario del tránsito', 'Longitudinalmente con la mitad del vehículo sobre la berma'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En vías rurales, el vehículo debe estacionarse con toda su estructura sobre la berma, fuera de la calzada, para no obstruir el tránsito.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2017,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes conducir sin licencia?',
    opciones: ['Sí, en caminos públicos rurales durante el día', 'Sí, en lugares de poco tránsito en las vías públicas de la ciudad', 'En ninguno de los casos anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No se puede conducir sin licencia bajo ninguna circunstancia en vías públicas. Hacerlo constituye una infracción gravísima.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2018,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al transitar con tu vehículo podrás pasar con luz roja del semáforo:',
    opciones: ['Si no hay vehículos que pasen con verde', 'Si tu vehículo es destinado a transporte de pasajeros', 'En ningún caso'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Nunca se puede pasar con luz roja del semáforo, independientemente del tipo de vehículo o las condiciones del tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2019,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué caso puedes conducir, por la vía pública, un tipo de vehículo distinto a la Clase Licencia que posees?',
    opciones: ['Para efectuar viajes cortos', 'En zonas no controladas', 'En ninguno de los casos anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No se puede conducir un vehículo de una clase distinta a la licencia que se posee. Cada clase de licencia habilita solo para el tipo de vehículo correspondiente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2020,
    categoria: 'Ley de Tránsito',
    pregunta: '¿De qué forma debes estacionar el vehículo en bajada?',
    opciones: ['Solo con freno de mano', 'Enganchado en primera marcha', 'Con freno de mano y las ruedas delanteras giradas hacia la cuneta'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En bajada, se debe estacionar con el freno de mano activado y las ruedas delanteras giradas hacia la cuneta, para que el vehículo se detenga contra el bordillo si se desplaza.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2021,
    categoria: 'Ley de Tránsito',
    pregunta: 'Puedes conducir tu vehículo en las vías públicas:',
    opciones: ['Sin sistemas de frenos', 'Con el mecanismo de la dirección en mal estado', 'En ninguno de los casos anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No se puede circular con el vehículo sin frenos o con la dirección en mal estado. El vehículo debe estar en condiciones mecánicas adecuadas para circular.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2022,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al transitar con tu vehículo en vías rurales, como norma de carácter general, durante la noche debes hacerlo con:',
    opciones: ['Luces altas', 'Luces bajas', 'Luces de estacionamiento'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En vías rurales durante la noche, la norma general es usar luces altas para mejor visibilidad. Se deben cambiar a bajas al encontrarse con otro vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2023,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al conducir tu vehículo durante la noche, por regla general, en las zonas urbanas debes hacerlo con:',
    opciones: ['Luces de estacionamiento solamente', 'Luces altas', 'Luces bajas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En zonas urbanas durante la noche se deben usar luces bajas, ya que las luces altas pueden encandilar a otros conductores y peatones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2024,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al conducir tu vehículo podrás usar la bocina para:',
    opciones: ['Apurar al vehículo que te antecede', 'Anunciar que estacionarás', 'Prevenir un siniestro, si ello es estrictamente necesario'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La bocina solo debe usarse para prevenir siniestros cuando sea estrictamente necesario. No debe utilizarse para apurar a otros conductores ni para otros fines.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2025,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si la parte trasera de tu vehículo patina hacia un costado debes:',
    opciones: ['Frenar bruscamente', 'Girar las ruedas delanteras en el mismo sentido que se desplaza la parte trasera del vehículo', 'Girar las ruedas delanteras en sentido contrario al que se desplaza la parte trasera del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al patinar la parte trasera, se deben girar las ruedas delanteras en el mismo sentido del patinaje para recuperar el control. Nunca frenes bruscamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true,
  },
  {
    id: 2026,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al transitar con tu vehículo podrás no tener espejo retrovisor interior, en los siguientes casos:',
    opciones: ['Cuando transites a baja velocidad', 'Cuando tu vehículo es de transporte de carga', 'En ninguno de los casos anteriores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de transporte de carga pueden no tener espejo retrovisor interior debido a que la carga puede impedir la visión trasera. Deben compensar con espejos exteriores.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2027,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuánto es el espacio lateral que debes dejar al adelantar a una persona ciclista?',
    opciones: ['2 metros', '1 metro', '1,5 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al adelantar a un ciclista se debe dejar un espacio lateral mínimo de 1,5 metros para garantizar la seguridad del ciclista.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2028,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes estacionar en ciclovías?',
    opciones: ['Sí', 'No', 'Solo por 30 minutos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Está prohibido estacionar en ciclovías. Estas vías son de uso exclusivo para bicicletas y otros ciclos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true,
  },
  {
    id: 2029,
    categoria: 'Mecánica Básica',
    pregunta: 'En comparación con un motor a bencina, ¿qué beneficio tiene un motor Diésel respecto al consumo de combustible y su duración?',
    opciones: ['Consumo y duración mayor', 'Consumo mayor y duración menor', 'Consumo menor y duración mayor'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El motor Diésel tiene menor consumo de combustible y mayor duración en comparación con un motor a bencina, lo que lo hace más eficiente para uso profesional.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2030,
    categoria: 'Mecánica Básica',
    pregunta: 'La emisión de monóxido de carbono y el número de revoluciones del motor Diésel son como se indica:',
    opciones: ['Mayores que en motores a bencina', 'Iguales', 'Menores que en el motor a gasolina'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El motor Diésel produce menores emisiones de monóxido de carbono y opera a menores revoluciones que un motor a bencina.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2031,
    categoria: 'Mecánica Básica',
    pregunta: 'La ignición de la mezcla se produce:',
    opciones: ['Con 1 bujía', 'Por la sola compresión del aire', 'Por la compresión del aire e inyección del petróleo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En un motor Diésel, la ignición se produce por la alta compresión del aire que eleva la temperatura, y al inyectarse el combustible este se enciende espontáneamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2032,
    categoria: 'Mecánica Básica',
    pregunta: 'Durante la carrera de compresión:',
    opciones: ['Se comprime mezcla de aire y petróleo', 'Se comprime aire', 'Se comprime petróleo pulverizado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En un motor Diésel, durante la carrera de compresión solo se comprime aire. El combustible se inyecta después, cuando el aire está a alta presión y temperatura.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2033,
    categoria: 'Mecánica Básica',
    pregunta: 'Acelerar rápidamente un motor Diésel es:',
    opciones: ['Positivo, pues así se produce un menor desgaste de los inyectores', 'Negativo, pues se produce un mayor desgaste de los anillos', 'Negativo, pues se produce una combustión incompleta'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Acelerar rápidamente un motor Diésel produce combustión incompleta, lo que genera mayor contaminación y desgaste innecesario del motor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2034,
    categoria: 'Mecánica Básica',
    pregunta: 'Los motores Diésel funcionan básicamente con:',
    opciones: ['Inyectores', 'Carburador igual al del motor a bencina', 'Un carburador especial'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los motores Diésel utilizan inyectores para introducir el combustible directamente en la cámara de combustión, a diferencia de los motores a bencina que pueden usar carburador.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2035,
    categoria: 'Mecánica Básica',
    pregunta: 'Los filtros de combustibles sirven para evitar:',
    opciones: ['Desgaste de partes vitales del motor', 'Ahogamiento del motor', 'Humo en el escape'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los filtros de combustible retienen impurezas que podrían dañar componentes vitales del motor como inyectores y bomba de combustible.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2036,
    categoria: 'Mecánica Básica',
    pregunta: 'Si el alternador de corriente del vehículo no carga, ¿qué pasa?',
    opciones: ['El motor deja de funcionar', 'Se descarga la batería', 'Se produce un desgaste rápido en los electrodos de las bujías'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si el alternador no carga, la batería se descarga progresivamente ya que no se repone la energía eléctrica consumida por el vehículo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2037,
    categoria: 'Mecánica Básica',
    pregunta: 'Cuando la rueda del vehículo se calienta, indica que:',
    opciones: ['El pedal de freno llega a fondo', 'Roza la balata (pastillas) por estar muy ajustadas', 'Falta de líquido de frenos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El calentamiento de la rueda indica que las pastillas de freno están rozando el disco por estar demasiado ajustadas, generando fricción excesiva.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2038,
    categoria: 'Mecánica Básica',
    pregunta: 'El nombre que recibe el marcador de revoluciones del motor es:',
    opciones: ['Manómetro', 'Tacómetro', 'Pluviómetro'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El tacómetro es el instrumento que mide las revoluciones por minuto (RPM) del motor. El manómetro mide presión y el pluviómetro mide lluvia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2039,
    categoria: 'Mecánica Básica',
    pregunta: 'El nivel correcto del electrolito en una batería es:',
    opciones: ['1 cm bajo nivel de las placas', 'Al nivel de las placas', 'Sobre 1 cm del nivel de las placas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El electrolito debe estar aproximadamente 1 cm sobre el nivel de las placas para asegurar el correcto funcionamiento de la batería.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2040,
    categoria: 'Mecánica Básica',
    pregunta: 'Si se corta la correa del ventilador:',
    opciones: ['El motor no funciona', 'El motor se calienta', 'El motor funciona solo en baja velocidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al cortarse la correa del ventilador, el sistema de refrigeración deja de funcionar correctamente y el motor se sobrecalienta.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2041,
    categoria: 'Mecánica Básica',
    pregunta: 'La función del embrague es:',
    opciones: ['Frenar el motor del vehículo', 'Darle fuerza al motor del vehículo', 'Conectar y desconectar la fuerza del motor a la caja de velocidades'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El embrague permite conectar y desconectar la transmisión de fuerza desde el motor hacia la caja de velocidades para cambiar de marcha.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2042,
    categoria: 'Mecánica Básica',
    pregunta: 'Una de las causas de que el motor de arranque no funcione es:',
    opciones: ['Cables de las bujías desconectados', 'Bobina en mal estado', 'Bornes de la batería sulfatados'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los bornes sulfatados de la batería impiden el paso de corriente eléctrica al motor de arranque, impidiendo que funcione.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2043,
    categoria: 'Mecánica Básica',
    pregunta: 'El exceso de inflado en un neumático produce:',
    opciones: ['Desgaste en los bordes de la banda de rodamiento', 'Desgaste en el centro de la banda de rodamiento del neumático', 'Deterioro de la válvula de inflado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El exceso de inflado hace que solo el centro del neumático haga contacto con el suelo, produciendo un desgaste desigual en el centro de la banda de rodamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2044,
    categoria: 'Mecánica Básica',
    pregunta: 'El desgaste disparejo de los neumáticos delanteros se debe a:',
    opciones: ['Exceso de velocidad en zona de curvas', 'Exceso de peso en el vehículo', 'Deficiente alineación del tren delantero y/o desgaste de amortiguadores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El desgaste disparejo de los neumáticos delanteros indica problemas de alineación del tren delantero o desgaste de amortiguadores.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2045,
    categoria: 'Mecánica Básica',
    pregunta: 'El conducir sin retirar totalmente el pie del pedal de embrague produce:',
    opciones: ['Desgaste en el motor del vehículo', 'Menor fuerza en el motor', 'Desgaste prematuro en balata de embrague'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Conducir con el pie apoyado en el pedal de embrague genera fricción constante en el disco de embrague, causando un desgaste prematuro.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2046,
    categoria: 'Mecánica Básica',
    pregunta: 'La excesiva temperatura en la batería puede deberse a:',
    opciones: ['Deficiente funcionamiento del regulador de voltaje', 'Poca chispa en las bujías', 'Demasiada agua destilada'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Un regulador de voltaje deficiente puede provocar sobrecarga de la batería, generando excesiva temperatura y posibles daños.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2047,
    categoria: 'Mecánica Básica',
    pregunta: 'Si con el motor funcionando se enciende la luz roja indicadora de presión de aceite, se debe:',
    opciones: ['Continuar la marcha', 'Detener inmediatamente el vehículo y el motor', 'Continuar muy lentamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La luz roja de presión de aceite indica falta de lubricación. Se debe detener inmediatamente el motor para evitar daños graves e irreversibles.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2048,
    categoria: 'Mecánica Básica',
    pregunta: 'Circulando con el vehículo se detecta que el motor se sobrecalienta; ello se puede deber a:',
    opciones: ['Circuito de refrigeración obstruido', 'Insuficiente paso de agua caliente al radiador de la calefacción', 'Batería con baja carga'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El sobrecalentamiento del motor generalmente se debe a una obstrucción en el circuito de refrigeración que impide la correcta circulación del refrigerante.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2049,
    categoria: 'Mecánica Básica',
    pregunta: 'Indica el modo más simple de limpiar los bornes sulfatados de la batería:',
    opciones: ['Ácido sulfúrico', 'Agua con bicarbonato', 'Agua destilada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El agua con bicarbonato de sodio neutraliza el ácido sulfúrico cristalizado en los bornes, siendo el método más simple y seguro de limpieza.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2050,
    categoria: 'Mecánica Básica',
    pregunta: 'Si durante la marcha del vehículo, se desconecta un cable de bujía:',
    opciones: ['El motor no funciona', 'El motor pierde fuerza', 'El motor gira la mitad de las revoluciones normales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al desconectarse un cable de bujía, un cilindro deja de funcionar, lo que causa pérdida de potencia pero el motor sigue funcionando con los cilindros restantes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2051,
    categoria: 'Mecánica Básica',
    pregunta: 'Si te encuentras bajando por una pendiente pronunciada, debes:',
    opciones: ['Utilizar permanentemente el freno de pie', 'Enganchar en el cambio de velocidad correspondiente', 'Presionar el pedal de embrague'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En pendientes pronunciadas se debe usar el freno motor enganchando una marcha baja. Usar solo el freno de pie puede provocar el sobrecalentamiento y falla de los frenos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2052,
    categoria: 'Mecánica Básica',
    pregunta: 'Cuando el tubo de escape expele humo azul significa que el vehículo está:',
    opciones: ['Mal carburado', 'Con el motor fuera de punto en el encendido', 'Quemando aceite'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El humo azul indica que el motor está quemando aceite, lo cual puede deberse a desgaste de anillos, sellos de válvulas u otros componentes internos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2053,
    categoria: 'Mecánica Básica',
    pregunta: 'Si el motor está sobrecalentado por falta de agua en el sistema de refrigeración:',
    opciones: ['Se debe agregar agua lentamente con el motor funcionando', 'No se debe agregar agua', 'Se debe agregar agua con el motor detenido'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Se debe agregar agua lentamente con el motor funcionando para evitar un choque térmico que podría dañar el bloque del motor.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2054,
    categoria: 'Mecánica Básica',
    pregunta: 'Al subir una cuesta en un cambio de velocidad no adecuado se produce:',
    opciones: ['Falla en el sistema de frenos', 'Falla en la caja de cambios', 'Exceso de consumo de combustible'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Subir una cuesta en una marcha inadecuada (muy alta) fuerza al motor a trabajar más, generando un consumo excesivo de combustible.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2055,
    categoria: 'Mecánica Básica',
    pregunta: 'Cuando un neumático delantero tiene baja presión:',
    opciones: ['La dirección del vehículo tiende hacia un lado', 'El motor pierde potencia', 'Se sobrecalienta el motor'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Un neumático con baja presión genera mayor resistencia al rodaje en ese lado, haciendo que la dirección del vehículo tire hacia el lado del neumático desinflado.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2056,
    categoria: 'Mecánica Básica',
    pregunta: 'El que los frenos rocen puede deberse a:',
    opciones: ['Mala regulación del pedal de freno', 'Falta líquido de freno', 'Mala regulación de balatas o pastillas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El roce de los frenos se debe principalmente a una mala regulación de las balatas o pastillas, que quedan demasiado cerca del disco o tambor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2057,
    categoria: 'Mecánica Básica',
    pregunta: 'Para que las bandas de los neumáticos se desgasten en forma pareja se debe efectuar:',
    opciones: ['Un recauchado cada 10.000 kilómetros', 'Una rotación periódica', 'Un redibujado cada 15.000 kilómetros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La rotación periódica de los neumáticos permite que se desgasten de manera uniforme, prolongando su vida útil.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2058,
    categoria: 'Mecánica Básica',
    pregunta: 'Antes de poner un vehículo en marcha, quien conduce debe verificar:',
    opciones: ['El funcionamiento del tubo de escape', 'El funcionamiento del freno, embrague e instrumentos del tablero', 'El estado de la carrocería'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de iniciar la marcha se deben verificar los sistemas de seguridad esenciales: frenos, embrague e instrumentos del tablero para asegurar un viaje seguro.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2059,
    categoria: 'Mecánica Básica',
    pregunta: 'Lo que recibe la fuerza de la explosión en un motor se denomina:',
    opciones: ['Pistón', 'Biela', 'Cigüeñal'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El pistón es la pieza que recibe directamente la fuerza de la explosión en la cámara de combustión y la transmite a la biela.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2060,
    categoria: 'Mecánica Básica',
    pregunta: 'La función del filtro de aceite es:',
    opciones: ['Restituir la viscosidad del aceite', 'Retener las partículas gruesas del aceite', 'Separar el combustible del aceite'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El filtro de aceite retiene las partículas e impurezas presentes en el aceite lubricante para mantener limpio el sistema de lubricación del motor.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2061,
    categoria: 'Mecánica Básica',
    pregunta: 'La función del filtro de aire es:',
    opciones: ['Separar el aire del aceite', 'Separar el aire del combustible', 'Retener las partículas contenidas en el aire, antes de entrar al carburador'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El filtro de aire retiene polvo y partículas del aire antes de que entre al motor, protegiendo los componentes internos del desgaste.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
  {
    id: 2062,
    categoria: 'Mecánica Básica',
    pregunta: 'La falta de presión de aire en los neumáticos produce:',
    opciones: ['Desgaste en el centro de la banda de rodamiento', 'Desgaste en los costados de la banda de rodamiento', 'Ninguna de las anteriores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La falta de presión hace que los costados del neumático soporten más peso, produciendo un desgaste desigual en los bordes de la banda de rodamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true,
  },
];
