import type { Question } from './questionsData';

const allTypes = ['clase_b', 'clase_a2', 'clase_a4', 'clase_c', 'clase_d', 'clase_e'];

export const questionsPart6: Question[] = [
  // =============================================
  // MECÁNICA Y MANTENIMIENTO PRÁCTICO (25 preguntas) - IDs 806-830
  // =============================================
  {
    id: 806,
    categoria: 'Mecánica Básica',
    pregunta: 'Su vehículo se desvía hacia un lado cuando frena. ¿Qué debería hacer?',
    opciones: ['Seguir conduciendo con precaución', 'Consultar con un mecánico lo antes posible', 'Aumentar la presión de los neumáticos', 'Cambiar el líquido de frenos usted mismo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si el vehículo se desvía al frenar, indica un problema en el sistema de frenos, como pastillas desgastadas de forma desigual, un pistón de caliper atascado o diferencia de presión en el circuito hidráulico. Debe consultar con un mecánico especializado de inmediato, ya que conducir en esa condición es peligroso y puede provocar pérdida de control.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 807,
    categoria: 'Mecánica Básica',
    pregunta: 'Mientras conduce siente un fuerte olor a gasolina. ¿Qué debe hacer?',
    opciones: ['Abrir las ventanas y seguir conduciendo', 'Detenerse en un lugar seguro e investigar la causa', 'Acelerar para ventilar el motor', 'Ignorarlo si el motor funciona bien'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un fuerte olor a gasolina mientras conduce puede indicar una fuga de combustible, lo cual representa un grave riesgo de incendio. Debe detenerse de inmediato en un lugar seguro, apagar el motor, no encender fuego ni dispositivos eléctricos, y verificar si hay fugas visibles. Llame a asistencia mecánica si detecta el problema.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 808,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cómo puede prevenir el riesgo de incendio en su vehículo?',
    opciones: ['Lavando el motor frecuentemente', 'Revisando ante olores extraños y manteniendo el sistema eléctrico en buen estado', 'Llevando siempre un extintor grande', 'Usando gasolina de mayor octanaje'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para prevenir incendios vehiculares, es fundamental estar atento a olores extraños como gasolina o cables quemados, mantener el sistema eléctrico en buen estado, revisar periódicamente las mangueras y conexiones del motor, y asegurarse de que no haya fugas de combustible o aceite. Un mantenimiento preventivo regular es la mejor protección.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 809,
    categoria: 'Mecánica Básica',
    pregunta: '¿Por qué es importante usar zapatos apropiados al conducir?',
    opciones: ['Para mayor comodidad durante viajes largos', 'Para un adecuado control de los pedales', 'Por razones estéticas', 'Para evitar multas de tránsito'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Usar zapatos apropiados permite un control preciso de los pedales de freno, acelerador y embrague. Conducir con sandalias, tacos altos, chancletas o descalzo puede hacer que el pie resbale de los pedales o no ejerza la presión necesaria. La falta de control sobre los pedales puede causar accidentes graves, especialmente en situaciones de emergencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 810,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué elemento del vehículo reduce el riesgo de lesiones de cuello en una colisión trasera?',
    opciones: ['El cinturón de seguridad', 'El apoya-cabeza correctamente ajustado', 'El airbag delantero', 'Los espejos retrovisores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El apoya-cabeza correctamente ajustado es fundamental para prevenir el latigazo cervical (whiplash) en colisiones traseras. Debe estar a la altura de la parte superior de la cabeza y lo más cerca posible de ella. Un apoya-cabeza mal ajustado o demasiado bajo puede agravar las lesiones en lugar de prevenirlas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 811,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuándo se debe chequear la presión de los neumáticos?',
    opciones: ['Después de conducir en carretera', 'Cuando los neumáticos están calientes', 'Cuando los neumáticos están fríos', 'Solo cuando se ven desinflados'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La presión de los neumáticos debe medirse cuando están fríos, es decir, antes de conducir o después de haber recorrido menos de 3 kilómetros. Al rodar, los neumáticos se calientan y la presión del aire aumenta, dando una lectura falsa más alta. Medir en caliente puede llevar a dejar los neumáticos con presión insuficiente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 812,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué líquido del vehículo en nivel bajo podría causar directamente un accidente?',
    opciones: ['Líquido limpiaparabrisas', 'Líquido refrigerante', 'Líquido de frenos', 'Aceite del motor'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El líquido de frenos es esencial para el funcionamiento del sistema de frenado hidráulico. Si su nivel es bajo, puede indicar una fuga o desgaste excesivo de las pastillas. Un nivel insuficiente puede provocar falla parcial o total de los frenos, causando directamente un accidente. Debe revisarse periódicamente y nunca debe estar por debajo del nivel mínimo.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 813,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál es la profundidad mínima legal de los surcos (dibujo) de un neumático?',
    opciones: ['1.0 mm', '1.6 mm', '2.0 mm', '3.0 mm'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La profundidad mínima legal del dibujo de los neumáticos es de 1.6 mm. Por debajo de esta medida, el neumático pierde capacidad de evacuación de agua y adherencia, aumentando significativamente el riesgo de aquaplaning y alargando la distancia de frenado. Se recomienda cambiar los neumáticos antes de llegar al mínimo legal.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 814,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué debe hacer si se revienta un neumático trasero mientras conduce?',
    opciones: ['Frenar bruscamente para detenerse rápido', 'Detenerse lentamente al costado de la vía sin frenar bruscamente', 'Acelerar para mantener el control', 'Girar el volante hacia el lado contrario'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si se revienta un neumático trasero, debe sujetar firmemente el volante, soltar el acelerador gradualmente sin frenar bruscamente, encender las luces de emergencia y dirigirse lentamente hacia el costado de la vía. Un frenado brusco podría hacer que el vehículo derrape o pierda el control. La clave es desacelerar de forma progresiva.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 815,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué debe hacer si se revienta un neumático delantero mientras conduce?',
    opciones: ['Soltar el volante para que el auto se enderece', 'Sostener firmemente el volante y desacelerar gradualmente', 'Frenar con fuerza inmediatamente', 'Girar bruscamente hacia la berma'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un reventón de neumático delantero, lo más importante es sostener firmemente el volante con ambas manos ya que el vehículo tenderá a desviarse hacia el lado del neumático reventado. Suelte el acelerador gradualmente, no frene bruscamente, y diríjase con cuidado al costado de la vía. El control del volante es fundamental.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 816,
    categoria: 'Mecánica Básica',
    pregunta: '¿Por qué no se debe desenganchar el motor (poner en neutro) al circular?',
    opciones: ['Porque gasta más combustible', 'Porque se pierde el frenado del motor', 'Porque daña la transmisión', 'Porque se apaga el motor automáticamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al desenganchar el motor o circular en neutro se pierde el efecto de freno motor, que ayuda a controlar la velocidad especialmente en pendientes. Sin freno motor, se depende exclusivamente de los frenos mecánicos, lo que puede provocar su sobrecalentamiento y pérdida de eficacia. Además, se pierde capacidad de reacción ante emergencias.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 817,
    categoria: 'Mecánica Básica',
    pregunta: 'Si la presión de aire en los neumáticos delanteros es baja, ¿qué efecto tendrá en la conducción?',
    opciones: ['El vehículo vibrará a alta velocidad', 'La dirección se sentirá más pesada y difícil de mover', 'El vehículo frenará más rápido', 'No tendrá ningún efecto notable'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La baja presión en los neumáticos delanteros hace que la dirección se sienta más pesada y difícil de mover, porque aumenta la superficie de contacto y la resistencia al rodamiento. Además, causa desgaste irregular del neumático, mayor consumo de combustible y puede provocar sobrecalentamiento del neumático, aumentando el riesgo de reventón.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 818,
    categoria: 'Mecánica Básica',
    pregunta: '¿A qué se debe principalmente un alto consumo de combustible?',
    opciones: ['Usar aire acondicionado ocasionalmente', 'Frecuentes frenadas y aceleraciones bruscas', 'Conducir en carretera a velocidad constante', 'Usar gasolina de alto octanaje'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las frenadas y aceleraciones bruscas y frecuentes son la principal causa de alto consumo de combustible. Cada aceleración brusca gasta significativamente más combustible que una aceleración suave. Conducir de manera agresiva puede aumentar el consumo hasta en un 40%. La conducción eficiente implica anticiparse al tráfico y mantener velocidad constante.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 819,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué característica tiene el monóxido de carbono presente en los gases de escape?',
    opciones: ['Tiene un olor fuerte y desagradable', 'Es visible como humo negro', 'Es inodoro, incoloro y potencialmente mortal', 'Solo es peligroso en grandes cantidades'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El monóxido de carbono (CO) es un gas inodoro, incoloro y altamente tóxico presente en los gases de escape. Es potencialmente mortal porque no puede detectarse por los sentidos. Por esto, nunca se debe dejar el motor encendido en espacios cerrados como garajes. La exposición prolongada causa intoxicación que puede llevar a la muerte.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 820,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál es la principal ventaja del sistema de frenos ABS?',
    opciones: ['Reduce la distancia de frenado en seco', 'Permite mantener el control de la dirección durante el frenado de emergencia', 'Elimina la necesidad de mantenimiento de frenos', 'Frena automáticamente ante obstáculos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La principal ventaja del sistema ABS (Sistema de Frenos Antibloqueo) es que permite mantener el control de la dirección durante un frenado de emergencia, ya que evita que las ruedas se bloqueen. Esto permite al conductor esquivar obstáculos mientras frena. Con ABS, se debe presionar el pedal de freno con firmeza y mantenerlo presionado sin bombear.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 821,
    categoria: 'Mecánica Básica',
    pregunta: 'Si el nivel de líquido de frenos baja constantemente, ¿qué indica?',
    opciones: ['Es normal por evaporación', 'Puede haber una fuga en el sistema de frenos', 'Los frenos están funcionando correctamente', 'Se debe a las altas temperaturas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si el nivel de líquido de frenos baja constantemente, probablemente existe una fuga en el sistema hidráulico de frenado, lo cual es extremadamente peligroso. El líquido de frenos no se evapora ni se consume en condiciones normales. Una fuga puede provocar falla total de los frenos. Debe llevar el vehículo al mecánico de inmediato.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 822,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué puede indicar un desgaste irregular en los neumáticos?',
    opciones: ['Que el neumático es de mala calidad', 'Problemas de alineación, suspensión o presión incorrecta', 'Que se conduce demasiado rápido', 'Que el neumático es nuevo y se está asentando'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El desgaste irregular de los neumáticos puede indicar problemas de alineación (desgaste en un borde), suspensión defectuosa o presión incorrecta. Si se desgasta más al centro, hay exceso de presión; si se desgasta más en los bordes, falta presión. Estos problemas afectan la seguridad y deben corregirse revisando alineación, balanceo y presión.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 823,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué debe revisar antes de un viaje largo?',
    opciones: ['Solo el nivel de combustible', 'Neumáticos, frenos, luces, niveles de líquidos y documentos', 'Solo la presión de los neumáticos', 'Solo el aceite del motor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de un viaje largo se debe revisar: presión y estado de los neumáticos (incluyendo el de repuesto), nivel de aceite, líquido de frenos, refrigerante y limpiaparabrisas, funcionamiento de todas las luces, estado de los frenos, y portar todos los documentos y elementos de seguridad obligatorios como triángulo y extintor.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 824,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica la luz de advertencia de temperatura del motor encendida?',
    opciones: ['El motor está funcionando normalmente', 'El motor se está sobrecalentando y debe detenerse', 'Necesita más aceite de motor', 'La calefacción está activada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La luz de temperatura encendida indica que el motor se está sobrecalentando. Debe detenerse de inmediato en un lugar seguro y apagar el motor. Continuar conduciendo puede causar daños graves y costosos al motor, como la deformación de la culata. Espere a que se enfríe antes de revisar el nivel de refrigerante y busque asistencia.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 825,
    categoria: 'Mecánica Básica',
    pregunta: '¿Con qué frecuencia se recomienda cambiar el aceite del motor?',
    opciones: ['Cada 20.000 km', 'Según las indicaciones del fabricante, generalmente entre 5.000 y 10.000 km', 'Solo cuando la luz de aceite se enciende', 'Una vez al año independiente del kilometraje'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El cambio de aceite debe realizarse según las recomendaciones del fabricante, generalmente cada 5.000 a 10.000 km o cada 6 meses, lo que ocurra primero. El aceite lubrica las partes móviles del motor, reduce la fricción y disipa el calor. Un aceite degradado pierde sus propiedades y puede causar desgaste prematuro del motor.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 826,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué sucede si conduce con los frenos de mano parcialmente activados?',
    opciones: ['No pasa nada si es por poco tiempo', 'Se sobrecalientan los frenos traseros y se reduce su eficacia', 'Mejora la estabilidad del vehículo', 'Solo aumenta levemente el consumo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Conducir con el freno de mano parcialmente activado genera un sobrecalentamiento de los frenos traseros que reduce significativamente su eficacia. Además, desgasta prematuramente las pastillas y discos traseros, aumenta el consumo de combustible y puede producir olores a quemado. Siempre verifique que el freno de mano esté completamente suelto antes de conducir.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 827,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumple el líquido refrigerante del motor?',
    opciones: ['Lubricar las piezas del motor', 'Mantener la temperatura del motor en un rango óptimo de funcionamiento', 'Limpiar el sistema de inyección', 'Mejorar el rendimiento del combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El líquido refrigerante circula por el motor absorbiendo el calor generado por la combustión y disipándolo a través del radiador. Mantiene la temperatura del motor en un rango óptimo de funcionamiento, evitando el sobrecalentamiento. Nunca se debe abrir la tapa del radiador con el motor caliente, ya que puede causar quemaduras graves por la presión acumulada.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 828,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué debe hacer si la dirección del vehículo se siente inusualmente dura?',
    opciones: ['Es normal en vehículos antiguos', 'Revisar el nivel de líquido de dirección hidráulica y llevar al mecánico', 'Girar el volante con más fuerza', 'Conducir más rápido para que se suavice'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una dirección inusualmente dura puede indicar bajo nivel de líquido de dirección hidráulica, falla en la bomba de dirección asistida, o problemas en la correa que la acciona. Conducir en esta condición dificulta las maniobras y puede ser peligroso en situaciones de emergencia. Debe revisarse lo antes posible por un mecánico calificado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 829,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué efecto tiene un exceso de presión en los neumáticos?',
    opciones: ['Mayor adherencia en curvas', 'Menor desgaste del neumático', 'Desgaste en la parte central del neumático y menor adherencia', 'Mejor rendimiento de combustible sin desventajas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El exceso de presión en los neumáticos provoca un desgaste prematuro en la parte central de la banda de rodadura, reduce la superficie de contacto con el pavimento y disminuye la adherencia. Esto aumenta la distancia de frenado y hace al vehículo más susceptible a irregularidades del camino. Siempre mantenga la presión recomendada por el fabricante.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 830,
    categoria: 'Mecánica Básica',
    pregunta: '¿Por qué es importante que el tubo de escape no tenga fugas?',
    opciones: ['Solo por razones de ruido', 'Porque los gases tóxicos pueden entrar al habitáculo del vehículo', 'Porque reduce la potencia del motor', 'Solo por razones estéticas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un tubo de escape con fugas puede permitir que gases tóxicos, especialmente monóxido de carbono, entren al habitáculo del vehículo a través del piso o las juntas. El monóxido de carbono es inodoro e incoloro y puede causar somnolencia, pérdida de conciencia e incluso la muerte. Cualquier fuga debe repararse de inmediato.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },

  // =============================================
  // DISTANCIAS Y FÍSICA DEL VEHÍCULO (25 preguntas) - IDs 831-855
  // =============================================
  {
    id: 831,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se calcula la distancia total de detención de un vehículo?',
    opciones: ['Solo la distancia de frenado', 'Distancia de reacción más distancia de frenado', 'Velocidad multiplicada por tiempo', 'Distancia de reacción menos distancia de frenado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La distancia total de detención es la suma de la distancia de reacción (espacio recorrido desde que se percibe el peligro hasta que se pisa el freno) más la distancia de frenado (espacio recorrido desde que se aplican los frenos hasta detenerse). Ambas dependen de la velocidad, y a mayor velocidad, mayor será la distancia total necesaria.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 832,
    categoria: 'Conducción Segura',
    pregunta: 'Si duplica la velocidad de su vehículo, ¿qué sucede con la distancia de reacción?',
    opciones: ['Se mantiene igual', 'Se duplica', 'Se triplica', 'Se cuadruplica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La distancia de reacción es directamente proporcional a la velocidad. Si duplica la velocidad, recorrerá el doble de distancia durante el tiempo de reacción (que es constante). Por ejemplo, si a 50 km/h recorre 14 metros durante su tiempo de reacción, a 100 km/h recorrerá 28 metros antes de comenzar a frenar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 833,
    categoria: 'Conducción Segura',
    pregunta: 'Si duplica la velocidad, ¿qué sucede con la distancia de frenado?',
    opciones: ['Se duplica', 'Se triplica', 'Se cuadruplica', 'Se mantiene igual'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La distancia de frenado aumenta con el cuadrado de la velocidad. Si duplica la velocidad, la distancia de frenado se cuadruplica (se multiplica por cuatro). Esto se debe a que la energía cinética del vehículo es proporcional al cuadrado de la velocidad. Por ejemplo, si a 50 km/h necesita 25 metros para frenar, a 100 km/h necesitará 100 metros.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 834,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se relaciona la energía cinética de un vehículo con su velocidad?',
    opciones: ['Es directamente proporcional a la velocidad', 'Es inversamente proporcional a la velocidad', 'Es proporcional al cuadrado de la velocidad', 'No tiene relación con la velocidad'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La energía cinética de un vehículo es proporcional al cuadrado de su velocidad. Esto significa que al duplicar la velocidad, la energía cinética se cuadruplica. Esta energía debe ser absorbida por los frenos para detener el vehículo, lo que explica por qué la distancia de frenado aumenta exponencialmente con la velocidad y por qué los accidentes a alta velocidad son más destructivos.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 835,
    categoria: 'Conducción Segura',
    pregunta: '¿Aproximadamente qué distancia necesita un tren para detenerse cuando circula a 100 km/h?',
    opciones: ['100 a 200 metros', '300 a 500 metros', '800 a 1.000 metros', '50 a 100 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Un tren que circula a 100 km/h necesita aproximadamente entre 800 y 1.000 metros para detenerse completamente, debido a su enorme masa e inercia. Por esta razón, los cruces ferroviarios son extremadamente peligrosos y se debe respetar siempre la señalización. Nunca intente cruzar las vías si se aproxima un tren, incluso si parece estar lejos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 836,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la regla para mantener una distancia mínima de seguimiento segura?',
    opciones: ['Mantener al menos 5 metros de distancia', 'Mantener al menos 2 segundos de distancia respecto al vehículo de adelante', 'Mantener al menos 10 metros de distancia', 'Depende del tamaño del vehículo de adelante'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La regla de los 2 segundos establece que debe mantener al menos 2 segundos de distancia con el vehículo que va adelante. Para verificarlo, elija un punto fijo: cuando el vehículo de adelante lo pase, cuente "mil uno, mil dos". Si usted pasa ese punto antes de terminar, está demasiado cerca. En condiciones adversas, aumente a 4 segundos o más.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 837,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene la alta velocidad sobre el campo visual del conductor?',
    opciones: ['Lo amplía permitiendo ver más', 'Lo reduce progresivamente (efecto túnel)', 'No tiene ningún efecto', 'Mejora la percepción periférica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'A mayor velocidad, el campo visual del conductor se reduce progresivamente, fenómeno conocido como "efecto túnel". A 40 km/h el campo visual es de aproximadamente 100 grados, pero a 130 km/h se reduce a solo 30 grados. Esto dificulta la detección de peatones, ciclistas y otros peligros en los costados de la vía.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 838,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo influyen neumáticos desgastados en la distancia de frenado sobre pavimento mojado?',
    opciones: ['No tienen influencia significativa', 'Disminuyen la distancia de frenado', 'Aumentan considerablemente la distancia de frenado', 'Solo afectan en curvas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los neumáticos desgastados aumentan considerablemente la distancia de frenado en pavimento mojado, ya que los surcos del neumático son los encargados de evacuar el agua entre el neumático y el asfalto. Con surcos desgastados, se forma una capa de agua que impide el contacto, generando aquaplaning y perdiendo toda capacidad de frenado y dirección.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 839,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el tiempo de reacción promedio de un conductor en buenas condiciones?',
    opciones: ['0.5 segundos', '1 segundo', '2 segundos', '3 segundos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El tiempo de reacción promedio de un conductor alerta y en buenas condiciones es de aproximadamente 1 segundo. Este tiempo incluye percibir el peligro, decidir qué hacer y actuar sobre los controles. La fatiga, el alcohol, las drogas, las distracciones y la edad avanzada pueden aumentar significativamente este tiempo, incrementando la distancia de reacción.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 840,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué factores aumentan la distancia de frenado?',
    opciones: ['Solo la velocidad del vehículo', 'Velocidad, lluvia, neumáticos desgastados, pendiente descendente y frenos en mal estado', 'Solo el estado de los neumáticos', 'Solo las condiciones climáticas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Múltiples factores aumentan la distancia de frenado: la velocidad (relación cuadrática), pavimento mojado o con hielo, neumáticos desgastados o con presión incorrecta, pendiente descendente, frenos en mal estado o sobrecalentados, carga excesiva del vehículo y tipo de superficie (tierra, grava). Todos estos factores pueden combinarse haciendo la distancia aún mayor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 841,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la forma correcta de frenar en una situación normal?',
    opciones: ['Pisar el freno a fondo de golpe', 'Aplicar el freno de forma progresiva y suave', 'Bombear el pedal de freno repetidamente', 'Usar solo el freno de mano'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En condiciones normales, el frenado debe ser progresivo y suave: presionar el pedal gradualmente aumentando la presión según se necesite, y luego aliviar la presión justo antes de detenerse para evitar una parada brusca. Este tipo de frenado es más seguro, cómodo para los pasajeros, reduce el desgaste de frenos y neumáticos, y evita que las ruedas se bloqueen.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 842,
    categoria: 'Conducción Segura',
    pregunta: 'A 100 km/h, ¿qué distancia recorre su vehículo durante el tiempo de reacción de 1 segundo?',
    opciones: ['Aproximadamente 14 metros', 'Aproximadamente 20 metros', 'Aproximadamente 28 metros', 'Aproximadamente 36 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'A 100 km/h el vehículo recorre aproximadamente 28 metros cada segundo. Esto significa que durante el segundo de reacción, el vehículo avanza 28 metros sin que se hayan aplicado los frenos. A esto hay que sumar la distancia de frenado. Por ello, es vital mantener una distancia de seguimiento adecuada y estar siempre alerta.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 843,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué ocurre con la distancia de frenado en pavimento mojado comparado con seco?',
    opciones: ['Disminuye ligeramente', 'Se mantiene igual', 'Puede duplicarse o más', 'Aumenta solo un 10%'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En pavimento mojado, la distancia de frenado puede duplicarse o incluso triplicarse respecto al pavimento seco. El agua actúa como lubricante entre el neumático y el asfalto, reduciendo significativamente la adherencia. Por esta razón, en condiciones de lluvia debe reducir la velocidad, aumentar la distancia de seguimiento y frenar con mayor anticipación.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 844,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué la distancia de seguimiento se mide en tiempo (segundos) y no en metros?',
    opciones: ['Porque es más fácil de calcular', 'Porque los segundos se adaptan automáticamente a cualquier velocidad', 'Porque los metros son imprecisos', 'No hay razón especial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Medir la distancia de seguimiento en segundos es más práctico porque se adapta automáticamente a cualquier velocidad. A mayor velocidad, 2 segundos representan más metros, que es exactamente lo que se necesita. A 50 km/h, 2 segundos equivalen a unos 28 metros; a 100 km/h, a unos 56 metros. El conductor no necesita calcular distancias precisas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 845,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene la carga excesiva del vehículo sobre la distancia de frenado?',
    opciones: ['La reduce por mayor peso sobre las ruedas', 'La aumenta porque se necesita más fuerza para detener mayor masa', 'No tiene efecto', 'Depende del tipo de frenos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un vehículo con carga excesiva tiene mayor inercia y requiere más energía para detenerse, lo que aumenta la distancia de frenado. Además, la sobrecarga afecta la estabilidad del vehículo, modifica su centro de gravedad y puede sobreexigir la suspensión y los frenos. Nunca exceda la carga máxima indicada por el fabricante del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 846,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué sucede con el frenado si los frenos se sobrecalientan (fading)?',
    opciones: ['Frenan mejor por el calor', 'Pierden eficacia progresivamente', 'No se ven afectados', 'Solo afecta a los frenos de tambor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El sobrecalentamiento de los frenos, conocido como "fading", provoca una pérdida progresiva de la eficacia del frenado. El líquido de frenos puede hervir formando burbujas de vapor que comprimen en lugar de transmitir presión. Ocurre comúnmente al descender pendientes largas usando solo los frenos. Se previene usando el freno motor en marchas bajas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 847,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué distancia de seguimiento debe mantener en condiciones de lluvia intensa?',
    opciones: ['La misma que en seco (2 segundos)', 'Al menos 4 segundos', '1 segundo es suficiente', '3 metros más que en seco'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En condiciones de lluvia intensa, la distancia de seguimiento debe aumentarse al menos al doble, es decir, a un mínimo de 4 segundos. Esto se debe a que la distancia de frenado aumenta significativamente en pavimento mojado, la visibilidad se reduce y se necesita más tiempo para reaccionar. En condiciones extremas como hielo o niebla, la distancia debe ser aún mayor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 848,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué relación existe entre el peso del vehículo y su energía cinética?',
    opciones: ['No tienen relación', 'La energía cinética es directamente proporcional al peso', 'La energía cinética es inversamente proporcional al peso', 'Solo importa la velocidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La energía cinética es directamente proporcional a la masa del vehículo. Un vehículo el doble de pesado tiene el doble de energía cinética a la misma velocidad. Por eso un camión necesita mayor distancia de frenado que un automóvil a la misma velocidad. La fórmula es: Ec = ½ × masa × velocidad², donde tanto masa como velocidad influyen.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 849,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué ocurre con la distancia de frenado en una pendiente descendente?',
    opciones: ['Disminuye por la gravedad', 'Aumenta porque la gravedad impulsa el vehículo hacia adelante', 'No cambia respecto a terreno plano', 'Depende solo del tipo de frenos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En una pendiente descendente, la distancia de frenado aumenta porque la fuerza de gravedad impulsa el vehículo cuesta abajo, sumándose a la inercia del movimiento. Los frenos deben contrarrestar no solo la energía cinética sino también la componente gravitatoria. Por ello, en bajadas se debe usar el freno motor en marchas bajas y aumentar la distancia de seguimiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 850,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo afecta la fatiga al tiempo de reacción del conductor?',
    opciones: ['No lo afecta significativamente', 'Lo reduce haciéndolo más rápido', 'Lo aumenta considerablemente', 'Solo afecta la visión, no la reacción'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La fatiga aumenta considerablemente el tiempo de reacción del conductor, pudiendo duplicarlo o triplicarlo. Un conductor fatigado tarda más en percibir el peligro, procesar la información y actuar sobre los controles. Además, la fatiga reduce la concentración, afecta la toma de decisiones y puede provocar microsueños. Se recomienda descansar cada 2 horas o 200 kilómetros.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 851,
    categoria: 'Conducción Segura',
    pregunta: '¿A qué velocidad un impacto contra un objeto fijo equivale aproximadamente a caer de un tercer piso?',
    opciones: ['30 km/h', '50 km/h', '80 km/h', '100 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un impacto a 50 km/h contra un objeto fijo equivale aproximadamente a caer desde un tercer piso (unos 10 metros de altura). A esta velocidad, la probabilidad de lesiones graves o mortales para ocupantes sin cinturón es muy alta. Esto demuestra por qué incluso a velocidades urbanas un accidente puede ser fatal si no se usan los elementos de seguridad.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 852,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué ocurre con un pasajero sin cinturón en una colisión a 50 km/h?',
    opciones: ['Puede sujetarse fácilmente con las manos', 'Sale proyectado con una fuerza equivalente a varias veces su peso', 'El airbag lo protege completamente', 'Solo sufre lesiones leves'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En una colisión a 50 km/h, un pasajero sin cinturón sale proyectado con una fuerza equivalente a 30 veces su peso corporal. Es imposible sujetarse con las manos a esa fuerza. Un pasajero de 70 kg genera un impacto equivalente a 2.100 kg. Puede ser lanzado contra el parabrisas, el tablero o contra otros ocupantes, causando lesiones graves o mortales.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 853,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuánto aumenta la distancia de frenado si triplica la velocidad?',
    opciones: ['Se triplica', 'Se multiplica por 6', 'Se multiplica por 9', 'Se multiplica por 4'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Si se triplica la velocidad, la distancia de frenado se multiplica por 9, ya que es proporcional al cuadrado de la velocidad (3² = 9). Por ejemplo, si a 30 km/h se necesitan 5 metros para frenar, a 90 km/h se necesitarán 45 metros. Esta relación exponencial demuestra lo peligroso que es el exceso de velocidad.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 854,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué influencia tiene el tipo de pavimento en la distancia de frenado?',
    opciones: ['No tiene influencia', 'El tipo de pavimento afecta la adherencia y por tanto la distancia de frenado', 'Solo influye si el pavimento está mojado', 'Solo influye en vehículos pesados'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El tipo de pavimento afecta directamente la adherencia y por tanto la distancia de frenado. El asfalto seco ofrece mejor adherencia, mientras que la grava, tierra, adoquines mojados o asfalto con hielo la reducen significativamente. Un pavimento recién asfaltado puede ser más resbaladizo por los aceites superficiales. El conductor debe adaptar su velocidad al tipo de superficie.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 855,
    categoria: 'Conducción Segura',
    pregunta: '¿A 60 km/h, cuántos metros recorre un vehículo en 1 segundo?',
    opciones: ['Aproximadamente 10 metros', 'Aproximadamente 17 metros', 'Aproximadamente 25 metros', 'Aproximadamente 30 metros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'A 60 km/h, un vehículo recorre aproximadamente 17 metros por segundo (60.000 metros/3.600 segundos = 16,7 m/s). Esto significa que durante el segundo de tiempo de reacción, el conductor avanza 17 metros sin frenar. Esta información es crucial para entender la importancia de mantener distancia y estar atento al tráfico.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },

  // =============================================
  // SEGURIDAD PASIVA Y ACTIVA (25 preguntas) - IDs 856-880
  // =============================================
  {
    id: 856,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la principal función del cinturón de seguridad?',
    opciones: ['Evitar que el conductor se mueva en curvas', 'Retener al ocupante en su asiento durante una colisión o frenado brusco', 'Cumplir con la ley de tránsito', 'Proteger al conductor de objetos exteriores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La principal función del cinturón de seguridad es retener al ocupante en su asiento durante una colisión o frenado brusco, evitando que sea proyectado contra el interior del vehículo o expulsado del mismo. Reduce el riesgo de muerte hasta en un 50% en accidentes frontales. Distribuye las fuerzas del impacto sobre las partes más resistentes del cuerpo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 857,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe usarse correctamente el cinturón de seguridad?',
    opciones: ['La banda superior sobre el hombro y la inferior sobre las caderas', 'La banda superior bajo el brazo para mayor comodidad', 'Solo la banda inferior es necesaria', 'Puede usarse holgado para mayor comodidad'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El cinturón debe colocarse con la banda diagonal sobre el hombro y el pecho (nunca bajo el brazo o detrás de la espalda) y la banda inferior sobre las caderas, no sobre el abdomen. Debe quedar ajustado al cuerpo sin holgura excesiva. Un cinturón mal colocado puede causar lesiones en lugar de proteger durante un impacto.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 858,
    categoria: 'Conducción Segura',
    pregunta: '¿Los airbags reemplazan la necesidad de usar cinturón de seguridad?',
    opciones: ['Sí, los airbags son suficiente protección', 'No, los airbags complementan al cinturón pero no lo reemplazan', 'Solo en ciudad donde las velocidades son bajas', 'Sí, si el vehículo tiene airbags laterales también'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los airbags NO reemplazan el cinturón de seguridad; son un complemento. El cinturón retiene al ocupante en la posición correcta para que el airbag sea efectivo. Sin cinturón, el ocupante puede desplazarse e impactar contra el airbag en una posición incorrecta, lo que puede causar lesiones graves o la muerte. Ambos sistemas trabajan en conjunto.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 859,
    categoria: 'Conducción Segura',
    pregunta: '¿Para qué sirve el seguro de niños en las puertas traseras del vehículo?',
    opciones: ['Para evitar robos del vehículo', 'Para impedir que los niños abran las puertas desde el interior', 'Para proteger las puertas de daños', 'Para activar la alarma del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El seguro de niños en las puertas traseras es un dispositivo que impide que las puertas sean abiertas desde el interior del vehículo. Esto previene que un niño abra la puerta mientras el vehículo está en movimiento, lo que podría provocar su caída a la vía. Es fundamental activarlo siempre que viajen menores en los asientos traseros.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 860,
    categoria: 'Conducción Segura',
    pregunta: '¿Es obligatorio el uso del cinturón de seguridad en los asientos traseros?',
    opciones: ['No, solo es obligatorio en los asientos delanteros', 'Sí, es obligatorio para todos los ocupantes del vehículo', 'Solo para menores de edad', 'Solo en carretera'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El uso del cinturón de seguridad es obligatorio para TODOS los ocupantes del vehículo, tanto en asientos delanteros como traseros. Un pasajero sin cinturón en el asiento trasero puede salir proyectado hacia adelante en una colisión, impactando a los ocupantes delanteros con una fuerza letal. El incumplimiento constituye una infracción grave.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 861,
    categoria: 'Conducción Segura',
    pregunta: '¿Se puede llevar a un niño pequeño dentro del cinturón de seguridad del adulto?',
    opciones: ['Sí, si el adulto lo sujeta firmemente', 'No, nunca se debe llevar a un niño dentro del cinturón del adulto', 'Solo en trayectos cortos', 'Sí, si el niño está dormido'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Nunca se debe llevar a un niño dentro del cinturón del adulto. En una colisión, el cuerpo del adulto aplasta al niño contra el cinturón con una fuerza enorme. El niño actuaría como un "airbag" para el adulto, sufriendo lesiones gravísimas o la muerte. Los niños deben usar siempre su propio sistema de retención infantil adecuado a su edad y peso.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 862,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué elementos del vehículo es importante mantener siempre limpios?',
    opciones: ['Solo el parabrisas', 'Luces, espejos retrovisores, vidrios y patente', 'Solo las luces delanteras', 'Solo los espejos laterales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Es fundamental mantener limpios: las luces (delanteras, traseras, intermitentes) para ser vistos, los espejos retrovisores para una visión clara, todos los vidrios para máxima visibilidad, y las patentes para ser identificados. Elementos sucios reducen significativamente la visibilidad y pueden impedir que otros conductores vean sus señales, aumentando el riesgo de accidentes.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 863,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuándo se deben usar las luces intermitentes de advertencia (balizas)?',
    opciones: ['Al estacionar en doble fila', 'En caso de pana, emergencia o para advertir un peligro adelante', 'Siempre que llueva', 'Al circular lentamente por una zona escolar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las luces intermitentes de advertencia (balizas) deben usarse cuando el vehículo está detenido por una pana o emergencia en la vía, para advertir a los conductores detrás de un peligro adelante (como un accidente o congestión repentina en carretera), o cuando se remolca un vehículo. No deben usarse como excusa para estacionar ilegalmente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 864,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la posición correcta del conductor al sentarse al volante?',
    opciones: ['Lo más lejos posible del volante', 'Con los brazos estirados y las piernas rectas', 'Con los brazos ligeramente flexionados, espalda apoyada y pudiendo pisar los pedales a fondo', 'Reclinado hacia atrás para mayor comodidad'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La posición correcta implica: espalda completamente apoyada en el respaldo, brazos ligeramente flexionados al tomar el volante en posición "9 y 3" o "10 y 2", piernas con flexión suficiente para pisar los pedales a fondo sin estirarse, y apoya-cabeza a la altura de la parte superior de la cabeza. Una mala posición reduce el control y aumenta lesiones en accidentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 865,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué tipo de sistema de retención infantil (SRI) debe usar un bebé menor de 1 año?',
    opciones: ['Alzador o booster', 'Silla mirando hacia adelante', 'Silla nido mirando hacia atrás (en sentido contrario a la marcha)', 'Puede ir en brazos de un adulto'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los bebés menores de 1 año (o menores de 9 kg) deben usar una silla nido instalada mirando hacia atrás, en sentido contrario a la marcha. Esta posición protege mejor la cabeza y el cuello del bebé en caso de impacto frontal, ya que distribuye las fuerzas sobre toda la espalda. Debe instalarse siempre en el asiento trasero del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 866,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué distancia mínima debe mantener el conductor respecto al volante si el vehículo tiene airbag?',
    opciones: ['No importa la distancia', 'Al menos 10 cm', 'Al menos 25 cm', 'Al menos 50 cm'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El conductor debe mantener al menos 25 centímetros de distancia entre su pecho y el centro del volante cuando el vehículo tiene airbag. El airbag se despliega a gran velocidad (hasta 300 km/h) y si el conductor está demasiado cerca, puede sufrir lesiones graves por el propio airbag, especialmente en la cara, cuello y tórax.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 867,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es la seguridad activa del vehículo?',
    opciones: ['Los elementos que protegen durante un accidente', 'Los sistemas que ayudan a evitar que ocurra un accidente', 'Los elementos de primeros auxilios', 'La alarma del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La seguridad activa comprende todos los sistemas del vehículo diseñados para evitar que ocurra un accidente. Incluye frenos (ABS, EBD), dirección asistida, suspensión, neumáticos en buen estado, iluminación, sistema de control de estabilidad (ESP) y tracción. Estos sistemas actúan antes del accidente, a diferencia de la seguridad pasiva que actúa durante y después.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 868,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es la seguridad pasiva del vehículo?',
    opciones: ['Los sistemas que evitan accidentes', 'Los elementos diseñados para reducir las lesiones durante un accidente', 'Las señales de tránsito', 'La revisión técnica del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La seguridad pasiva comprende los elementos diseñados para reducir las consecuencias y lesiones una vez que el accidente ya se ha producido. Incluye cinturones de seguridad, airbags, apoya-cabezas, zonas de deformación programada de la carrocería, barras laterales de protección y sistemas de retención infantil. Actúan durante y después del impacto.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 869,
    categoria: 'Conducción Segura',
    pregunta: '¿Hasta qué edad deben los niños usar un sistema de retención infantil en el vehículo?',
    opciones: ['Hasta los 4 años', 'Hasta los 6 años', 'Hasta los 9 años o hasta que midan 135 cm', 'Hasta los 12 años'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Según la legislación chilena, los niños deben usar un sistema de retención infantil (SRI) adecuado a su edad, peso y talla hasta los 9 años o hasta que alcancen los 135 cm de estatura. Existen tres tipos: silla nido (hasta 1 año), silla convertible (1-4 años) y alzador o booster (4-9 años o 135 cm). Siempre deben ir en el asiento trasero.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 870,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué función cumplen las zonas de deformación programada de un vehículo?',
    opciones: ['Hacen que el vehículo sea más liviano', 'Absorben la energía del impacto para proteger a los ocupantes', 'Reducen el costo de reparación', 'Mejoran la aerodinámica del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las zonas de deformación programada están diseñadas para deformarse de manera controlada durante un impacto, absorbiendo la mayor cantidad de energía posible antes de que llegue al habitáculo donde van los ocupantes. La parte delantera y trasera del vehículo se deforman para que la cabina de pasajeros mantenga su integridad estructural.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 871,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué una mujer embarazada debe usar el cinturón de seguridad?',
    opciones: ['No debe usarlo para proteger al bebé', 'Debe usarlo siempre, con la banda inferior bajo el vientre', 'Solo debe usarlo en carretera', 'Puede usarlo sobre el vientre sin problema'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las mujeres embarazadas deben usar siempre el cinturón de seguridad. La banda inferior debe colocarse por debajo del vientre, sobre las caderas, y la banda diagonal entre los senos y al costado del vientre. No usar cinturón es más peligroso tanto para la madre como para el bebé, ya que en un accidente sin cinturón ambos corren riesgo vital.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 872,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué sistema evita que las ruedas derrapen lateralmente en curvas?',
    opciones: ['El sistema ABS', 'El control electrónico de estabilidad (ESP/ESC)', 'La dirección asistida', 'El control de crucero'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El control electrónico de estabilidad (ESP o ESC) detecta cuando el vehículo comienza a derrapar y aplica frenos selectivamente a ruedas individuales para corregir la trayectoria. Es especialmente útil en curvas, maniobras de evasión y pavimento resbaladizo. Reduce significativamente el riesgo de vuelcos y pérdida de control. No sustituye una conducción prudente.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 873,
    categoria: 'Conducción Segura',
    pregunta: '¿Dónde es más seguro instalar la silla de retención infantil en el vehículo?',
    opciones: ['En el asiento del copiloto', 'En el asiento trasero central', 'En cualquier asiento trasero lateral', 'No importa la ubicación'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La posición más segura para la silla de retención infantil es el asiento trasero central, ya que es el punto más alejado de cualquier impacto lateral y frontal. Si no es posible instalarlo correctamente en el centro (por falta de anclaje), se recomienda el asiento trasero del lado derecho. Nunca debe instalarse en el asiento delantero si el vehículo tiene airbag activo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 874,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer antes de poner el vehículo en marcha?',
    opciones: ['Solo ajustar el espejo retrovisor', 'Ajustar asiento, espejos, cinturón, y verificar que todos los pasajeros usen cinturón', 'Solo encender las luces', 'Calentar el motor durante 10 minutos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de conducir debe ajustar el asiento para alcanzar cómodamente los pedales y el volante, regular los espejos retrovisores (interior y exteriores), colocarse el cinturón de seguridad, verificar que todos los pasajeros usen cinturón o SRI, y revisar que las puertas estén bien cerradas. Esta rutina es fundamental para una conducción segura.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 875,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el principal peligro de llevar objetos sueltos en el habitáculo del vehículo?',
    opciones: ['Producen ruido molesto', 'Se convierten en proyectiles peligrosos durante un frenado brusco o colisión', 'Pueden obstruir los pedales', 'No representan ningún peligro'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los objetos sueltos en el habitáculo se convierten en proyectiles peligrosos durante un frenado brusco o colisión. Un objeto de 1 kg a 50 km/h impacta con una fuerza equivalente a 30 kg. Una botella de agua, un celular o una tablet pueden causar lesiones graves. Todos los objetos deben guardarse en la guantera, cajuelas o fijarse adecuadamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 876,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué tipo de airbag protege en colisiones laterales?',
    opciones: ['El airbag frontal del conductor', 'El airbag lateral o de cortina', 'El airbag de rodilla', 'No existen airbags para impactos laterales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los airbags laterales y de cortina están diseñados para proteger a los ocupantes en colisiones laterales. Los airbags laterales se despliegan desde el asiento o la puerta para proteger el torso, mientras que los airbags de cortina se despliegan desde el techo para proteger la cabeza. Los impactos laterales son especialmente peligrosos por la menor distancia de deformación.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 877,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo deben regularse los espejos retrovisores exteriores?',
    opciones: ['Para ver el costado del propio vehículo completo', 'Para minimizar los puntos ciegos, viendo apenas el costado del vehículo', 'Para ver directamente hacia atrás', 'No necesitan ajustarse si el espejo interior funciona'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los espejos exteriores deben regularse para minimizar los puntos ciegos. Se debe ver apenas el costado del propio vehículo como referencia, y el resto del espejo debe mostrar la vía y los vehículos que se aproximan. Aun así, siempre existen puntos ciegos, por lo que antes de cambiar de pista se debe girar brevemente la cabeza para verificar.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 878,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuándo es especialmente peligroso NO usar cinturón de seguridad?',
    opciones: ['Solo en carretera', 'Solo a alta velocidad', 'Siempre es peligroso, incluso a baja velocidad y en trayectos cortos', 'Solo cuando llueve'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No usar cinturón es peligroso siempre, incluso a baja velocidad y en trayectos cortos. La mayoría de los accidentes fatales ocurren a menos de 40 km/h y cerca del hogar. A solo 30 km/h, un impacto sin cinturón equivale a caer desde un segundo piso. Las estadísticas muestran que muchas víctimas mortales en accidentes urbanos no llevaban puesto el cinturón.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 879,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe verificar del cinturón de seguridad periódicamente?',
    opciones: ['Solo que abroche correctamente', 'Que la cinta no esté deshilachada, cortada o deformada y que el mecanismo funcione', 'No necesita verificación', 'Solo verificar después de un accidente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Debe verificarse periódicamente que la cinta del cinturón no esté deshilachada, cortada, retorcida o deformada, que el mecanismo de enrollado funcione correctamente, que la hebilla cierre y abra sin dificultad, y que los anclajes estén firmes. Un cinturón en mal estado puede no cumplir su función protectora. Después de un accidente, todos los cinturones deben ser reemplazados.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 880,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué elemento de seguridad activa es fundamental para una buena visibilidad nocturna?',
    opciones: ['Los airbags', 'Las luces del vehículo en buen estado y correctamente reguladas', 'El cinturón de seguridad', 'El apoya-cabeza'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las luces del vehículo son un elemento de seguridad activa fundamental para la visibilidad nocturna. Deben estar en buen estado, limpias y correctamente reguladas para no encandilar a otros conductores. Incluyen luces bajas, altas, de posición, intermitentes y de freno. Luces desreguladas pueden deslumbrar al tránsito contrario, causando accidentes graves.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },

  // =============================================
  // CONDUCCIÓN PRÁCTICA Y SITUACIONES REALES (25 preguntas) - IDs 881-905
  // =============================================
  {
    id: 881,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué acción nunca se debe realizar en una bomba de bencina (gasolinera)?',
    opciones: ['Apagar el motor', 'Fumar o encender fuego', 'Bajar del vehículo', 'Hablar con el despachador'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Nunca se debe fumar, encender fósforos, encendedores ni ningún tipo de fuego en una bomba de bencina. Los vapores de combustible son altamente inflamables y una chispa puede provocar una explosión o incendio devastador. Tampoco se debe usar el teléfono celular cerca de los surtidores y siempre se debe apagar el motor del vehículo durante la carga.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 882,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el uso correcto del pedal de embrague?',
    opciones: ['Mantener el pie apoyado en el embrague mientras conduce', 'Pisarlo solo al cambiar de marcha o detenerse, sin apoyar el pie sobre él mientras circula', 'Usarlo para frenar suavemente', 'Pisarlo junto con el acelerador para mayor potencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El embrague debe pisarse solo al cambiar de marcha o al detenerse. No se debe mantener el pie apoyado sobre el pedal mientras circula, práctica conocida como "cabalgar el embrague", ya que provoca desgaste prematuro del disco de embrague y puede causar patinamiento. Al soltar el embrague, el pie debe descansar en el reposapiés.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 883,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué no se debe circular cuesta abajo con el motor desenganchado (en neutro)?',
    opciones: ['Porque se gasta más combustible', 'Porque se pierde el freno de motor y se sobrecargan los frenos', 'Porque el motor se puede apagar', 'Porque es ilegal pero no peligroso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Circular cuesta abajo en neutro elimina el efecto de freno motor, obligando a depender exclusivamente de los frenos de servicio. En descensos prolongados, los frenos se sobrecalientan y pierden eficacia (fading), pudiendo fallar completamente. Además, se pierde la capacidad de acelerar rápidamente ante una emergencia. Siempre descienda en una marcha adecuada.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 884,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el procedimiento correcto al llegar a un cruce de vías férreas sin barreras?',
    opciones: ['Pasar rápidamente para no quedar sobre las vías', 'Detenerse, mirar a ambos lados, escuchar y cruzar solo si no viene tren', 'Reducir velocidad y cruzar sin detenerse', 'Tocar la bocina y cruzar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al llegar a un cruce ferroviario sin barreras debe detenerse completamente antes de las vías, mirar cuidadosamente en ambas direcciones, bajar la ventanilla y escuchar si se aproxima un tren, y cruzar solo cuando tenga certeza de que no viene ninguno. Recuerde que un tren necesita hasta 1.000 metros para detenerse y siempre tiene prioridad absoluta de paso.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 885,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuándo está prohibido realizar un adelantamiento?',
    opciones: ['En rectas largas con buena visibilidad', 'En curvas, puentes, túneles, cruces e intersecciones', 'Solo está prohibido en zonas urbanas', 'Solo cuando hay línea continua'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Está prohibido adelantar en curvas, puentes, túneles, cruces, intersecciones, pasos de peatones, cimas de pendientes, donde hay línea continua, y donde la visibilidad sea insuficiente. También está prohibido adelantar cuando el vehículo que va delante ha señalizado un viraje a la izquierda, o cuando viene un vehículo en sentido contrario.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 886,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se debe realizar correctamente un viraje a la izquierda en una intersección?',
    opciones: ['Girar rápidamente antes que los vehículos que vienen de frente', 'Ubicarse en la pista izquierda, señalizar, ceder el paso al tránsito contrario y girar', 'Girar desde cualquier pista si no hay otros vehículos', 'Detenerse en el centro de la intersección y esperar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para virar a la izquierda: señalice con anticipación, ubíquese en la pista más cercana al eje central de la calzada, reduzca la velocidad, ceda el paso a los vehículos que vienen en sentido contrario y a los peatones que cruzan, y realice el giro cuando sea seguro. Nunca gire desde una pista que no corresponda ni sin verificar que no vienen vehículos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 887,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo deben posicionarse las ruedas al estacionar en una pendiente ascendente con solera?',
    opciones: ['Rectas hacia adelante', 'Giradas hacia la cuneta', 'Giradas hacia la calle (contrario a la solera)', 'No importa la posición'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al estacionar en pendiente ascendente con solera (vereda), las ruedas delanteras deben girarse hacia la calle, es decir, en sentido contrario a la solera. Si el vehículo se desplaza hacia atrás, las ruedas girarán contra la solera y lo detendrán. Además, siempre active el freno de mano y deje una marcha engranada (primera en subida, reversa en bajada).',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 888,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuándo se deben usar las luces altas (largas)?',
    opciones: ['Siempre de noche en carretera', 'De noche en carreteras sin iluminación y cuando no hay vehículos de frente ni adelante', 'En la ciudad para ver mejor', 'Cuando llueve fuerte'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las luces altas deben usarse de noche en carreteras y caminos sin iluminación artificial, pero deben cambiarse a luces bajas cuando se aproxima un vehículo en sentido contrario (a 200 metros) o cuando sigue a otro vehículo de cerca (a 150 metros), para no encandilarlo. En zona urbana con alumbrado público se usan luces bajas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 889,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué la primera lluvia después de un período seco es especialmente peligrosa?',
    opciones: ['Porque el agua está más fría', 'Porque el aceite y la suciedad acumulados en el pavimento se mezclan con el agua, creando una superficie muy resbaladiza', 'Porque los limpiaparabrisas no funcionan bien', 'Porque los conductores no están acostumbrados a la lluvia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La primera lluvia después de un período seco es extremadamente peligrosa porque el agua se mezcla con el aceite, goma, polvo y suciedad acumulados en el pavimento, formando una película resbaladiza. Esta condición reduce drásticamente la adherencia de los neumáticos. Después de llover un tiempo, el agua lava estos residuos y la adherencia mejora gradualmente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 890,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer si su vehículo sufre aquaplaning?',
    opciones: ['Frenar bruscamente para detenerse', 'Soltar el acelerador suavemente, no frenar bruscamente y mantener el volante recto', 'Acelerar para salir de la zona mojada', 'Girar el volante hacia un lado rápidamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En caso de aquaplaning, los neumáticos pierden contacto con el pavimento al "flotar" sobre una capa de agua. Debe soltar el acelerador suavemente sin frenar bruscamente, mantener el volante recto y esperar a que los neumáticos recuperen contacto con el asfalto. Frenar o girar bruscamente puede provocar pérdida total del control. Prevenga reduciendo velocidad en lluvia.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 891,
    categoria: 'Conducción Segura',
    pregunta: 'En una intersección sin señalización ni semáforo, ¿quién tiene prioridad de paso?',
    opciones: ['El vehículo más grande', 'El vehículo que viene por la derecha', 'El que llega primero', 'El que circula más rápido'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En una intersección sin señalización ni semáforo, rige la "regla de la derecha": tiene prioridad el vehículo que se aproxima por la derecha del conductor. Esta es una norma fundamental en la legislación chilena de tránsito. Sin embargo, los peatones que cruzan por el cruce peatonal siempre tienen prioridad sobre todos los vehículos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 892,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precauciones debe tomar al ingresar a un túnel?',
    opciones: ['Acelerar para salir rápido', 'Encender luces bajas, quitarse lentes de sol, mantener distancia y no detenerse', 'Solo encender las luces de emergencia', 'Bajar las ventanillas para mejor ventilación'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al ingresar a un túnel: encienda las luces bajas (obligatorio), quítese los lentes de sol para adaptarse al cambio de luminosidad, mantenga la distancia de seguridad, no se detenga ni cambie de pista, respete los límites de velocidad señalizados. Si hay congestión dentro del túnel, mantenga las ventanillas cerradas para evitar la acumulación de gases.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 893,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer si otro vehículo le adelanta peligrosamente?',
    opciones: ['Acelerar para no dejarse adelantar', 'Facilitar la maniobra reduciendo velocidad y manteniendo su pista', 'Tocar la bocina prolongadamente', 'Encender las luces altas para advertir'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si otro vehículo le adelanta, incluso peligrosamente, debe facilitar la maniobra reduciendo levemente la velocidad y manteniendo su posición en la pista. Nunca intente competir acelerando, ya que esto aumenta el peligro para todos. La conducción defensiva implica evitar conflictos y contribuir a que las maniobras de otros, aunque imprudentes, terminen sin accidentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 894,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuándo es seguro adelantar a otro vehículo?',
    opciones: ['En cualquier momento si tiene un vehículo potente', 'En recta con buena visibilidad, línea discontinua, sin tránsito de frente y distancia suficiente', 'Cuando el vehículo de adelante va lento', 'Solo en autopistas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para adelantar de forma segura se requiere: recta con buena visibilidad, línea de eje discontinua (segmentada), que no vengan vehículos en sentido contrario, distancia suficiente para completar la maniobra sin riesgo, y señalizar la maniobra con anticipación. Siempre adelante por la izquierda y regrese a su pista solo cuando vea al vehículo adelantado en su espejo retrovisor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 895,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer si le encandilan las luces de un vehículo que viene de frente?',
    opciones: ['Encender sus luces altas para que el otro baje las suyas', 'Desviar la mirada hacia el borde derecho de la calzada y reducir velocidad', 'Cerrar los ojos momentáneamente', 'Frenar bruscamente y detenerse'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si le encandilan las luces de un vehículo que viene de frente, desvíe la mirada hacia el borde derecho de la calzada usando la línea blanca como guía, reduzca la velocidad y, si es necesario, deténgase al costado. Nunca mire directamente a las luces ni encienda sus luces altas como represalia, ya que encandilará al otro conductor empeorando la situación.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 896,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué hacer si se revienta un neumático a alta velocidad en una autopista?',
    opciones: ['Frenar a fondo inmediatamente', 'Sujetar el volante firmemente, soltar el acelerador gradualmente y dirigirse a la berma', 'Girar bruscamente hacia la berma', 'Apagar el motor inmediatamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si se revienta un neumático a alta velocidad: sujete firmemente el volante con ambas manos, suelte el acelerador gradualmente sin frenar bruscamente, encienda las luces de emergencia, y diríjase lentamente hacia la berma. Una vez detenido, coloque el triángulo a 50 metros. Frenar o girar bruscamente a alta velocidad puede provocar un vuelco o pérdida total del control.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 897,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe conducir en una zona residencial?',
    opciones: ['A la velocidad máxima permitida de 60 km/h', 'Con precaución, a baja velocidad, atento a niños y peatones', 'Igual que en una avenida principal', 'Rápido para no molestar a los residentes'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zonas residenciales debe conducir con especial precaución y a baja velocidad, ya que es común la presencia de niños jugando, peatones cruzando, mascotas, ciclistas y vehículos saliendo de estacionamientos. La velocidad máxima es de 30 km/h en calles residenciales según las señales. Debe estar preparado para detenerse en cualquier momento.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 898,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer antes de abrir la puerta del vehículo para bajarse?',
    opciones: ['Abrir rápidamente para no detener el tráfico', 'Verificar por el espejo y mirando hacia atrás que no vengan vehículos ni ciclistas', 'Solo mirar por el espejo retrovisor', 'No es necesario verificar si está estacionado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de abrir la puerta, siempre debe verificar por los espejos retrovisores y girando la cabeza que no se aproximen vehículos, motocicletas ni ciclistas. Abrir la puerta sin mirar puede causar un accidente grave, especialmente con ciclistas que circulan cerca de los vehículos estacionados. Se recomienda usar la "maniobra holandesa": abrir con la mano contraria para girar el cuerpo naturalmente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 899,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precaución especial debe tener al conducir cerca de un bus escolar detenido?',
    opciones: ['Adelantarlo rápidamente por el lado izquierdo', 'Reducir la velocidad drásticamente y estar atento a niños que puedan cruzar', 'Tocar la bocina para alertar a los niños', 'No es necesario tomar precauciones especiales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al acercarse a un bus escolar detenido, debe reducir la velocidad drásticamente y estar extremadamente atento, ya que los niños pueden cruzar la calzada repentinamente al bajar del bus. Los niños son impredecibles y pueden aparecer por delante o detrás del bus sin mirar. En algunos casos, la normativa prohíbe adelantar al bus escolar mientras descienden pasajeros.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 900,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la mejor técnica para tomar una curva de manera segura?',
    opciones: ['Frenar dentro de la curva si va muy rápido', 'Reducir la velocidad antes de la curva, no frenar en ella, y acelerar suavemente al salir', 'Mantener la misma velocidad durante toda la curva', 'Acelerar al entrar para tener más estabilidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La técnica correcta es: reducir la velocidad ANTES de entrar a la curva, mantener una velocidad constante y adecuada durante la curva sin frenar bruscamente, y acelerar suavemente al salir de ella. Frenar dentro de una curva puede provocar pérdida de adherencia y derrape, especialmente en pavimento mojado. La velocidad de entrada debe ser la adecuada.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 901,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué hacer si circulando por la carretera se encuentra con niebla densa repentinamente?',
    opciones: ['Detenerse inmediatamente en la pista', 'Encender luces bajas y neblineros, reducir velocidad y aumentar distancia de seguimiento', 'Encender luces altas para ver mejor', 'Seguir al vehículo de adelante de cerca usando sus luces como guía'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En caso de niebla densa: encienda luces bajas y neblineros (NUNCA luces altas, ya que la luz se refleja en la niebla y empeora la visibilidad), reduzca considerablemente la velocidad, aumente la distancia de seguimiento, use las líneas del pavimento como guía. Si la niebla es muy densa, considere detenerse fuera de la calzada hasta que mejore la visibilidad.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 902,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer si su vehículo comienza a derrapar en una curva?',
    opciones: ['Frenar bruscamente para detenerse', 'Soltar el acelerador y girar suavemente el volante en la dirección del derrape', 'Acelerar fuertemente para recuperar tracción', 'Apagar el motor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si el vehículo derrapa, suelte el acelerador sin frenar bruscamente y gire suavemente el volante en la dirección hacia donde se desliza la parte trasera del vehículo (contravolante). Esto ayuda a recuperar la adherencia y el control. Una vez recuperado el control, enderece progresivamente el volante. Frenar bruscamente durante un derrape solo empeora la situación.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 903,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la forma correcta de incorporarse a una autopista desde una pista de aceleración?',
    opciones: ['Detenerse al final de la pista y esperar un espacio', 'Acelerar en la pista de aceleración para igualar la velocidad del tráfico y incorporarse cediendo el paso', 'Entrar directamente sin mirar', 'Incorporarse a baja velocidad para ser más seguro'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para incorporarse a una autopista correctamente: use la pista de aceleración para alcanzar una velocidad similar a la del flujo de tráfico, señalice su intención, verifique por los espejos y el punto ciego, y busque un espacio adecuado para incorporarse cediendo el paso a los vehículos que ya circulan. Incorporarse a baja velocidad es muy peligroso por la diferencia de velocidades.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 904,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es peligroso conducir muy cerca del vehículo de adelante?',
    opciones: ['Solo porque es una infracción de tránsito', 'Porque no tendrá tiempo ni espacio suficiente para frenar si el otro se detiene repentinamente', 'Solo porque reduce la visibilidad', 'No es peligroso si el otro conductor es prudente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Conducir demasiado cerca del vehículo de adelante es peligroso porque no tendrá suficiente tiempo ni distancia para frenar si el otro se detiene repentinamente. Además, reduce su campo de visión del camino adelante, impidiendo anticiparse a peligros. Una colisión trasera puede causar el efecto "latigazo cervical" y, en cadena, involucrar a múltiples vehículos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 905,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer si se queda sin frenos mientras conduce?',
    opciones: ['Apagar el motor inmediatamente', 'Bombear el pedal de freno, usar el freno de mano gradualmente y bajar marchas para frenar con el motor', 'Chocar contra algo suave para detenerse', 'Saltar del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si falla el sistema de frenos: bombee rápidamente el pedal de freno para intentar generar presión hidráulica, baje marchas progresivamente para usar el freno motor, aplique el freno de mano gradualmente (no de golpe para evitar bloqueo de ruedas), busque una zona segura para detenerse como una pendiente ascendente o terreno blando. Encienda luces de emergencia y use la bocina para alertar.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
];
