import type { Question } from './questionsData';

const allTypes = ['clase_b', 'clase_a2', 'clase_a4', 'clase_c', 'clase_d', 'clase_e'];

export const questionsPart7: Question[] = [
  // =============================================
  // SEÑALES DE TRÁNSITO - DETALLE EXHAUSTIVO (30 preguntas) - IDs 906-935
  // =============================================
  {
    id: 906,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué significa la señal PARE de forma octogonal y color rojo?',
    opciones: ['Reducir la velocidad y continuar', 'Detenerse completamente antes de la línea de detención', 'Ceder el paso solo si hay vehículos', 'Precaución por zona peligrosa'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal PARE octogonal roja es una señal reglamentaria que obliga al conductor a detenerse completamente antes de la línea de detención. Debe verificar que la vía esté despejada antes de continuar. No basta con reducir velocidad; la detención debe ser total. No respetar esta señal constituye una infracción gravísima según la Ley de Tránsito chilena.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 907,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué forma y color tiene la señal CEDA EL PASO?',
    opciones: ['Circular roja', 'Octogonal roja', 'Triangular invertida con borde rojo y fondo blanco', 'Cuadrada azul'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La señal CEDA EL PASO tiene forma de triángulo invertido (con la punta hacia abajo), borde rojo y fondo blanco. Indica que el conductor debe ceder el paso a los vehículos que circulan por la vía preferente. Si no hay tráfico, puede continuar sin detenerse, a diferencia de la señal PARE que exige detención total.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 908,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica la señal de NO ESTACIONAR (círculo rojo con la letra E tachada)?',
    opciones: ['Prohibido detenerse momentáneamente', 'Prohibido estacionar en esa zona', 'Estacionamiento exclusivo para residentes', 'Estacionamiento permitido solo de noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de NO ESTACIONAR muestra un círculo con borde rojo y una letra E cruzada por una diagonal. Prohíbe estacionar el vehículo en la zona señalizada, pero permite detenerse brevemente para subir o bajar pasajeros o carga. La prohibición rige desde la señal hasta la próxima intersección o hasta una señal que la anule.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 909,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica la señal de NO VIRAR A LA IZQUIERDA?',
    opciones: ['Prohibido girar a la izquierda en esa intersección', 'Obligación de girar a la derecha', 'Prohibido adelantar por la izquierda', 'Curva peligrosa a la izquierda'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal de NO VIRAR A LA IZQUIERDA es una señal reglamentaria circular con borde rojo que muestra una flecha hacia la izquierda cruzada por una diagonal roja. Prohíbe girar a la izquierda en esa intersección específica. El conductor debe buscar una ruta alternativa. No respetar esta señal constituye una infracción grave.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 910,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica la señal de NO VIRAR A LA DERECHA?',
    opciones: ['Curva peligrosa a la derecha', 'Obligación de girar a la izquierda', 'Prohibido girar a la derecha en esa intersección', 'Prohibido adelantar por la derecha'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La señal de NO VIRAR A LA DERECHA es circular con borde rojo y muestra una flecha hacia la derecha cruzada por una diagonal roja. Prohíbe girar a la derecha en la intersección donde está ubicada. El conductor debe continuar recto o buscar otra ruta. Su incumplimiento puede provocar accidentes y constituye una infracción grave.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 911,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué prohíbe la señal de NO VIRAR EN U?',
    opciones: ['Prohibido retroceder', 'Prohibido realizar un giro de 180 grados (viraje en U)', 'Prohibido detenerse', 'Prohibido cambiar de pista'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de NO VIRAR EN U prohíbe realizar un giro de 180 grados para cambiar de sentido de circulación en ese punto. Es una señal circular con borde rojo y una flecha en U cruzada por una diagonal. El viraje en U está prohibido también en curvas, pendientes, túneles y donde la visibilidad sea reducida.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 912,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica una señal circular con borde rojo y un número en su interior (por ejemplo, 60)?',
    opciones: ['Velocidad mínima permitida', 'Velocidad máxima permitida en esa zona', 'Distancia al próximo punto de control', 'Número de la ruta'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de VELOCIDAD MÁXIMA es circular con borde rojo, fondo blanco y un número en su interior que indica la velocidad máxima permitida en km/h para ese tramo. Superar dicha velocidad constituye una infracción que puede ser grave o gravísima según la magnitud del exceso. La señal rige hasta que otra la modifique.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 913,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica la señal de FIN DE PROHIBICIÓN DE ADELANTAR?',
    opciones: ['Inicio de zona de no adelantar', 'Que se puede volver a adelantar a partir de ese punto', 'Prohibido adelantar a vehículos pesados', 'Fin de zona de velocidad reducida'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de FIN DE PROHIBICIÓN DE ADELANTAR es circular con fondo blanco y líneas diagonales grises, e indica que a partir de ese punto se puede volver a adelantar, siempre que las condiciones de la vía y la demarcación lo permitan. El conductor debe verificar que sea seguro antes de iniciar cualquier maniobra de adelantamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 914,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica una señal con una flecha blanca sobre un círculo azul?',
    opciones: ['Dirección de salida de emergencia', 'Sentido obligatorio de circulación', 'Zona de estacionamiento', 'Ruta turística recomendada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de SENTIDO OBLIGATORIO muestra una flecha blanca sobre fondo azul circular. Indica la dirección obligatoria que deben seguir los vehículos. Puede señalar adelante, derecha, izquierda o combinaciones. Es una señal reglamentaria de obligación. No seguir la dirección indicada constituye una infracción grave según la normativa chilena.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 915,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica la señal circular azul con tres flechas formando un círculo?',
    opciones: ['Cruce de varias vías', 'Rotonda: circulación obligatoria en un solo sentido', 'Zona de tránsito libre', 'Intersección con semáforo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de ROTONDA muestra tres flechas curvadas en sentido antihorario sobre fondo azul circular. Indica que se debe circular obligatoriamente en el sentido indicado dentro de la rotonda. En Chile, la circulación es siempre en sentido contrario a las agujas del reloj. Los vehículos dentro de la rotonda tienen preferencia de paso.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 916,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué indica una señal triangular amarilla con un peatón dibujado?',
    opciones: ['Prohibido el paso de peatones', 'Paso de peatones obligatorio', 'Advertencia de proximidad de un cruce peatonal', 'Zona exclusiva para peatones'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La señal preventiva de PASO DE PEATONES es triangular con fondo amarillo y borde negro, mostrando la silueta de un peatón. Advierte al conductor que se aproxima a un cruce peatonal y debe reducir la velocidad y estar preparado para detenerse. Los peatones tienen prioridad absoluta en los cruces demarcados.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 917,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué indica la señal de ZONA ESCOLAR?',
    opciones: ['Prohibido el ingreso de vehículos', 'Advertencia de proximidad de un establecimiento educacional', 'Estacionamiento reservado para profesores', 'Velocidad mínima de 30 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de ZONA ESCOLAR advierte al conductor que se aproxima a un sector donde hay establecimientos educacionales. Debe reducir la velocidad a un máximo de 30 km/h cuando la señalización está activa, generalmente en horarios de entrada y salida de clases. Debe extremar la precaución por la presencia de niños.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 918,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué indica la señal preventiva de CURVA PELIGROSA?',
    opciones: ['Prohibido girar en esa dirección', 'Advertencia de una curva pronunciada donde se debe reducir la velocidad', 'Desvío obligatorio', 'Cambio de sentido de circulación'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de CURVA PELIGROSA es triangular amarilla con una flecha curvada que advierte sobre una curva pronunciada adelante. El conductor debe reducir la velocidad antes de ingresar a la curva, no durante la misma. Es importante no frenar bruscamente dentro de la curva ya que puede provocar pérdida de control del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 919,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué advierte la señal de CAMINO RESBALADIZO?',
    opciones: ['Que el pavimento está en mal estado', 'Que el camino puede ponerse resbaladizo por lluvia, hielo o gravilla', 'Que hay obras en la vía', 'Que el camino es de tierra'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de CAMINO RESBALADIZO muestra un vehículo derrapando sobre fondo amarillo triangular. Advierte que el pavimento puede volverse resbaladizo en condiciones de lluvia, hielo, escarcha o presencia de gravilla suelta. El conductor debe reducir la velocidad, evitar maniobras bruscas y aumentar la distancia de seguimiento con el vehículo delantero.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 920,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué indica la Cruz de San Andrés en un cruce de ferrocarril?',
    opciones: ['Que el tren tiene preferencia absoluta y se debe detener', 'Que el cruce está fuera de servicio', 'Que hay un paso a nivel con barreras automáticas', 'Que se puede cruzar sin detenerse'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La Cruz de San Andrés es una señal en forma de X ubicada en los cruces de ferrocarril. Indica que el tren tiene preferencia absoluta de paso. El conductor debe detenerse completamente, mirar a ambos lados y asegurarse de que no venga ningún tren antes de cruzar. Nunca se debe intentar ganarle al tren.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 921,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué advierte la señal de ANIMALES EN LA VÍA?',
    opciones: ['Zona de caza permitida', 'Posible presencia de animales cruzando la calzada', 'Zona de ganadería prohibida', 'Prohibido transportar animales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de ANIMALES EN LA VÍA es triangular amarilla con la silueta de un animal (generalmente una vaca). Advierte que pueden haber animales cruzando la calzada en esa zona. El conductor debe reducir la velocidad y estar atento, especialmente en horarios de amanecer y atardecer cuando los animales se desplazan con mayor frecuencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 922,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué indica la señal de PENDIENTE PELIGROSA (bajada)?',
    opciones: ['Camino en mal estado', 'Advertencia de bajada pronunciada donde se debe usar freno motor', 'Zona de velocidad libre', 'Prohibido el paso de vehículos pesados'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de PENDIENTE PELIGROSA de bajada advierte sobre un descenso pronunciado. El conductor debe usar el freno motor (marchas bajas) para controlar la velocidad y no depender exclusivamente de los frenos de servicio, ya que el uso prolongado puede recalentarlos y hacerlos perder eficacia. Se recomienda reducir la velocidad antes de iniciar el descenso.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 923,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué advierte la señal de ESTRECHAMIENTO DE CALZADA?',
    opciones: ['Que la vía se angosta más adelante', 'Que hay un puente angosto', 'Que se prohíbe adelantar', 'Que la vía tiene doble sentido'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal de ESTRECHAMIENTO DE CALZADA es triangular amarilla y muestra que la vía se angosta más adelante, ya sea por uno o ambos lados. El conductor debe reducir la velocidad y estar preparado para ceder el paso. Si el estrechamiento es por un lado, tiene preferencia el vehículo que circula por el lado no afectado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 924,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una línea continua amarilla pintada al centro de la calzada?',
    opciones: ['Separación de pistas en el mismo sentido', 'Separación de sentidos de circulación opuestos, prohibido cruzar', 'Borde de la calzada', 'Zona de estacionamiento'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La línea continua amarilla al centro de la calzada separa los sentidos de circulación opuestos y prohíbe cruzarla para adelantar o cambiar de sentido. Las líneas amarillas siempre indican separación de flujos opuestos, mientras que las líneas blancas separan pistas del mismo sentido o marcan el borde de la calzada.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 925,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una línea continua blanca en el borde de la calzada?',
    opciones: ['Separación de sentidos opuestos', 'Límite del borde de la calzada que no se debe cruzar', 'Zona de adelantamiento permitido', 'Pista exclusiva para buses'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La línea continua blanca en el borde de la calzada delimita el límite de la vía transitable. No debe ser cruzada excepto en caso de emergencia o para ingresar/salir de la vía. Las líneas blancas también se usan para separar pistas del mismo sentido y para demarcaciones como pasos de cebra y líneas de detención.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 926,
    categoria: 'Señalización',
    pregunta: '¿Qué permite hacer una línea discontinua (segmentada) en la calzada?',
    opciones: ['Indica que está prohibido adelantar', 'Permite adelantar o cambiar de pista cuando sea seguro', 'Indica zona de estacionamiento', 'Marca una zona de velocidad reducida'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La línea discontinua o segmentada permite adelantar o cambiar de pista cuando las condiciones de tránsito y visibilidad lo permitan de manera segura. Antes de cruzarla, el conductor debe verificar que no venga ningún vehículo en sentido contrario y que tenga espacio suficiente para completar la maniobra sin peligro.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 927,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una doble línea continua amarilla en el centro de la calzada?',
    opciones: ['Permitido adelantar con precaución', 'Prohibido cruzar desde cualquier sentido de circulación', 'Zona de estacionamiento bilateral', 'Cambio de velocidad máxima'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La doble línea continua amarilla prohíbe cruzarla desde ambos sentidos de circulación. Ningún vehículo puede adelantar ni cambiar de sentido en ese tramo. Esta demarcación se utiliza en zonas de visibilidad reducida, curvas, pendientes y cercanías de intersecciones donde adelantar sería extremadamente peligroso.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 928,
    categoria: 'Señalización',
    pregunta: '¿Cuándo se puede adelantar si hay una línea segmentada junto a una línea continua?',
    opciones: ['Pueden adelantar los de ambos sentidos', 'Solo pueden adelantar los que tienen la línea segmentada a su lado', 'Nadie puede adelantar', 'Solo vehículos de emergencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Cuando una línea segmentada va junto a una línea continua, solo pueden adelantar los vehículos que tienen la línea segmentada (discontinua) de su lado. Los que tienen la línea continua de su lado no pueden cruzar. Esta configuración se usa cuando las condiciones de visibilidad son favorables solo desde uno de los sentidos de circulación.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 929,
    categoria: 'Señalización',
    pregunta: '¿Qué indican las flechas pintadas en el pavimento?',
    opciones: ['Zona de estacionamiento', 'La dirección obligatoria que deben seguir los vehículos en esa pista', 'Velocidad recomendada', 'Proximidad de un paso de cebra'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las flechas en el pavimento indican la dirección o direcciones obligatorias que deben seguir los vehículos que circulan por esa pista. Pueden indicar avance recto, giro a la derecha, giro a la izquierda o combinaciones. El conductor debe ubicarse con anticipación en la pista correspondiente a la maniobra que va a realizar.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 930,
    categoria: 'Señalización',
    pregunta: '¿Qué derechos tiene el peatón en un paso de cebra?',
    opciones: ['Debe esperar que no haya vehículos para cruzar', 'Tiene prioridad absoluta y los vehículos deben detenerse', 'Solo tiene prioridad con semáforo en verde', 'Debe cruzar corriendo para no detener el tránsito'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En un paso de cebra (cruce peatonal demarcado con líneas blancas paralelas), el peatón tiene prioridad absoluta. Todo conductor debe detenerse completamente cuando un peatón está cruzando o manifiesta intención de cruzar. No se debe avanzar hasta que el peatón haya completado el cruce de manera segura en toda la calzada.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 931,
    categoria: 'Señalización',
    pregunta: '¿Cómo se identifica la demarcación de una ciclovía en el pavimento?',
    opciones: ['Línea roja continua', 'Franja de color verde o rojo con el símbolo de una bicicleta', 'Línea blanca punteada', 'No tiene demarcación específica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La ciclovía se demarca generalmente con una franja de color diferenciado (verde o rojo) en el pavimento y el símbolo de una bicicleta pintado. Está destinada exclusivamente para la circulación de bicicletas. Los vehículos motorizados no deben circular, estacionar ni detenerse sobre la ciclovía bajo ninguna circunstancia.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 932,
    categoria: 'Señales Reglamentarias',
    pregunta: '¿Qué indica la señal de NO ADELANTAR?',
    opciones: ['Reducir velocidad', 'Prohibido sobrepasar al vehículo que va adelante en ese tramo', 'Mantener distancia de seguimiento', 'Prohibido circular por la pista izquierda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de NO ADELANTAR prohíbe sobrepasar al vehículo que circula adelante en ese tramo de la vía. Es circular con borde rojo y muestra dos vehículos, uno rojo y uno negro. Esta prohibición se aplica en zonas de visibilidad reducida, curvas cerradas y pendientes. La prohibición rige hasta la señal de fin de prohibición de adelantar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 933,
    categoria: 'Señales Preventivas',
    pregunta: '¿Qué indica la señal preventiva de PENDIENTE PELIGROSA de subida?',
    opciones: ['Zona de descanso para vehículos', 'Advertencia de subida pronunciada, posible pérdida de potencia', 'Prohibido el paso de bicicletas', 'Velocidad mínima obligatoria'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal de PENDIENTE PELIGROSA de subida advierte sobre un ascenso pronunciado. Los vehículos pueden perder potencia y velocidad, especialmente los más pesados. El conductor debe usar marchas bajas para mantener la fuerza del motor. En subidas con doble sentido, debe tener precaución con vehículos lentos que circulan en el mismo sentido.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 934,
    categoria: 'Señalización',
    pregunta: '¿Qué indica una señal cuadrada azul con la letra P blanca?',
    opciones: ['Prohibido estacionar', 'Estacionamiento permitido en esa zona', 'Parada de buses', 'Puesto de primeros auxilios'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal cuadrada azul con la letra P blanca es una señal informativa que indica que en esa zona está permitido estacionar. Puede incluir información adicional como horarios, duración máxima o tipo de vehículos permitidos. Es la señal opuesta a la de No Estacionar y ayuda al conductor a encontrar lugares habilitados.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 935,
    categoria: 'Señalización',
    pregunta: '¿Qué significan las líneas en zigzag amarillas pintadas en el pavimento junto a una acera?',
    opciones: ['Zona de estacionamiento exclusivo', 'Prohibido estacionar y detenerse, zona de visibilidad para peatones', 'Zona de carga y descarga', 'Pista de aceleración'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las líneas en zigzag amarillas junto a la acera indican prohibición de estacionar y detenerse. Se ubican generalmente cerca de cruces peatonales y paradas de buses para mantener la visibilidad y seguridad de los peatones. Estacionar sobre estas marcas obstruye la visión del peatón y de los conductores, aumentando el riesgo de atropello.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },

  // =============================================
  // VELOCIDADES Y NORMATIVA ESPECÍFICA (20 preguntas) - IDs 936-955
  // =============================================
  {
    id: 936,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida en zonas urbanas según la ley chilena?',
    opciones: ['40 km/h', '50 km/h', '60 km/h', '70 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La velocidad máxima en zonas urbanas es de 50 km/h, según la modificación a la Ley de Tránsito. Esta velocidad se aplica salvo que la señalización indique un límite diferente. En zonas escolares y residenciales puede ser menor (30 km/h). El conductor debe adaptar la velocidad a las condiciones del tránsito y la vía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 937,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima para automóviles en zonas rurales (caminos no urbanos)?',
    opciones: ['80 km/h', '90 km/h', '100 km/h', '120 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad máxima para automóviles en zonas rurales es de 100 km/h, salvo que la señalización indique un límite diferente. Los vehículos pesados tienen límites inferiores. El conductor debe reducir la velocidad en caminos no pavimentados, con curvas, pendientes o condiciones climáticas adversas para mantener el control del vehículo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 938,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida en autopistas para vehículos livianos?',
    opciones: ['100 km/h', '110 km/h', '120 km/h', '140 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad máxima en autopistas para vehículos livianos es de 120 km/h según la legislación chilena vigente. Esta velocidad puede ser menor si la señalización lo indica. Los vehículos pesados y buses tienen límites inferiores. Circular por sobre este límite constituye una infracción que se agrava proporcionalmente al exceso de velocidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 939,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima en una zona escolar cuando la señalización está activa?',
    opciones: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zonas escolares con señalización activa, la velocidad máxima es de 30 km/h. Esta restricción se aplica generalmente durante los horarios de entrada y salida de clases. Exceder este límite en zona escolar constituye una infracción gravísima, ya que pone en riesgo la vida de los niños que transitan por el sector.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 940,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima en las cercanías de un hospital?',
    opciones: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En las cercanías de hospitales y centros de salud señalizados, la velocidad máxima es de 30 km/h. Esta restricción protege a pacientes, personal médico y visitantes que pueden cruzar la vía. Además, el uso de bocina está prohibido en estas zonas para no afectar a los pacientes hospitalizados.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 941,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad mínima permitida en autopistas?',
    opciones: ['40 km/h', '50 km/h', '60 km/h', '80 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad mínima en autopistas es de 60 km/h. Circular a velocidades inferiores obstaculiza el flujo vehicular y puede provocar accidentes por alcance. Los vehículos que no pueden mantener esta velocidad mínima no deben ingresar a la autopista. Los vehículos lentos deben circular por la pista derecha.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 942,
    categoria: 'Ley de Tránsito',
    pregunta: '¿A qué distancia mínima de una esquina se debe estacionar un vehículo?',
    opciones: ['5 metros', '8 metros', '10 metros', '15 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se debe estacionar a una distancia mínima de 10 metros de una esquina. Esta distancia garantiza la visibilidad tanto de peatones como de conductores en las intersecciones. Estacionar a menor distancia dificulta los giros y obstruye la visión, constituyendo una infracción sancionable con multa y posible retiro del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 943,
    categoria: 'Ley de Tránsito',
    pregunta: '¿A qué distancia mínima de un grifo (hidrante) se debe estacionar?',
    opciones: ['3 metros', '5 metros', '10 metros', '15 metros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se debe estacionar a una distancia mínima de 5 metros de un grifo (hidrante) de incendio. Esta distancia permite el acceso rápido de los bomberos en caso de emergencia. Obstruir un grifo puede retrasar la respuesta ante un incendio con consecuencias fatales. Estacionar frente a un grifo es una infracción sancionable.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 944,
    categoria: 'Ley de Tránsito',
    pregunta: '¿A qué distancia mínima de un paradero de buses se debe estacionar?',
    opciones: ['5 metros', '8 metros', '10 metros', '15 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se debe mantener una distancia mínima de 10 metros de un paradero de buses al estacionar. Esta norma permite que los buses puedan detenerse y que los pasajeros desciendan de forma segura. Estacionar en un paradero obstaculiza el transporte público y pone en riesgo a los pasajeros que deben bajar a la calzada.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 945,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuáles son los documentos obligatorios que debe portar un conductor al manejar?',
    opciones: ['Solo licencia de conducir', 'Licencia y cédula de identidad', 'Licencia, permiso de circulación, SOAP y revisión técnica vigentes', 'Solo permiso de circulación y SOAP'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Todo conductor debe portar obligatoriamente: licencia de conducir vigente, cédula de identidad, permiso de circulación al día, certificado de SOAP (Seguro Obligatorio de Accidentes Personales) vigente y certificado de revisión técnica al día. La ausencia de cualquiera de estos documentos puede significar multas e incluso la retención del vehículo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 946,
    categoria: 'Ley de Tránsito',
    pregunta: '¿A partir de qué nivel de alcohol en la sangre se considera estado de ebriedad en Chile?',
    opciones: ['0.3 g/L', '0.5 g/L', '0.8 g/L', '1.0 g/L'],
    respuestaCorrecta: 2,
    explicacionTexto: 'A partir de 0.8 g/L de alcohol en la sangre se configura el delito de conducción en estado de ebriedad. Entre 0.3 y 0.8 g/L se considera conducción bajo la influencia del alcohol, con sanciones administrativas. Sobre 0.8 g/L las sanciones son penales e incluyen multas, suspensión de licencia y posible presidio según la Ley Emilia.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 947,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué establece la ley de tolerancia cero de alcohol para conductores profesionales?',
    opciones: ['Pueden tener hasta 0.3 g/L', 'No se les aplica ninguna restricción especial', 'No pueden tener ningún nivel de alcohol en la sangre (0.0 g/L)', 'Tienen un límite de 0.1 g/L'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los conductores profesionales (buses, camiones, taxis, transporte escolar) tienen tolerancia cero de alcohol, es decir, no pueden tener absolutamente ningún nivel de alcohol en la sangre (0.0 g/L). Cualquier nivel detectable constituye infracción. Esta norma más estricta se justifica por la responsabilidad que implica transportar pasajeros o carga pesada.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 948,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué tipo de infracción es no usar el cinturón de seguridad?',
    opciones: ['Infracción leve', 'Infracción menos grave', 'Infracción grave', 'Infracción gravísima'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No usar el cinturón de seguridad constituye una infracción grave según la Ley de Tránsito chilena. La multa oscila entre 1 y 1,5 UTM. Esta norma aplica tanto al conductor como a todos los pasajeros. El cinturón de seguridad reduce hasta en un 50% el riesgo de muerte en caso de accidente, siendo el elemento de seguridad pasiva más efectivo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 949,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanción implica usar el teléfono celular con las manos mientras se conduce?',
    opciones: ['Amonestación verbal', 'Infracción leve con multa menor', 'Infracción grave con multa y posible suspensión de licencia', 'Solo multa la segunda vez'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Usar el teléfono celular con las manos al conducir es una infracción grave con multa de 1 a 1,5 UTM. Solo se permite su uso con sistema manos libres (bluetooth o altavoz). La distracción por uso de celular es una de las principales causas de accidentes en Chile, aumentando significativamente el tiempo de reacción del conductor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 950,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la edad mínima para obtener la licencia de conducir Clase B en Chile?',
    opciones: ['16 años', '17 años con escuela de conductores', '18 años, o 17 con escuela de conductores certificada', '21 años'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La edad mínima para obtener la licencia Clase B es de 18 años. Sin embargo, jóvenes de 17 años pueden obtenerla si aprueban un curso en una escuela de conductores certificada por el Ministerio de Transportes. En ambos casos deben aprobar los exámenes teórico, práctico y psicotécnico en la municipalidad correspondiente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_b'],
  },
  {
    id: 951,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida en pasajes residenciales?',
    opciones: ['10 km/h', '20 km/h', '30 km/h', '40 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En pasajes residenciales la velocidad máxima es de 20 km/h. Estas vías estrechas son frecuentadas por niños jugando, peatones y ciclistas. El conductor debe extremar la precaución y estar preparado para detenerse en cualquier momento. La baja velocidad permite un tiempo de reacción adecuado para evitar accidentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 952,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué ocurre si un conductor excede en más de 20 km/h la velocidad máxima permitida?',
    opciones: ['Infracción leve', 'Infracción menos grave', 'Infracción grave', 'Infracción gravísima con posible suspensión de licencia'],
    respuestaCorrecta: 3,
    explicacionTexto: 'Exceder en más de 20 km/h el límite de velocidad constituye una infracción gravísima. Conlleva multas de 1,5 a 3 UTM y puede incluir la suspensión de la licencia de conducir. La velocidad excesiva reduce drásticamente la capacidad de reacción y aumenta exponencialmente la gravedad de los accidentes de tránsito.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 953,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cada cuántos años se debe renovar la licencia de conducir Clase B para personas menores de 60 años?',
    opciones: ['Cada 2 años', '4 años', '6 años', '10 años'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La licencia de conducir Clase B debe renovarse cada 6 años para personas menores de 60 años. Para personas entre 60 y 70 años se renueva cada 3 años, y para mayores de 70 años cada 2 años. La renovación requiere aprobar nuevamente el examen psicotécnico y, en algunos casos, el teórico.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_b'],
  },
  {
    id: 954,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanción corresponde por conducir con la licencia vencida?',
    opciones: ['Amonestación verbal', 'Infracción leve', 'Infracción grave', 'Infracción gravísima, equivalente a conducir sin licencia'],
    respuestaCorrecta: 3,
    explicacionTexto: 'Conducir con la licencia de conducir vencida se equipara a conducir sin licencia, lo que constituye una infracción gravísima. Las sanciones incluyen multas de 1,5 a 3 UTM, posible retención del vehículo y prohibición de continuar conduciendo hasta regularizar la situación. El conductor debe renovar su licencia antes del vencimiento.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 955,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué pista debe circular un vehículo lento en una autopista de varias pistas?',
    opciones: ['En la pista central', 'En la pista izquierda', 'En la pista derecha', 'En cualquier pista disponible'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los vehículos que circulan a menor velocidad deben hacerlo por la pista derecha. La pista izquierda es exclusivamente para adelantar. Circular lento por la pista izquierda obstaculiza el tránsito y constituye una infracción. Una vez completada la maniobra de adelantamiento, el conductor debe retornar a la pista derecha.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },

  // =============================================
  // PEATONES, CICLISTAS Y CONVIVENCIA VIAL (20 preguntas) - IDs 956-975
  // =============================================
  {
    id: 956,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué prioridad tiene el peatón al cruzar por un paso de cebra sin semáforo?',
    opciones: ['Debe esperar que pasen todos los vehículos', 'Tiene prioridad absoluta y los vehículos deben detenerse', 'Solo tiene prioridad si cruza en grupo', 'Debe solicitar paso con señas al conductor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El peatón tiene prioridad absoluta al cruzar por un paso de cebra, incluso sin semáforo. Los conductores deben detenerse completamente cuando un peatón está cruzando o manifiesta intención de hacerlo. No respetar esta prioridad constituye una infracción gravísima y puede resultar en un atropello con graves consecuencias legales y penales.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 957,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la distancia lateral mínima que se debe mantener al adelantar a un ciclista?',
    opciones: ['0.5 metros', '1 metro', '1.5 metros', '2 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al adelantar a un ciclista, el conductor debe mantener una distancia lateral mínima de 1.5 metros. Esta distancia protege al ciclista de la turbulencia generada por el vehículo y permite un margen de seguridad ante posibles movimientos imprevistos. Si no es posible mantener esta distancia, el conductor debe esperar hasta que pueda hacerlo de forma segura.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 958,
    categoria: 'Conducción Segura',
    pregunta: '¿Pueden los ciclistas circular por la calzada?',
    opciones: ['No, solo pueden usar ciclovías', 'Sí, tienen derecho a circular por la calzada', 'Solo en zonas rurales', 'Solo si no existe ciclovía'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los ciclistas tienen pleno derecho a circular por la calzada. Deben hacerlo por la pista derecha, lo más cerca posible del borde, y respetar las normas de tránsito. Cuando existe ciclovía, se recomienda su uso pero no es obligatorio en todos los casos. Los conductores deben respetar a los ciclistas como usuarios legítimos de la vía.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 959,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué prioridad tienen los peatones con discapacidad visual (bastón blanco o perro guía)?',
    opciones: ['La misma que cualquier peatón', 'Prioridad absoluta en cualquier punto de la vía', 'Solo prioridad en pasos de cebra', 'Deben ser acompañados por otra persona'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los peatones con discapacidad visual, identificados por bastón blanco o perro guía, tienen prioridad absoluta en cualquier punto de la vía, incluso fuera de los cruces peatonales. Los conductores deben detenerse y facilitar su cruce de manera segura. No respetar esta prioridad es una infracción gravísima dada la vulnerabilidad de estas personas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 960,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precauciones especiales debe tomar un conductor al ver niños o ancianos cerca de la vía?',
    opciones: ['Tocar la bocina para alertarlos', 'Reducir la velocidad y estar preparado para detenerse', 'Mantener la velocidad si tiene preferencia', 'Solo precaución en zonas escolares'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al ver niños o ancianos cerca de la vía, el conductor debe reducir la velocidad y estar preparado para detenerse de inmediato. Los niños pueden actuar de forma impredecible y los ancianos pueden tener movilidad reducida o problemas auditivos o visuales. La ley chilena establece que estos grupos tienen protección especial en la vía pública.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 961,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuándo puede un peatón cruzar la calle en una intersección con semáforo?',
    opciones: ['Cuando el semáforo vehicular está en rojo', 'Cuando el semáforo peatonal está en verde', 'En cualquier momento si mira a ambos lados', 'Solo cuando no hay vehículos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El peatón debe cruzar cuando el semáforo peatonal muestra la señal verde (silueta caminando). Si el semáforo peatonal comienza a parpadear, los que ya iniciaron el cruce deben completarlo, pero los que no han comenzado deben esperar. Cruzar con luz roja peatonal constituye una infracción y pone en riesgo la vida del peatón.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 962,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor si un peatón está cruzando fuera de un paso habilitado?',
    opciones: ['Tiene derecho a no detenerse', 'Tocar la bocina y continuar', 'Igualmente debe tomar precauciones y evitar atropellarlo', 'Acelerar para pasar antes que el peatón'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Aunque el peatón comete una infracción al cruzar fuera de un paso habilitado, el conductor siempre tiene el deber de cuidado y debe tomar todas las precauciones necesarias para evitar un atropello. La vida del peatón prevalece sobre la preferencia de paso del vehículo. El conductor debe reducir velocidad y estar preparado para frenar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 963,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué caracteriza una zona de tránsito calmado (zona 30)?',
    opciones: ['Velocidad máxima de 30 km/h con prioridad para peatones y ciclistas', 'Zona exclusivamente peatonal', 'Zona de estacionamiento regulado', 'Zona con semáforos inteligentes'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las zonas de tránsito calmado o zonas 30 son sectores urbanos donde la velocidad máxima es de 30 km/h y se prioriza la seguridad de peatones y ciclistas. Incluyen medidas de diseño como reductores de velocidad, calles estrechas y pavimento diferenciado. El objetivo es crear espacios de convivencia segura entre todos los usuarios de la vía.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 964,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precauciones debe tener un conductor respecto a los motociclistas?',
    opciones: ['Ninguna especial, deben cuidarse solos', 'Verificar espejos antes de cambiar de pista y respetar su espacio', 'Darles siempre la preferencia de paso', 'Dejarlos pasar entre los vehículos siempre'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los conductores deben tener especial precaución con los motociclistas por su mayor vulnerabilidad. Antes de cambiar de pista o girar, deben verificar los espejos retrovisores y el punto ciego. Los motociclistas son más difíciles de ver que los automóviles. Se debe respetar su espacio en la vía y no realizar maniobras que los pongan en riesgo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 965,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la responsabilidad principal del conductor ante los peatones?',
    opciones: ['Solo respetar semáforos', 'Velar por la seguridad del peatón en todo momento, incluso si este infringe', 'Solo detenerse en pasos de cebra', 'Tocar la bocina para advertirles'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor tiene la responsabilidad permanente de velar por la seguridad de los peatones en todo momento. Esto incluye reducir la velocidad en zonas con presencia peatonal, detenerse en pasos de cebra y evitar atropellos incluso cuando el peatón cruce de forma imprudente. La ley chilena siempre protege al más vulnerable en la vía.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 966,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor al aproximarse a un bus escolar detenido con luces intermitentes?',
    opciones: ['Adelantar con precaución por la izquierda', 'Detenerse y esperar hasta que el bus reanude la marcha', 'Tocar la bocina y pasar lentamente', 'Continuar a velocidad normal si hay espacio'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Cuando un bus escolar está detenido con las luces intermitentes activadas, indica que están subiendo o bajando niños. El conductor debe detenerse completamente, tanto si viene por detrás como en sentido contrario, y esperar hasta que el bus desactive las luces y reanude la marcha. Los niños pueden cruzar inesperadamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 967,
    categoria: 'Conducción Segura',
    pregunta: '¿Tienen los ciclistas la obligación de usar casco en Chile?',
    opciones: ['No, es opcional para todos', 'Sí, es obligatorio para todos los ciclistas', 'Solo para menores de 18 años', 'Solo en carreteras'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En Chile, el uso de casco es obligatorio para todos los ciclistas sin excepción, tanto en vías urbanas como rurales. Además, deben usar elementos reflectantes y luces en horario nocturno. El casco reduce significativamente el riesgo de lesiones craneales graves en caso de caída o colisión. Su incumplimiento es sancionado con multa.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 968,
    categoria: 'Conducción Segura',
    pregunta: '¿Por dónde deben circular los peatones cuando no existe vereda?',
    opciones: ['Por la calzada en el mismo sentido del tránsito', 'Por la berma en sentido contrario al tránsito', 'No deben circular en vías sin vereda', 'Por el centro de la calzada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Cuando no existe vereda, los peatones deben circular por la berma en sentido contrario al tránsito vehicular. Esto les permite ver los vehículos que se aproximan y reaccionar a tiempo. En horario nocturno deben usar elementos reflectantes o linterna. Los conductores deben extremar la precaución al circular por vías sin veredas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 969,
    categoria: 'Conducción Segura',
    pregunta: '¿Puede un conductor abrir la puerta del vehículo sin verificar que no vengan ciclistas?',
    opciones: ['Sí, el ciclista debe estar atento', 'No, debe verificar siempre antes de abrir la puerta', 'Solo en calles con ciclovía', 'Sí, si está estacionado legalmente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor y pasajeros deben verificar siempre que no vengan ciclistas, motociclistas u otros vehículos antes de abrir la puerta. El "dooring" (golpear a un ciclista al abrir la puerta) es una causa frecuente de accidentes graves. Se recomienda usar la técnica holandesa: abrir con la mano más lejana para girar el cuerpo y mirar atrás.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 970,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor al girar a la derecha si hay una ciclovía?',
    opciones: ['Girar sin preocuparse por la ciclovía', 'Ceder el paso a los ciclistas que circulan por la ciclovía', 'Los ciclistas deben detenerse siempre', 'Tocar la bocina para advertir a los ciclistas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al girar a la derecha en una intersección con ciclovía, el conductor debe ceder el paso a los ciclistas que circulan por ella. Debe verificar con los espejos y girando la cabeza que no haya ciclistas acercándose antes de iniciar el giro. Los ciclistas en la ciclovía generalmente tienen preferencia de paso sobre los vehículos que giran.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 971,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué deben usar los ciclistas para circular de noche?',
    opciones: ['Solo casco', 'Luz delantera blanca, luz trasera roja y elementos reflectantes', 'Solo chaleco reflectante', 'Nada especial, las luces de la calle son suficientes'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para circular de noche, los ciclistas deben usar obligatoriamente luz delantera blanca, luz trasera roja y elementos reflectantes en el cuerpo o la bicicleta. Estas medidas garantizan su visibilidad ante los conductores. Circular sin estos elementos de noche constituye una infracción y aumenta drásticamente el riesgo de ser atropellado.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 972,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué derechos tiene una persona en silla de ruedas al cruzar la calle?',
    opciones: ['Los mismos que cualquier peatón', 'Prioridad absoluta como persona con movilidad reducida', 'Debe esperar que no haya tránsito', 'Solo puede cruzar con ayuda de otra persona'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las personas en silla de ruedas tienen prioridad absoluta como personas con movilidad reducida. Los conductores deben detenerse y facilitarles el cruce de forma segura, dándoles el tiempo necesario. Las rampas en las veredas y los rebajes de solera están diseñados para facilitar su desplazamiento. La ley protege especialmente a las personas con discapacidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 973,
    categoria: 'Conducción Segura',
    pregunta: '¿Pueden los ciclistas circular por la vereda?',
    opciones: ['Sí, siempre que quieran', 'No, deben circular por la calzada o ciclovía', 'Solo si son menores de 14 años', 'Solo en zonas comerciales'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En general, los ciclistas adultos no deben circular por la vereda, ya que esta es espacio exclusivo para peatones. Sin embargo, los menores de 14 años pueden hacerlo. Los ciclistas adultos deben usar la calzada o ciclovía. Circular por la vereda pone en riesgo a los peatones y puede ser sancionado con multa según la normativa vigente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 974,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué significa el concepto de "usuario vulnerable de la vía"?',
    opciones: ['Conductores novatos', 'Peatones, ciclistas, motociclistas y personas con movilidad reducida', 'Solo personas de tercera edad', 'Conductores bajo la influencia del alcohol'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los usuarios vulnerables de la vía son aquellos que tienen mayor riesgo de sufrir lesiones graves en un accidente: peatones, ciclistas, motociclistas y personas con movilidad reducida. La Ley de Convivencia Vial establece que los conductores de vehículos motorizados deben proteger a estos usuarios y actuar con mayor precaución cuando estén presentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 975,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué establece la Ley de Convivencia Vial respecto a la jerarquía de usuarios?',
    opciones: ['Los automóviles tienen prioridad absoluta', 'Los peatones son los más protegidos, seguidos por ciclistas y luego vehículos motorizados', 'Todos los usuarios tienen la misma prioridad', 'Los buses de transporte público tienen la máxima prioridad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Ley de Convivencia Vial establece una jerarquía de protección donde los peatones son los más protegidos, seguidos por ciclistas, luego motociclistas y finalmente vehículos motorizados. Los usuarios de vehículos más grandes y potentes tienen mayor responsabilidad de cuidado hacia los más vulnerables. Este principio rige toda la normativa vial chilena.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },

  // =============================================
  // ALCOHOL, DROGAS Y CONDICIONES DEL CONDUCTOR (15 preguntas) - IDs 976-990
  // =============================================
  {
    id: 976,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el principal efecto del alcohol en la conducción?',
    opciones: ['Mejora los reflejos', 'Aumenta el tiempo de reacción, reduce la coordinación y altera la visión', 'Solo produce sueño', 'No afecta si se bebe poco'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El alcohol afecta múltiples funciones necesarias para conducir: aumenta significativamente el tiempo de reacción, reduce la coordinación motora, altera la percepción visual y de distancias, disminuye la capacidad de concentración y genera una falsa sensación de seguridad. Estos efectos aparecen incluso con cantidades pequeñas de alcohol.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 977,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanción se aplica cuando un conductor tiene entre 0.3 y 0.8 g/L de alcohol en la sangre?',
    opciones: ['Ninguna sanción', 'Sanción administrativa: multa y suspensión de licencia', 'Cárcel inmediata', 'Solo amonestación verbal'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Con un nivel de alcohol entre 0.3 y 0.8 g/L se considera conducción bajo la influencia del alcohol, lo que conlleva sanciones administrativas: multa de 2 a 10 UTM y suspensión de la licencia de conducir de 3 a 12 meses. Aunque no constituye delito penal, es una infracción grave que puede agravarse si se causa un accidente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 978,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué establece la Ley Emilia sobre el conductor que causa muerte estando ebrio?',
    opciones: ['Solo multa económica', 'Suspensión de licencia por un año', 'Pena de presidio efectivo de al menos un año, sin beneficios alternativos', 'Trabajo comunitario obligatorio'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La Ley Emilia (20.770) establece que quien conduce en estado de ebriedad y causa muerte o lesiones gravísimas recibirá una pena de presidio efectivo de al menos un año, sin posibilidad de penas alternativas como remisión condicional o libertad vigilada. También sanciona la negativa a someterse a la alcoholemia y la fuga del lugar del accidente.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 979,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué penas contempla la Ley Emilia para quien huye del lugar de un accidente con víctimas?',
    opciones: ['Multa solamente', 'Suspensión de licencia por 6 meses', 'Presidio de 3 años y un día a 10 años', 'Servicio comunitario'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La Ley Emilia establece penas de presidio de 3 años y un día a 10 años para quien huya del lugar de un accidente donde haya resultado una persona fallecida o con lesiones gravísimas. La fuga agrava significativamente la situación penal del conductor, independientemente de si estaba o no bajo la influencia del alcohol.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 980,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué sustancias puede detectar el narcotest utilizado por Carabineros?',
    opciones: ['Solo alcohol', 'Solo marihuana', 'Drogas como marihuana, cocaína, anfetaminas, opiáceos y benzodiazepinas', 'Solo drogas sintéticas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El narcotest utilizado por Carabineros puede detectar diversas sustancias: marihuana (THC), cocaína, anfetaminas y metanfetaminas, opiáceos y benzodiazepinas. Se realiza a través de una muestra de saliva. Conducir bajo el efecto de drogas tiene las mismas consecuencias legales que conducir en estado de ebriedad, incluyendo penas penales.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 981,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué la somnolencia al volante es tan peligrosa como el alcohol?',
    opciones: ['No es tan peligrosa', 'Porque puede causar que el conductor se quede dormido y pierda completamente el control', 'Solo es peligrosa de noche', 'Solo afecta a conductores profesionales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La somnolencia es tan peligrosa como el alcohol porque reduce drásticamente el tiempo de reacción, altera la percepción y puede causar "microsueños" donde el conductor pierde el conocimiento por segundos. A 100 km/h, un microsueño de 3 segundos significa recorrer más de 80 metros sin control. Se recomienda descansar cada 2 horas de conducción.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 982,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuáles son las señales de alerta de fatiga al conducir?',
    opciones: ['Solo bostezos frecuentes', 'Bostezos, párpados pesados, dificultad para mantener la velocidad y cambio involuntario de pista', 'Solo dificultad para ver', 'No hay señales claras de fatiga'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las señales de fatiga incluyen: bostezos frecuentes, párpados pesados, dificultad para mantener velocidad constante, cambios involuntarios de pista, dificultad para recordar los últimos kilómetros recorridos y visión borrosa. Ante estas señales, se debe detener el vehículo en un lugar seguro y descansar. Ningún estimulante sustituye el sueño.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 983,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué tipos de medicamentos pueden afectar la capacidad de conducir?',
    opciones: ['Solo los medicamentos controlados', 'Antihistamínicos, ansiolíticos, relajantes musculares y analgésicos fuertes', 'Solo los antibióticos', 'Ningún medicamento afecta la conducción'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Diversos medicamentos pueden afectar la conducción: antihistamínicos (producen somnolencia), ansiolíticos y tranquilizantes (reducen reflejos), relajantes musculares (reducen coordinación), analgésicos opioides y algunos antidepresivos. Siempre se debe leer el prospecto y consultar al médico. Si el medicamento indica que afecta la conducción, no se debe manejar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 984,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo afecta el estrés y la agresividad al volante?',
    opciones: ['Mejora la concentración', 'Provoca decisiones impulsivas, exceso de velocidad y maniobras arriesgadas', 'No tiene ningún efecto', 'Solo afecta a conductores novatos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El estrés y la agresividad al volante provocan decisiones impulsivas, tendencia al exceso de velocidad, maniobras arriesgadas como adelantamientos peligrosos y reducción de la tolerancia hacia otros conductores. La conducción agresiva es una de las principales causas de accidentes. Se recomienda practicar técnicas de relajación y evitar conducir en estados emocionales alterados.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 985,
    categoria: 'Conducción Segura',
    pregunta: '¿Es seguro conducir bajo efectos emocionales intensos como ira, tristeza o euforia?',
    opciones: ['Sí, las emociones no afectan la conducción', 'No, las emociones intensas alteran la concentración y la capacidad de juicio', 'Solo la ira afecta la conducción', 'Solo si se conduce a baja velocidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las emociones intensas como ira, tristeza profunda o euforia alteran significativamente la concentración, la capacidad de juicio y el tiempo de reacción. Un conductor emocionalmente alterado tiende a no percibir riesgos correctamente y a tomar decisiones imprudentes. Se recomienda no conducir hasta recuperar la calma y el equilibrio emocional.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 986,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene el alcohol sobre la visión del conductor?',
    opciones: ['Mejora la visión nocturna', 'Produce visión de túnel, dificultad de enfoque y mayor sensibilidad al deslumbramiento', 'No afecta la visión', 'Solo afecta la visión a larga distancia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El alcohol produce efectos graves en la visión: visión de túnel (reducción del campo visual periférico), dificultad para enfocar, visión doble, mayor sensibilidad al deslumbramiento por luces de otros vehículos y menor capacidad de adaptación a cambios de luminosidad. Estos efectos hacen la conducción nocturna especialmente peligrosa bajo influencia del alcohol.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 987,
    categoria: 'Conducción Segura',
    pregunta: '¿Puede un conductor negarse a realizar el test de alcoholemia solicitado por Carabineros?',
    opciones: ['Sí, es un derecho constitucional', 'Sí, sin ninguna consecuencia', 'No, la negativa se sanciona como si estuviera en estado de ebriedad', 'Solo puede negarse con abogado presente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La negativa a someterse al test de alcoholemia o narcotest solicitado por Carabineros se sanciona como si el conductor estuviera en estado de ebriedad, según lo establece la Ley Emilia. Esto significa que recibirá las mismas penas y sanciones que si se hubiera comprobado un nivel de alcohol sobre 0.8 g/L en su sangre.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 988,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuánto tiempo debe esperar para conducir después de consumir alcohol?',
    opciones: ['30 minutos', 'Basta con tomar café o agua', 'El tiempo varía, pero como mínimo varias horas según la cantidad consumida', 'Con una ducha fría puede conducir inmediatamente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El tiempo de eliminación del alcohol varía según la cantidad consumida, el peso corporal, el sexo y el metabolismo de cada persona. El hígado procesa aproximadamente 0.1 a 0.15 g/L por hora. Ningún método casero (café, ducha fría, ejercicio) acelera este proceso. Lo más seguro es no conducir si se ha consumido alcohol.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 989,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor si siente somnolencia durante un viaje largo?',
    opciones: ['Abrir la ventana y subir el volumen de la radio', 'Detenerse en un lugar seguro y dormir al menos 20 minutos', 'Tomar café y continuar', 'Acelerar para llegar más rápido'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si siente somnolencia, debe detenerse en un lugar seguro (estación de servicio, área de descanso) y dormir al menos 20 minutos. Ningún estimulante como café, música alta o ventana abierta sustituye efectivamente el descanso. Se recomienda no conducir más de 2 horas seguidas y planificar paradas de descanso durante viajes largos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 990,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el efecto combinado de alcohol y medicamentos al conducir?',
    opciones: ['Se anulan mutuamente', 'El efecto se potencia, siendo mucho más peligroso que cada uno por separado', 'No hay efecto combinado', 'El medicamento neutraliza el alcohol'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La combinación de alcohol con medicamentos (especialmente sedantes, antihistamínicos o analgésicos) potencia los efectos negativos de ambas sustancias. El resultado es una disminución mucho mayor de los reflejos, la concentración y la coordinación que la que produciría cada sustancia por separado. Esta combinación puede ser extremadamente peligrosa e incluso mortal al volante.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },

  // =============================================
  // ACCIDENTES Y PROCEDIMIENTOS LEGALES (15 preguntas) - IDs 991-1005
  // =============================================
  {
    id: 991,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué obligaciones tiene un conductor en caso de accidente con solo daños materiales?',
    opciones: ['Puede retirarse si los daños son menores', 'Debe detenerse, identificarse, intercambiar datos y hacer constancia en Carabineros o comisaría', 'Solo debe llamar al seguro', 'Solo debe tomar fotos y retirarse'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En un accidente con solo daños materiales, el conductor debe detenerse, identificarse, intercambiar datos con el otro involucrado (nombre, RUT, patente, seguro) y hacer una constancia en la comisaría más cercana dentro de 24 horas. También puede completar un parte amigable si ambas partes están de acuerdo en las circunstancias del accidente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 992,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué debe hacer un conductor involucrado en un accidente donde hay personas lesionadas?',
    opciones: ['Solo llamar a una ambulancia y retirarse', 'Detenerse, prestar ayuda a los heridos, llamar a emergencias y esperar a Carabineros', 'Retirarse si no fue su culpa', 'Solo tomar fotos como evidencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En un accidente con lesionados, el conductor debe detenerse inmediatamente, prestar los primeros auxilios posibles, llamar al servicio de emergencias (131 bomberos, 132 ambulancia, 133 Carabineros), señalizar el lugar del accidente y esperar a Carabineros. No debe abandonar el lugar bajo ninguna circunstancia, pues incurriría en el delito de fuga.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 993,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuáles son las consecuencias penales de huir del lugar de un accidente (ley de fuga)?',
    opciones: ['Solo una multa administrativa', 'Suspensión de licencia por 6 meses', 'Penas de presidio de hasta 10 años y cancelación de licencia', 'Amonestación por escrito'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Huir del lugar de un accidente constituye un delito grave. Según la Ley Emilia, si hay lesiones gravísimas o muerte, las penas pueden llegar hasta 10 años de presidio. Además, se cancela la licencia de conducir de por vida. Incluso en accidentes con solo daños materiales, la fuga constituye una infracción gravísima con severas consecuencias legales.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: allTypes,
  },
  {
    id: 994,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuándo se puede usar un parte amigable después de un accidente de tránsito?',
    opciones: ['En cualquier tipo de accidente', 'Solo cuando hay exclusivamente daños materiales y ambas partes están de acuerdo', 'Solo si interviene Carabineros', 'Solo en accidentes en autopistas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El parte amigable o declaración conjunta de accidente puede usarse solo cuando hay exclusivamente daños materiales (sin lesionados) y ambas partes están de acuerdo en las circunstancias del siniestro. Debe ser firmado por ambos conductores y presentado a las compañías de seguros. Si hay lesionados o desacuerdo, se debe llamar a Carabineros obligatoriamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 995,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué casos es obligatorio llamar a Carabineros después de un accidente?',
    opciones: ['Solo si hay fallecidos', 'Cuando hay lesionados, fallecidos, desacuerdo entre las partes o daños a bienes públicos', 'Solo si los daños superan cierto monto', 'Nunca es obligatorio, es opcional'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Es obligatorio llamar a Carabineros cuando hay personas lesionadas o fallecidas, cuando las partes no están de acuerdo sobre las circunstancias del accidente, cuando hay daños a bienes públicos o de terceros, y cuando alguno de los conductores se encuentra bajo la influencia del alcohol o drogas. El número de Carabineros es el 133.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 996,
    categoria: 'Primeros Auxilios',
    pregunta: '¿A qué distancia mínima del accidente se debe colocar el triángulo reflectante para señalizar?',
    opciones: ['10 metros', '25 metros', '50 metros', '100 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El triángulo reflectante debe colocarse a una distancia mínima de 50 metros detrás del vehículo accidentado para advertir a los demás conductores. En autopistas o vías de alta velocidad, esta distancia debe ser mayor (hasta 150 metros). Es obligatorio portar al menos un triángulo reflectante en todo vehículo motorizado en Chile.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 997,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cuándo se puede mover a una persona herida en un accidente de tránsito?',
    opciones: ['Siempre, para llevarla al hospital', 'Nunca bajo ninguna circunstancia', 'Solo cuando existe peligro inminente como incendio o riesgo de explosión', 'Solo si la persona lo solicita'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Solo se debe mover a un herido cuando existe peligro inminente como incendio, riesgo de explosión o derrumbe que amenace su vida. Mover a un herido sin la técnica adecuada puede agravar lesiones de columna vertebral y causar parálisis permanente. Siempre se debe esperar al personal de emergencias especializado para la movilización del herido.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 998,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En cuántas horas debe hacerse la constancia en comisaría después de un accidente de tránsito?',
    opciones: ['12 horas', '24 horas', '48 horas', '72 horas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La constancia de un accidente de tránsito debe realizarse en la comisaría más cercana dentro de las 24 horas siguientes al siniestro. Esta constancia es fundamental para efectos legales y de seguros. Incluye datos de los conductores, vehículos involucrados, circunstancias del accidente y nombres de testigos si los hubiera.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 999,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué cubre el Seguro Obligatorio de Accidentes Personales (SOAP)?',
    opciones: ['Daños materiales al vehículo', 'Gastos médicos y de rehabilitación de todas las personas afectadas por un accidente', 'Solo al conductor del vehículo asegurado', 'Robo del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El SOAP cubre gastos médicos, hospitalización y rehabilitación de todas las personas afectadas por un accidente de tránsito, independientemente de quién sea el responsable. Incluye conductor, pasajeros y peatones. También cubre una indemnización en caso de muerte. No cubre daños materiales al vehículo, para eso existe el seguro automotriz opcional.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 1000,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la diferencia entre el SOAP y un seguro automotriz comercial?',
    opciones: ['Son exactamente lo mismo', 'El SOAP cubre personas lesionadas; el seguro automotriz cubre daños materiales al vehículo', 'El SOAP es más completo que el seguro automotriz', 'El seguro automotriz es obligatorio y el SOAP es opcional'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El SOAP es obligatorio y cubre gastos médicos de personas lesionadas en accidentes de tránsito, sin importar culpa. El seguro automotriz comercial es voluntario y cubre daños materiales al vehículo propio, al de terceros, robo y otros riesgos según la póliza contratada. Ambos seguros son complementarios y se recomienda contar con los dos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 1001,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué debe hacer un conductor que atropella a un peatón?',
    opciones: ['Puede retirarse si el peatón se levanta', 'Debe detenerse, prestar ayuda, llamar a emergencias y dar cuenta a Carabineros siempre', 'Solo debe llamar a una ambulancia', 'Solo debe detenerse si el peatón está inconsciente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En caso de atropello, el conductor siempre debe detenerse inmediatamente, prestar los primeros auxilios al peatón, llamar al servicio de emergencias (132 ambulancia, 133 Carabineros) y dar cuenta del hecho. El atropello de peatón siempre debe ser reportado a Carabineros, independientemente de la gravedad aparente de las lesiones. La fuga agrava severamente las penas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 1002,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor si tiene un accidente en una autopista?',
    opciones: ['Quedarse en la calzada y esperar ayuda', 'Mover el vehículo a la berma de emergencia, encender balizas y colocar triángulo', 'Bajar del vehículo y caminar por la pista para pedir ayuda', 'Esperar en el vehículo en la pista sin hacer nada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En caso de accidente en autopista, se debe intentar mover el vehículo a la berma de emergencia si es posible, encender las luces de emergencia (balizas), colocar el triángulo reflectante a una distancia de al menos 100-150 metros, salir del vehículo por el lado de la berma y ubicarse detrás de la barrera de contención para esperar ayuda.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 1003,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué significa la cadena de socorro PAS (Proteger-Alertar-Socorrer)?',
    opciones: ['Un tipo de seguro vehicular', 'Los tres pasos secuenciales para actuar ante un accidente: proteger la zona, alertar a emergencias y socorrer a las víctimas', 'Un protocolo policial', 'Un sistema de comunicación por radio'],
    respuestaCorrecta: 1,
    explicacionTexto: 'PAS son las siglas de Proteger-Alertar-Socorrer, los tres pasos fundamentales ante un accidente. Primero, proteger la zona señalizándola para evitar nuevos accidentes. Segundo, alertar a los servicios de emergencia (131, 132, 133). Tercero, socorrer a las víctimas con primeros auxilios básicos sin moverlas, esperando al personal especializado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: allTypes,
  },
  {
    id: 1004,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué número de emergencia se debe llamar para solicitar una ambulancia en Chile?',
    opciones: ['131', '132', '133', '134'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El número 132 corresponde al SAMU (Servicio de Atención Médica de Urgencia) para solicitar una ambulancia. El 131 es para bomberos, el 133 para Carabineros y el 134 para la PDI. En caso de accidente de tránsito con lesionados, se recomienda llamar al 133 (Carabineros) quienes coordinan la llegada de todos los servicios de emergencia necesarios.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
  {
    id: 1005,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué es lo primero que se debe hacer al llegar a la escena de un accidente de tránsito?',
    opciones: ['Socorrer inmediatamente a los heridos', 'Llamar a los medios de comunicación', 'Proteger la zona del accidente para evitar nuevos siniestros', 'Tomar fotografías del accidente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Lo primero que se debe hacer es PROTEGER la zona del accidente: encender luces de emergencia, colocar triángulos reflectantes y señalizar para que otros vehículos reduzcan la velocidad y no provoquen un nuevo accidente. Luego se debe ALERTAR a los servicios de emergencia y finalmente SOCORRER a las víctimas siguiendo el protocolo PAS.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: allTypes,
  },
];
