import type { Question } from './questionsData';

export const questionsOficialClaseC: Question[] = [
  {
    id: 2200,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal de "Ceda el paso"?',
    opciones: ['Pase', 'Ceda el paso', 'Paso de peatones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal triangular invertida indica que debe ceder el paso a los vehículos que circulan por la vía preferente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2201,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal circular con un número que indica velocidad máxima?',
    opciones: ['Velocidad máxima', 'Velocidad mínima', 'Velocidad recomendada'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal circular con borde rojo y un número indica la velocidad máxima permitida en ese tramo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2202,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra la silueta de niños?',
    opciones: ['Niños jugando', 'Proximidad de paso de cebra', 'Zona de escuela'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal preventiva con silueta de niños advierte sobre la presencia de niños jugando en la zona.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2203,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra a una persona en un paso de cebra?',
    opciones: ['Niños jugando', 'Proximidad de paso de cebra', 'Zona de escuela'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Esta señal preventiva advierte sobre la proximidad de un paso de cebra o cruce peatonal.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2204,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra estudiantes con mochilas?',
    opciones: ['Niños jugando', 'Proximidad de paso de cebra', 'Zona de escuela'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Esta señal preventiva indica la presencia de una zona de escuela donde se debe extremar la precaución.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2205,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva con flechas circulares?',
    opciones: ['Proximidad de rotonda', 'Viento fuerte', 'Cruce peligroso'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las flechas circulares en una señal preventiva indican la proximidad de una rotonda.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2206,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal reglamentaria con una flecha hacia la izquierda tachada?',
    opciones: ['No virar a la izquierda', 'No virar en U', 'Prohibido el tránsito en sentido contrario'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal con una flecha hacia la izquierda tachada prohíbe virar a la izquierda.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2207,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal reglamentaria con una flecha en U tachada?',
    opciones: ['No virar a la izquierda', 'No virar en U', 'Prohibido el tránsito en sentido contrario'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal con una flecha en U tachada prohíbe realizar virajes en U en ese lugar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2208,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra un resalto en la vía?',
    opciones: ['Resalto', 'Pavimento en mal estado', 'Pendiente fuerte'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Esta señal preventiva advierte sobre la presencia de un resalto (lomo de toro) en la vía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2209,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal reglamentaria con una "E" tachada?',
    opciones: ['Prohibido estacionar', 'Prohibido estacionar y detenerse', 'Prohibido detenerse'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal con una "E" tachada prohíbe estacionar en ese lugar.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2210,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal reglamentaria con una "E" tachada y aspas cruzadas?',
    opciones: ['Prohibido estacionar', 'Prohibido estacionar y detenerse', 'Prohibido detenerse'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal con "E" tachada y aspas cruzadas prohíbe tanto estacionar como detenerse en ese lugar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2211,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal reglamentaria con una flecha apuntando a la derecha?',
    opciones: ['Dirección obligada', 'Permitido virar a la derecha', 'Prohibido virar a la izquierda'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La señal circular azul con una flecha blanca indica dirección obligada en el sentido de la flecha.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2212,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la demarcación de líneas blancas paralelas anchas en la calzada?',
    opciones: ['Paso de peatones', 'Paso de ciclistas', 'Línea de detención'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las líneas blancas paralelas anchas en la calzada corresponden a un paso de peatones (paso de cebra).',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2213,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la demarcación con símbolos de bicicleta en la calzada?',
    opciones: ['Paso de peatones', 'Paso de ciclistas', 'Línea de detención'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La demarcación con símbolos de bicicleta indica un cruce o paso destinado a ciclistas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2214,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la demarcación de una línea blanca transversal continua en la calzada?',
    opciones: ['Paso de peatones', 'Paso de ciclistas', 'Línea de detención'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La línea blanca transversal continua es una línea de detención donde los vehículos deben detenerse.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2215,
    categoria: 'Señalización',
    pregunta: 'Respecto de la zona achurada en la calzada:',
    opciones: ['No se puede transitar sobre la zona achurada', 'Solo los triciclos motorizados de carga pueden circular sobre la zona achurada', 'Peatones y ciclistas pueden circular sobre la zona achurada'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La zona achurada es una demarcación que indica que no se puede transitar sobre ella. Sirve para separar flujos de tránsito.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2216,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la demarcación con una X en la calzada dentro de una intersección?',
    opciones: ['Cruce de ferrocarriles', 'No bloquear cruce', 'Cruce peligroso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La demarcación con una X dentro de una intersección indica que no se debe bloquear el cruce.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2217,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Los triciclos motorizados de carga pueden circular por las pistas exclusivas de transporte público?',
    opciones: ['Sí', 'No', 'Solo por la noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden circular por las pistas exclusivas de transporte público.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2218,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la demarcación con flechas que indican solo virar a la derecha?',
    opciones: ['Solo se puede virar a la derecha', 'Es posible continuar derecho o virar a la izquierda', 'Solo se puede virar en U'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las flechas de dirección en la calzada indican los movimientos permitidos desde esa pista.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2219,
    categoria: 'Señalización',
    pregunta: '¿Qué significan las dos líneas continuas amarillas en la calzada?',
    opciones: ['Separan a los vehículos que circulan en sentidos opuestos', 'Separan dos pistas que van en el mismo sentido de tránsito', 'Separan el tránsito de automóviles del de buses'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las dos líneas continuas amarillas separan el tránsito en sentidos opuestos y prohíben el adelantamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2220,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga deben circular por:',
    opciones: ['La calzada', 'La acera', 'La ciclovía'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los triciclos motorizados de carga deben circular por la calzada, no por aceras ni ciclovías.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2221,
    categoria: 'Señalización',
    pregunta: '¿Qué significan las líneas blancas segmentadas en la calzada?',
    opciones: ['Separan pistas del mismo sentido y permiten cambio de pista', 'Prohíben el cambio de pista', 'Indican zona de estacionamiento'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las líneas blancas segmentadas separan pistas del mismo sentido y permiten el cambio de pista cuando es seguro.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2222,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga, ¿pueden circular por las ciclovías?',
    opciones: ['Sí', 'No', 'Sí, solo si no hay ciclistas utilizando la ciclovía'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden circular por las ciclovías, estas son exclusivas para bicicletas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2223,
    categoria: 'Conducción Segura',
    pregunta: 'Si otro vehículo te está adelantando, ¿qué debes hacer?',
    opciones: ['Permitir el adelantamiento', 'Aumentar la velocidad', 'Tocar la bocina para demostrar tu molestia'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Debes permitir el adelantamiento facilitando la maniobra del otro vehículo, sin aumentar la velocidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2224,
    categoria: 'Conducción Segura',
    pregunta: 'Los adelantamientos se deben realizar por:',
    opciones: ['La derecha', 'La izquierda', 'Cualquier lado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los adelantamientos deben realizarse siempre por la izquierda, salvo excepciones establecidas en la ley.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2225,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si el semáforo cambia a verde pero aún hay peatones cruzando la calle, debes:',
    opciones: ['Tocar la bocina', 'Esperar a que terminen de cruzar la calle', 'Avanzar, ya que tienes la preferencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Aunque el semáforo esté en verde, debes esperar a que los peatones terminen de cruzar la calle de forma segura.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2226,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si el semáforo cambia a verde pero aún hay vehículos cruzando la calle, debes:',
    opciones: ['Tocar la bocina', 'Esperar a que los vehículos terminen de atravesar la calle', 'Avanzar, ya que tienes la preferencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Debes esperar a que los vehículos que aún están cruzando terminen de atravesar la intersección antes de avanzar.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2227,
    categoria: 'Señalización',
    pregunta: 'Los vehículos que enfrenten una luz amarilla en el semáforo, deberán:',
    opciones: ['Acelerar y cruzar la calle lo más rápido posible', 'Detenerse', 'Cruzar la calle ya que la luz amarilla indica paso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La luz amarilla indica que los vehículos deben detenerse antes de la línea de detención.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2228,
    categoria: 'Señalización',
    pregunta: 'Una luz roja intermitente significa:',
    opciones: ['PARE', 'Ceda el paso', 'Precaución'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una luz roja intermitente tiene el mismo efecto que la señal de PARE: el vehículo debe detenerse completamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2229,
    categoria: 'Señalización',
    pregunta: 'Una luz amarilla intermitente significa:',
    opciones: ['Precaución', 'Ceda el paso', 'PARE'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Una luz amarilla intermitente indica precaución. Se debe reducir la velocidad y cruzar con cuidado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2230,
    categoria: 'Señalización',
    pregunta: 'Podrás pasar con luz roja:',
    opciones: ['Si conduces un triciclo motorizado de carga', 'Si no vienen vehículos por la otra calle', 'Si un Carabinero está dirigiendo el tránsito y te indica que avances'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Solo se puede pasar con luz roja si un Carabinero está dirigiendo el tránsito y te indica que avances.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2231,
    categoria: 'Señalización',
    pregunta: 'Podrás pasar con luz amarilla:',
    opciones: ['Si no alcanzas a detenerte con seguridad antes del cruce', 'Siempre', 'Si no vienen vehículos por la otra calle'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Solo se puede pasar con luz amarilla si no alcanzas a detenerte con seguridad antes del cruce.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2232,
    categoria: 'Conducción Segura',
    pregunta: 'Podrás utilizar la bocina para:',
    opciones: ['Apurar al vehículo que va delante tuyo', 'Avisar que te detendrás', 'Prevenir un siniestro'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La bocina solo debe utilizarse para prevenir siniestros de tránsito, no para apurar a otros conductores.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2233,
    categoria: 'Conducción Segura',
    pregunta: 'En qué caso se puede utilizar la bocina:',
    opciones: ['Para apurar al vehículo que va delante tuyo', 'Para avisar que te vas a estacionar', 'Para prevenir un siniestro'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La bocina se debe utilizar únicamente para prevenir siniestros de tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2234,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál de las siguientes describe un neumático inflado en exceso?',
    opciones: ['El centro del neumático está más desgastado', 'Los bordes del neumático están más desgastados', 'El desgaste es uniforme'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Un neumático inflado en exceso presenta mayor desgaste en el centro de la banda de rodamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2235,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál de las siguientes describe un neumático con falta de presión?',
    opciones: ['El centro está más desgastado', 'Los bordes están más desgastados', 'El desgaste es uniforme'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Un neumático con falta de presión presenta mayor desgaste en los bordes de la banda de rodamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2236,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál de las siguientes describe un neumático inflado correctamente?',
    opciones: ['El centro está más desgastado', 'El desgaste es uniforme en toda la superficie', 'Los bordes están más desgastados'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un neumático inflado correctamente presenta un desgaste uniforme en toda la superficie de contacto.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2237,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la distancia que debes mantener con el vehículo que va delante?',
    opciones: ['20 metros', '40 metros', 'Una distancia razonable y prudente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se debe mantener una distancia razonable y prudente con el vehículo que va delante, no una distancia fija.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2238,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la distancia que debes mantener con el vehículo que va delante? (variante)',
    opciones: ['Una distancia razonable y prudente', '30 metros exactos', '10 metros'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se debe mantener una distancia razonable y prudente, que varía según la velocidad y condiciones de la vía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2239,
    categoria: 'Conducción Segura',
    pregunta: 'La distancia razonable y prudente es:',
    opciones: ['Aquella que te permite detener tu vehículo ante una emergencia', '30 metros', 'Igual al largo de un vehículo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La distancia razonable y prudente es aquella que permite detener el vehículo de manera segura ante una emergencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2240,
    categoria: 'Conducción Segura',
    pregunta: 'Si vas a realizar un viraje, debes señalizarlo:',
    opciones: ['30 metros antes', '20 metros antes', '10 metros antes'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Todo viraje debe señalizarse con al menos 30 metros de anticipación para advertir a los demás usuarios de la vía.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2241,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se señaliza un viraje a la derecha con el brazo izquierdo?',
    opciones: ['Extendido horizontalmente', 'En ángulo recto hacia arriba', 'Extendido hacia abajo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para señalizar un viraje a la derecha con el brazo izquierdo, se extiende en ángulo recto hacia arriba.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2242,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se señaliza un viraje a la izquierda con el brazo izquierdo?',
    opciones: ['Extendido horizontalmente', 'En ángulo recto hacia arriba', 'Extendido hacia abajo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Para señalizar un viraje a la izquierda, el brazo izquierdo se extiende horizontalmente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2243,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se señaliza una reducción de velocidad con el brazo izquierdo?',
    opciones: ['Extendido horizontalmente', 'En ángulo recto hacia arriba', 'Extendido hacia abajo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Para señalizar una reducción de velocidad, el brazo izquierdo se extiende hacia abajo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2244,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuándo puedes transportar pasajeros en tu triciclo motorizado de carga, en el espacio destinado para la carga?',
    opciones: ['Siempre', 'En viajes de corta distancia', 'Nunca'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Nunca se pueden transportar pasajeros en el espacio destinado para la carga del triciclo motorizado.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2245,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuándo puedes transportar pasajeros en el espacio de carga de tu triciclo motorizado?',
    opciones: ['Siempre', 'En casos justificados y tomando las medidas de seguridad que correspondan', 'Nunca'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Nunca se permite transportar pasajeros en el espacio de carga del triciclo motorizado.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2246,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes transportar pasajeros en el espacio destinado para carga?',
    opciones: ['Sí', 'No', 'Solo una persona'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No se permite transportar pasajeros en el espacio destinado para carga del triciclo motorizado.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2247,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga, ¿pueden circular por la acera?',
    opciones: ['Sí', 'No', 'Solo por trayectos cortos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden circular por la acera, deben hacerlo por la calzada.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2248,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga, ¿pueden ser estacionados en la acera?',
    opciones: ['Sí', 'No', 'Solo si es por poco tiempo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden ser estacionados en la acera.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2249,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué debes hacer si te enfrentas a una señal PARE?',
    opciones: ['Avanzar lentamente, sin detenerme, hasta que puedas cruzar la calle', 'Detenerte y permitir el paso de los vehículos que circulan por la otra vía', 'Bajar la velocidad y tocar la bocina para advertir a los otros vehículos que vas a cruzar la calle'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante una señal PARE debes detenerte completamente y ceder el paso a los vehículos de la otra vía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2250,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué debes hacer si te enfrentas a una señal CEDA EL PASO?',
    opciones: ['Bajar la velocidad hasta detenerte si es necesario, para permitir que los vehículos que circulan por la otra vía puedan pasar', 'Detener tu vehículo y permitir el paso de los vehículos que circulan por la otra vía', 'Bajar la velocidad y tocar la bocina para advertir a los otros vehículos que vas a cruzar la calle'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Ante CEDA EL PASO debes bajar la velocidad y detenerte si es necesario para ceder el paso.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2251,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes detener tu vehículo en una ciclovía?',
    opciones: ['Sí', 'No', 'Sí, por un máximo de 10 minutos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No se puede detener el vehículo en una ciclovía bajo ninguna circunstancia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2252,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los vehículos motorizados de carga, ¿pueden detenerse en una ciclovía?',
    opciones: ['Sí', 'No', 'Sí, por períodos cortos de tiempo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos motorizados de carga no pueden detenerse en una ciclovía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2253,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes estacionarte en una ciclovía?',
    opciones: ['Sí', 'No', 'Sí, durante la noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Está prohibido estacionarse en una ciclovía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2254,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los vehículos motorizados de carga, ¿pueden detenerse en una ciclovía los fines de semana?',
    opciones: ['Sí', 'No', 'Sí, los días sábado y domingo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos motorizados de carga no pueden detenerse en una ciclovía ningún día de la semana.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2255,
    categoria: 'Ley de Tránsito',
    pregunta: 'En un triciclo motorizado de carga, ¿cuál es la capacidad máxima de carga?',
    opciones: ['250 kg', '300 kg', '500 kg'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La capacidad máxima de carga de un triciclo motorizado es de 300 kg según la ley.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2256,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la capacidad máxima de carga de un triciclo motorizado?',
    opciones: ['300 kg', '400 kg', '500 kg'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La capacidad máxima de carga de un triciclo motorizado de carga es de 300 kilogramos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2257,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes prestar tu vehículo a una persona que no tiene la Licencia de Conducir necesaria para conducirlo?',
    opciones: ['Sí', 'No', 'Solo mayores de 18 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No se puede prestar el vehículo a una persona que no tenga la licencia de conducir correspondiente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2258,
    categoria: 'Ley de Tránsito',
    pregunta: 'Un triciclo motorizado de carga, ¿necesita tener placa patente?',
    opciones: ['Sí', 'No', 'Solo si fueron fabricados después de 2017'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Todo triciclo motorizado de carga debe tener placa patente para circular.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2259,
    categoria: 'Ley de Tránsito',
    pregunta: 'Un triciclo motorizado de carga, ¿necesita tener seguro obligatorio de accidentes?',
    opciones: ['Sí', 'No', 'Solo si transitan por zonas rurales'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Todo triciclo motorizado de carga debe contar con el Seguro Obligatorio de Accidentes Personales (SOAP).',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2260,
    categoria: 'Ley de Tránsito',
    pregunta: 'Un triciclo motorizado de carga, ¿necesita obtener su permiso de circulación en la Municipalidad?',
    opciones: ['Sí', 'No', 'Solo si transitan por zonas urbanas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Todo triciclo motorizado de carga debe obtener su permiso de circulación en la Municipalidad correspondiente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2261,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿deben tener placa patente?',
    opciones: ['Sí', 'No', 'Solo si transitan por zonas urbanas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los triciclos motorizados de carga deben tener placa patente obligatoriamente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2262,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿necesitan obtener permiso de circulación?',
    opciones: ['Sí', 'No', 'Solo si transitan por zonas urbanas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los triciclos motorizados de carga deben obtener permiso de circulación obligatoriamente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2263,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si un triciclo motorizado de carga transita sin placa patente, ¿Carabineros puede retirarlo de circulación?',
    opciones: ['Sí', 'No', 'Solo si la persona que conduce no es la dueña del triciclo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Carabineros puede retirar de circulación un triciclo motorizado que transite sin placa patente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2264,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si un triciclo motorizado de carga transita sin placa patente, ¿Carabineros puede retirarlo de circulación? (variante)',
    opciones: ['Sí', 'No', 'Solo si la persona que conduce es la dueña del triciclo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Sí, Carabineros puede retirar de circulación cualquier triciclo sin placa patente, independiente de quién lo conduzca.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2265,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si un triciclo motorizado de carga transita sin el certificado vigente del SOAP, ¿Carabineros puede retirarlo de circulación?',
    opciones: ['Sí', 'No', 'Solo si quien conduce no es el dueño del triciclo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Carabineros puede retirar de circulación un triciclo que no cuente con SOAP vigente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2266,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿deben contar con revisión técnica?',
    opciones: ['Sí', 'No', 'Solo si transitan por vías urbanas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los triciclos motorizados de carga deben contar con revisión técnica vigente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2267,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿deben contar con revisión técnica? (variante fabricación)',
    opciones: ['Sí', 'No', 'Solo si fueron fabricados antes del 2017'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Todos los triciclos motorizados de carga deben contar con revisión técnica, sin importar su año de fabricación.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2268,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿deben contar con revisión técnica? (variante zona rural)',
    opciones: ['Sí', 'No', 'Solo si transitan por vías rurales'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los triciclos motorizados deben contar con revisión técnica sin importar por dónde circulen.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2269,
    categoria: 'Ley de Tránsito',
    pregunta: 'Deberás respetar y obedecer las señales del tránsito, excepto:',
    opciones: ['Si un Carabinero te da una instrucción contraria a las señales', 'Si otras personas conductoras tampoco respetan las señales', 'No hay excepciones'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las instrucciones de Carabineros prevalecen sobre las señales de tránsito. Es la única excepción.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2270,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si enfrentas un semáforo con luz roja y Carabineros te indica que debes avanzar, debes:',
    opciones: ['Obedecer la luz roja del semáforo', 'Obedecer la instrucción de Carabineros', 'Solo obedecer la instrucción de Carabineros si otros vehículos también lo hacen'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las instrucciones de Carabineros prevalecen sobre el semáforo. Debes obedecer al Carabinero.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2271,
    categoria: 'Señalización',
    pregunta: '¿Qué indica el semáforo con una flecha verde apuntando a la derecha?',
    opciones: ['Solo puedes virar a la derecha', 'Solo puedes seguir derecho', 'Puedes seguir derecho o virar a la derecha'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un semáforo con flecha verde apuntando a la derecha indica que solo puedes seguir derecho.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2272,
    categoria: 'Señalización',
    pregunta: '¿Qué indica el semáforo con una X roja sobre una pista?',
    opciones: ['No puedes utilizar esa pista', 'Debes circular con precaución por esa pista', 'Solo buses y camiones no pueden utilizar esa pista'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La X roja sobre una pista indica que no se puede utilizar dicha pista.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2273,
    categoria: 'Señalización',
    pregunta: '¿Qué indica el semáforo con flecha verde apuntando a la izquierda?',
    opciones: ['Solo puedes virar a la izquierda', 'Solo puedes seguir derecho', 'Puedes seguir derecho o virar a la izquierda'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Un semáforo con flecha verde apuntando a la izquierda indica que solo puedes virar a la izquierda.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2274,
    categoria: 'Conducción Segura',
    pregunta: '¿Debes conducir prestando atención a las condiciones de tránsito?',
    opciones: ['Sí, siempre', 'Solo si se conduce de día', 'Solo si se conduce de noche'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Siempre se debe conducir prestando atención a las condiciones de tránsito, sin importar la hora del día.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2275,
    categoria: 'Conducción Segura',
    pregunta: 'Si te encuentras en condiciones físicas deficientes:',
    opciones: ['Podrás conducir vehículos con precaución', 'Podrás conducir vehículos por trayectos cortos', 'No podrás conducir vehículos'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Si te encuentras en condiciones físicas deficientes, no puedes conducir ningún vehículo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2276,
    categoria: 'Conducción Segura',
    pregunta: 'La conducción en condiciones físicas deficientes:',
    opciones: ['Está permitida', 'Está prohibida', 'Es una decisión de la persona conductora'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La conducción en condiciones físicas deficientes está prohibida por la ley.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2277,
    categoria: 'Conducción Segura',
    pregunta: 'Si una persona tiene una concentración de alcohol en la sangre de 0,5 gramos por litro, entonces está:',
    opciones: ['Bajo la influencia del alcohol', 'En estado de ebriedad', 'Sobria'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Con 0,5 g/l de alcohol en la sangre, la persona está bajo la influencia del alcohol (entre 0,3 y 0,8 g/l).',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2278,
    categoria: 'Conducción Segura',
    pregunta: 'Si una persona tiene una concentración de alcohol en la sangre de 1 gramo por litro, entonces está:',
    opciones: ['Bajo la influencia del alcohol', 'En estado de ebriedad', 'Sobria'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Con 1 g/l de alcohol en la sangre, la persona está en estado de ebriedad (sobre 0,8 g/l).',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2279,
    categoria: 'Conducción Segura',
    pregunta: 'Si una persona tiene una concentración de alcohol en la sangre de 0,4 gramos por litro, entonces está:',
    opciones: ['Bajo la influencia del alcohol', 'En estado de ebriedad', 'Sobria'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Con 0,4 g/l de alcohol en la sangre, la persona está bajo la influencia del alcohol (entre 0,3 y 0,8 g/l).',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2280,
    categoria: 'Conducción Segura',
    pregunta: 'Si una persona tiene una concentración de alcohol en la sangre de 0,8 gramos por litro, entonces está:',
    opciones: ['Bajo la influencia del alcohol', 'En estado de ebriedad', 'Sobria'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Con 0,8 g/l de alcohol en la sangre, la persona se encuentra en estado de ebriedad.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2281,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿pueden circular por las autopistas?',
    opciones: ['Sí', 'No', 'Solo de noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden circular por autopistas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2282,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los triciclos motorizados de carga ¿pueden circular por las autovías?',
    opciones: ['Sí', 'No', 'Solo de noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden circular por autovías.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2283,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido que los triciclos motorizados de carga circulen por las autopistas?',
    opciones: ['Sí', 'No', 'Sí, solo por la pista derecha'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No está permitido que los triciclos motorizados circulen por autopistas bajo ninguna circunstancia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2284,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido que los triciclos motorizados de carga circulen por las autovías?',
    opciones: ['Sí', 'No', 'Sí, solo por la pista derecha'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No está permitido que los triciclos motorizados circulen por autovías.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2285,
    categoria: 'Ley de Tránsito',
    pregunta: 'Por regla general, los vehículos deben circular por:',
    opciones: ['La mitad derecha de la calzada', 'La mitad izquierda de la calzada', 'Por el medio de la calzada'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Por regla general, todos los vehículos deben circular por la mitad derecha de la calzada.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2286,
    categoria: 'Conducción Segura',
    pregunta: 'Los vehículos que circulen a una velocidad inferior a la máxima, deberán hacerlo por la:',
    opciones: ['Derecha', 'Izquierda', 'Acera'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los vehículos que circulen más lento deben hacerlo por la pista derecha.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2287,
    categoria: 'Conducción Segura',
    pregunta: 'Los vehículos que circulen a una velocidad inferior a la máxima, deberán hacerlo por la: (variante)',
    opciones: ['Derecha', 'Izquierda', 'Ciclovía'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los vehículos más lentos deben circular por la derecha, nunca por la ciclovía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2288,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Podrás sobrepasar a otro vehículo invadiendo una ciclovía?',
    opciones: ['Sí', 'No', 'Solo si no hay ciclistas circulando por la ciclovía'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Nunca se puede sobrepasar a otro vehículo invadiendo una ciclovía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2289,
    categoria: 'Conducción Segura',
    pregunta: '¿Podrás sobrepasar a otro vehículo invadiendo la acera?',
    opciones: ['Sí', 'No', 'Solo si no hay peatones circulando por la acera'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Nunca se puede sobrepasar a otro vehículo invadiendo la acera.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2290,
    categoria: 'Ley de Tránsito',
    pregunta: 'En una rotonda, debes circular siguiendo la trayectoria indicada por las señales:',
    opciones: ['En cualquier dirección', 'En el sentido contrario a las agujas del reloj', 'En el sentido que tú elijas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En una rotonda se debe circular en el sentido indicado por las señales, generalmente en sentido contrario a las agujas del reloj.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2291,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido realizar un viraje en U en un paso para peatones?',
    opciones: ['Sí, siempre', 'No', 'Sí, solo si no hay peatones cruzando por el paso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No está permitido realizar virajes en U en pasos para peatones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2292,
    categoria: 'Ley de Tránsito',
    pregunta: 'En una intersección sin señalización, ¿quién tiene la preferencia?',
    opciones: ['El vehículo rojo que viene por la derecha', 'El vehículo que viene por la izquierda', 'El vehículo más grande'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En una intersección sin señalización, tiene preferencia el vehículo que se aproxima por la derecha.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2293,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si ves que una ambulancia se aproxima al cruce con su sirena y señales luminosas encendidas:',
    opciones: ['Debes permitirle el paso', 'Debes pasar primero', 'Se debe respetar la señal de prioridad o semáforo que esté instalado en el cruce'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Siempre debes permitir el paso a vehículos de emergencia con sirena y luces encendidas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2294,
    categoria: 'Conducción Segura',
    pregunta: 'Debes circular:',
    opciones: ['A la velocidad mínima establecida', 'A la velocidad máxima establecida', 'A una velocidad razonable y prudente no superior a la máxima'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se debe circular a una velocidad razonable y prudente, sin superar la velocidad máxima establecida.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2295,
    categoria: 'Conducción Segura',
    pregunta: 'La velocidad debe ser tal, que:',
    opciones: ['Permita controlar el vehículo en todo momento', 'Permita adelantar sin problemas a todos los vehículos', 'Permita sobrepasar a bicicletas y otros ciclos'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La velocidad debe permitir controlar el vehículo en todo momento y ante cualquier situación.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2296,
    categoria: 'Conducción Segura',
    pregunta: 'La velocidad máxima en zonas urbanas es de:',
    opciones: ['50 km/h', '60 km/h', '40 km/h'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La velocidad máxima en zonas urbanas es de 50 km/h, salvo señalización que indique lo contrario.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2297,
    categoria: 'Conducción Segura',
    pregunta: 'En zona de escuelas, en horario de entrada y salida de clases, la velocidad máxima es de:',
    opciones: ['20 km/h', '30 km/h', '40 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zona de escuelas, durante el horario de entrada y salida de clases, la velocidad máxima es de 30 km/h.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2298,
    categoria: 'Conducción Segura',
    pregunta: 'En zona de escuelas, en horario de entrada y salida de clases, se puede circular a un máximo de:',
    opciones: ['20 km/h', '30 km/h', '50 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zonas escolares durante horarios de clases, el máximo permitido es 30 km/h.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2299,
    categoria: 'Ley de Tránsito',
    pregunta: 'Los vehículos deben estar estacionados:',
    opciones: ['A favor del sentido del tránsito', 'En contra del sentido del tránsito', 'De cualquier manera'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los vehículos siempre deben estacionarse a favor del sentido del tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2300,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si participas en un siniestro de tránsito donde solo hubo daños en los vehículos, entonces:',
    opciones: ['Debes informar a Carabineros de Chile de inmediato', 'Debes informar a Carabineros de Chile en un plazo de 5 días', 'No debes informar a Carabineros de Chile'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En caso de siniestro con daños materiales, se debe informar a Carabineros de inmediato.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2301,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si tienes un siniestro donde tu vehículo resulta con daños, entonces:',
    opciones: ['No debes informar del siniestro a Carabineros de Chile', 'Debes informar inmediatamente a Carabineros de Chile', 'Tienes un plazo de 48 horas para informar a Carabineros de Chile'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un siniestro con daños, debes informar inmediatamente a Carabineros de Chile.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2302,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si estás involucrada/o en un siniestro donde hay personas lesionadas, debes:',
    opciones: ['No informar del siniestro a Carabineros', 'Informar inmediatamente a Carabineros de Chile', 'Tienes un plazo de 48 horas para informar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En un siniestro con personas lesionadas, debes informar inmediatamente a Carabineros.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2303,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si estás involucrada/o en un siniestro donde hay personas lesionadas:',
    opciones: ['Debes detenerte y prestar toda la ayuda que sea posible', 'Debes detenerte solo si eres culpable del siniestro', 'Puedes continuar sin detenerte y dar aviso a Carabineros posteriormente'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Siempre debes detenerte y prestar toda la ayuda posible a las personas lesionadas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2304,
    categoria: 'Conducción Segura',
    pregunta: 'Si la autoridad fiscalizadora te sorprende conduciendo tu vehículo bajo la influencia del alcohol:',
    opciones: ['No podrás conducir por un periodo de 3 meses', 'No podrás conducir por un periodo de 1 mes', 'No podrás conducir por un periodo de 2 meses'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Si te sorprenden conduciendo bajo la influencia del alcohol, no podrás conducir por 3 meses.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2305,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes es considerada una infracción gravísima?',
    opciones: ['Estacionar en un lugar prohibido', 'Conducir tu vehículo con neumáticos en mal estado', 'No detenerte ante la luz roja de un semáforo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No detenerse ante la luz roja de un semáforo es una infracción gravísima.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2306,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes es considerada una infracción grave? (señal CEDA EL PASO)',
    opciones: ['No respetar una señal CEDA EL PASO', 'No respetar una señal PARE', 'No señalizar antes de virar'],
    respuestaCorrecta: 0,
    explicacionTexto: 'No respetar una señal CEDA EL PASO es considerada una infracción grave.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2307,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes es considerada una infracción grave? (derecho de paso)',
    opciones: ['No señalizar antes de virar', 'Arrojar basura desde tu vehículo', 'No respetar el derecho de paso de un peatón'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No respetar el derecho de paso de un peatón es una infracción grave.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2308,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes es considerada una infracción grave? (permiso de circulación)',
    opciones: ['Estacionarse en doble fila', 'Conducir un vehículo sin permiso de circulación', 'No detenerse ante una señal PARE'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Conducir un vehículo sin permiso de circulación es una infracción grave.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2309,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes es considerada una infracción grave? (pista de circulación)',
    opciones: ['Estacionarse en lugares exclusivos para personas en situación de discapacidad', 'No conducir dentro de la pista de circulación demarcada', 'No respetar una señal PARE'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Estacionarse en lugares exclusivos para personas en situación de discapacidad es una infracción grave.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2310,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes es considerada una infracción gravísima? (sentido del tránsito)',
    opciones: ['Arrojar basura desde tu vehículo', 'Conducir un vehículo contra el sentido del tránsito', 'No detenerse ante una señal PARE'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Conducir contra el sentido del tránsito es considerada una de las infracciones más graves.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2311,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si cometes una infracción gravísima, tu Licencia de Conducir será suspendida por un periodo de:',
    opciones: ['5 a 45 días', '45 a 90 días', '90 días'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Una infracción gravísima puede resultar en la suspensión de la licencia por un periodo de 5 a 45 días.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2312,
    categoria: 'Ley de Tránsito',
    pregunta: 'No respetar una señal CEDA EL PASO es considerada una infracción:',
    opciones: ['Leve', 'Grave', 'Gravísima'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No respetar una señal CEDA EL PASO es una infracción grave.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2313,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si te estacionas indebidamente en un estacionamiento exclusivo para personas en situación de discapacidad, estás cometiendo una infracción:',
    opciones: ['Leve', 'Menos grave', 'Grave'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Estacionarse indebidamente en un lugar para personas con discapacidad es una infracción grave.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2314,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si cometes una infracción gravísima por primera vez, arriesgas:',
    opciones: ['Una multa en dinero más la suspensión de tu Licencia de Conducir', 'Una multa en dinero', 'La suspensión de tu Licencia de Conducir'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Una infracción gravísima por primera vez conlleva multa más suspensión de la licencia.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2315,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si luego de obtener tu Licencia de Conducir te cambias de domicilio, ¿debes informar de este cambio?',
    opciones: ['Sí', 'No', 'Solo si se cambia de región'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Sí, debes informar cualquier cambio de domicilio después de obtener la licencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2316,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si luego de obtener tu Licencia de Conducir te cambias de domicilio, ¿a quién se le debe informar?',
    opciones: ['A la municipalidad que otorgó la licencia', 'A la municipalidad de tu nuevo domicilio', 'A la municipalidad que otorgó la licencia o en aquella de tu nuevo domicilio'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El cambio de domicilio se debe informar a la municipalidad correspondiente al nuevo domicilio.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2317,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si te estás incorporando a la circulación desde un estacionamiento:',
    opciones: ['Tienes la preferencia para realizar esta acción', 'No tienes preferencia para realizar esta acción', 'Tienes preferencia solo si es de noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al incorporarte a la circulación desde un estacionamiento no tienes preferencia sobre el tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2318,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si viras a la derecha:',
    opciones: ['Tienes preferencia para realizar esta maniobra', 'No tienes preferencia para realizar esta maniobra', 'No tienes preferencia solo si hay peatones cruzando'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al virar a la derecha no tienes preferencia automática. Debes ceder el paso según corresponda.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2319,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si viras a la izquierda:',
    opciones: ['Tienes preferencia para realizar esta maniobra', 'No tienes preferencia para realizar esta maniobra', 'No tienes preferencia solo si hay peatones cruzando'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al virar a la izquierda no tienes preferencia. Debes ceder el paso a los vehículos que vienen en sentido contrario.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2320,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál de las siguientes alternativas es la correcta sobre conducción?',
    opciones: ['Puedes conducir tu vehículo bajo la influencia del alcohol', 'Debes conducir tu vehículo con atención a las condiciones del tránsito', 'Puedes conducir tu triciclo motorizado de carga por las ciclovías'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Siempre se debe conducir con atención a las condiciones de tránsito, respetando todas las normas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2321,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si llegas a un cruce al cual se aproxima un vehículo de emergencia con sus señales luminosas y audibles funcionando:',
    opciones: ['Debes atravesar la calle lo más rápido posible', 'Debes detenerte y esperar a que el vehículo de emergencia cruce la calle', 'Si tienes luz verde, el vehículo de emergencia deberá respetar tu preferencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Debes detenerte y esperar a que el vehículo de emergencia pase. Siempre tienen prioridad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2322,
    categoria: 'Conducción Segura',
    pregunta: '¿Existe alguna excepción para superar el límite máximo de velocidad?',
    opciones: ['Sí, cuando debes dar paso a los vehículos de emergencia', 'Sí, durante la noche se puede conducir a una velocidad mayor a la máxima', 'No, no hay excepciones'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No existen excepciones para superar el límite máximo de velocidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2323,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al llegar a un cruce ferroviario, debes:',
    opciones: ['Detenerte antes del cruce, salvo que exista una señal que indique lo contrario', 'Avanzar, ya que tienes preferencia por sobre los trenes', 'Tocar la bocina para advertir que estás cruzando la línea férrea'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Al llegar a un cruce ferroviario debes detenerte antes del cruce por seguridad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2324,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si se aproxima un vehículo de emergencia haciendo uso de sus señales en el mismo sentido que circulas:',
    opciones: ['Debes hacerte hacia un lado y permitir que pase el vehículo de emergencia', 'Debes acelerar para no entorpecer al vehículo de emergencia', 'Debes tocar la bocina para que los vehículos delante tuyo avancen más rápido'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Debes hacerte a un lado para permitir el paso del vehículo de emergencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2325,
    categoria: 'Señalización',
    pregunta: 'La flecha verde intermitente de un semáforo tiene el mismo significado que:',
    opciones: ['La luz roja', 'La luz amarilla', 'La luz verde'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La flecha verde intermitente tiene el mismo significado que la luz amarilla: precaución, prepárese para detenerse.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2326,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si cometes una infracción y Carabineros retiene tu Licencia de Conducir, ¿qué documento te permite seguir conduciendo?',
    opciones: ['La boleta de citación que entregue Carabineros, solo hasta el día y hora que se indique en ella', 'El permiso de circulación y revisión técnica', 'El permiso de circulación, la revisión técnica y el seguro obligatorio SOAP'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La boleta de citación de Carabineros permite seguir conduciendo temporalmente hasta la fecha indicada.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2327,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al llegar a un cruce ferroviario, debes: (variante)',
    opciones: ['Detenerte antes del cruce, salvo que exista una señal que indique lo contrario', 'Avanzar, ya que tienes preferencia por sobre los trenes que circulan', 'Encender las luces de advertencia de peligro mientras cruzas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Siempre debes detenerte antes de un cruce ferroviario, salvo señalización contraria.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2328,
    categoria: 'Conducción Segura',
    pregunta: '¿Puedes conducir tu vehículo en condiciones físicas deficientes?',
    opciones: ['Sí, solo por trayectos cortos', 'No, nunca', 'Sí, solo durante horas de la noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No se puede conducir en condiciones físicas deficientes bajo ninguna circunstancia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2329,
    categoria: 'Conducción Segura',
    pregunta: 'Si estás enferma/o y estás tomando medicamentos:',
    opciones: ['Debes preguntarle a tu médico si puedes conducir mientras dura el tratamiento', 'No debes conducir mientras dure el tratamiento', 'Puedes conducir sin problema'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Si tomas medicamentos, debes consultar a tu médico si puedes conducir durante el tratamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2330,
    categoria: 'Conducción Segura',
    pregunta: 'Si sientes cansancio y sueño:',
    opciones: ['No debes conducir', 'Puedes conducir a baja velocidad por calles poco transitadas', 'Puedes conducir con las luces de advertencia de peligro encendidas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Si sientes cansancio o sueño, no debes conducir. Detente en un lugar seguro y descansa.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2331,
    categoria: 'Conducción Segura',
    pregunta: 'Si deseas cambiarte de pista, ¿debes señalizar esta maniobra?',
    opciones: ['Sí', 'No', 'Solo si hay vehículos circulando en la pista a la que deseo cambiarme'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Siempre se debe señalizar cualquier cambio de pista, independientemente del tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2332,
    categoria: 'Ley de Tránsito',
    pregunta: 'Si cometes una infracción y Carabineros retiene tu Licencia de Conducir, ¿puedes seguir conduciendo?',
    opciones: ['Sí, con la boleta de citación que entregue Carabineros, solo hasta el día y hora que se indique en ella', 'No, no puedes conducir hasta la fecha de citación', 'Sí, puedes conducir pero solo para regresar a tu casa'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Con la boleta de citación de Carabineros puedes seguir conduciendo hasta la fecha indicada.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2333,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debes hacer para cambiarte de pista?',
    opciones: ['Señalizar la maniobra con anticipación', 'Tocar la bocina para avisar a los otros vehículos', 'Realizar la maniobra lo más rápido posible aunque entorpezca la circulación'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Para cambiarte de pista debes señalizar la maniobra con anticipación suficiente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2334,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra una bicicleta?',
    opciones: ['Ciclovía', 'Cruce de ciclistas', 'Estacionamiento para bicicletas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal preventiva con bicicleta advierte sobre un cruce de ciclistas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2335,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra una señal PARE adelante?',
    opciones: ['Proximidad a Señal PARE', 'Señal PARE para ciclistas', 'Recomienda parar en la próxima intersección'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Esta señal preventiva advierte sobre la proximidad de una señal PARE más adelante.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2336,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Los triciclos motorizados de carga pueden estacionarse en estacionamientos para bicicletas?',
    opciones: ['Sí', 'No', 'Solo por 30 minutos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los triciclos motorizados de carga no pueden estacionarse en lugares destinados a bicicletas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2337,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes estacionar tu triciclo motorizado en un estacionamiento para bicicletas?',
    opciones: ['Solo si hay espacio disponible', 'Sí', 'No'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No se puede estacionar un triciclo motorizado en un estacionamiento para bicicletas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2338,
    categoria: 'Conducción Segura',
    pregunta: '¿Puedes conducir haciendo uso de tu teléfono celular?',
    opciones: ['Sí, solo si cuentas con dispositivo "manos libres"', 'No', 'Sí, siempre'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Solo se permite usar el teléfono celular con un dispositivo manos libres mientras conduces.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2339,
    categoria: 'Conducción Segura',
    pregunta: '¿Está permitido el uso de teléfono celular mientras conduces?',
    opciones: ['Sí', 'No', 'Solo si cuentas con "manos libres"'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El uso de teléfono celular solo está permitido con dispositivo manos libres.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2340,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puedes estacionar a menos de 10 metros de una esquina?',
    opciones: ['Sí', 'No', 'Solo si te mantienes arriba del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'No se puede estacionar a menos de 10 metros de una esquina.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2341,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Quién tiene la preferencia en una rotonda?',
    opciones: ['El vehículo que va a ingresar a la rotonda', 'Los vehículos que circulan en la rotonda', 'El vehículo de mayor tamaño'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos que ya circulan dentro de la rotonda tienen preferencia sobre los que desean ingresar.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2342,
    categoria: 'Ley de Tránsito',
    pregunta: 'Al llegar a una rotonda, ¿cuál de las siguientes afirmaciones es correcta?',
    opciones: ['Debes detenerte obligatoriamente antes de ingresar', 'Debes ceder el paso a los vehículos que circulan por la rotonda', 'Podrás ingresar directamente ya que tienes la preferencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al llegar a una rotonda debes ceder el paso a los vehículos que ya circulan por ella.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2343,
    categoria: 'Señalización',
    pregunta: '¿Qué indica la demarcación con una X en un cruce?',
    opciones: ['Paso de peatones', 'Cruce de ciclistas', 'No bloquear cruce'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La demarcación en el cruce indica un paso de peatones o restricción de bloqueo según el diseño.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2344,
    categoria: 'Señalización',
    pregunta: 'De las demarcaciones presentes en una intersección, ¿cuál corresponde a la línea de detención?',
    opciones: ['La línea más cercana al cruce, transversal a la dirección de circulación', 'Las líneas paralelas del paso de cebra', 'Las flechas direccionales en la calzada'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La línea de detención es la línea transversal más cercana al cruce donde los vehículos deben detenerse.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2345,
    categoria: 'Señalización',
    pregunta: '¿Qué indica la demarcación de una flecha obligando a virar a la izquierda?',
    opciones: ['Solo puedes virar a la izquierda', 'Hay una curva a la izquierda', 'Está permitido virar a la izquierda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La flecha indica la obligación de virar o la presencia de una curva según la señalización.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2346,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal con el símbolo de una persona en silla de ruedas?',
    opciones: ['Está permitido estacionar', 'Estacionamiento para personas en situación de discapacidad', 'Estacionamiento para bicicletas'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El símbolo de silla de ruedas indica un estacionamiento reservado para personas en situación de discapacidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2347,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué caso está permitido virar en U?',
    opciones: ['En pasos para peatones', 'En las intersecciones', 'Donde la señalización lo permita'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Solo se permite virar en U donde la señalización expresamente lo permita.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2348,
    categoria: 'Señalización',
    pregunta: 'Si vas por la pista derecha y hay una línea continua separándola de la pista izquierda, ¿puedes cambiarte?',
    opciones: ['Sí', 'No', 'Solo si ambas pistas tienen el mismo sentido de tránsito'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una línea continua prohíbe el cambio de pista. No se puede cruzar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2349,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra un estrechamiento del lado derecho?',
    opciones: ['Angostamiento del lado derecho de la calle', 'Angostamiento del lado izquierdo de la calle', 'Ensanchamiento de la calle'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Esta señal preventiva advierte sobre un angostamiento de la calzada por el lado derecho.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2350,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal preventiva que muestra la silueta de niños con mochilas cruzando?',
    opciones: ['Niños jugando', 'Zona de escuela', 'Cruce peatonal'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Esta señal advierte sobre la presencia de niños en la zona, generalmente cerca de escuelas o parques.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
  {
    id: 2351,
    categoria: 'Señalización',
    pregunta: '¿Qué significa la señal octogonal roja con la palabra PARE?',
    opciones: ['Ceda el paso', 'PARE', 'Paso de peatones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La señal octogonal roja es la señal de PARE, que obliga a detenerse completamente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
    oficial: true,
  },
];
