import type { Question } from './questionsData';

export const questionsOficialPart2: Question[] = [
  {
    id: 2063,
    pregunta: '¿Cuándo las personas que conducen deben mantenerse atentas a las condiciones del tránsito del momento?',
    opciones: ['Siempre', 'Solo en días de lluvia y niebla', 'Solo en la noche'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las personas que conducen deben mantenerse atentas SIEMPRE a las condiciones del tránsito.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2064,
    pregunta: 'Una persona puede manejar un vehículo bajo la influencia del alcohol.',
    opciones: ['Nunca', 'Solo de día', 'Sin estar ebrio'],
    respuestaCorrecta: 0,
    explicacionTexto: 'NUNCA se puede manejar bajo la influencia del alcohol. La Ley Emilia establece tolerancia cero.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2065,
    pregunta: 'Los vehículos deberán circular por la mitad derecha de la calzada, salvo en el siguiente caso, entre otros:',
    opciones: ['En circulación rural, cuando la velocidad sea menor a 45 km/h', 'En circulación urbana, cuando la velocidad sea menor a 45 km/h', 'En la circulación urbana, cuando la calzada está exclusivamente señalizada para el tránsito en un solo sentido'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se puede circular fuera de la mitad derecha cuando la calzada está señalizada para tránsito en un solo sentido.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2066,
    pregunta: 'En condiciones normales un vehículo podrá ser conducido marcha atrás solo:',
    opciones: ['50 metros', '30 metros', 'Para mantener la libre circulación o para incorporarse a ella o estacionar un vehículo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La marcha atrás solo se permite para mantener la libre circulación, incorporarse o estacionar.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2067,
    pregunta: 'En vías de doble tránsito, los vehículos que circulen en sentido opuesto, al cruzarse:',
    opciones: ['Deberán encender las luces bajas', 'Deberán señalizar con los brazos', 'No pasarán sobre el eje de la calzada, demarcado o imaginario'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al cruzarse en vías de doble tránsito, los vehículos no deben pasar sobre el eje de la calzada.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2068,
    pregunta: 'Quien conduce un vehículo puede sobrepasar a otro por la derecha, cuando:',
    opciones: ['El vehículo de adelante va a virar a la derecha', 'El vehículo de adelante va a virar a la izquierda', 'Nunca'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se puede sobrepasar por la derecha cuando el vehículo de adelante va a virar a la izquierda.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2069,
    pregunta: 'No se podrá adelantar en el siguiente caso:',
    opciones: ['Al aproximarse a un camión', 'Cuando existe eje discontinuo', 'Al aproximarse a la cima de una cuesta'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No se puede adelantar al aproximarse a la cima de una cuesta por falta de visibilidad.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2070,
    pregunta: 'Se prohíbe efectuar viraje en "U" en el siguiente caso:',
    opciones: ['A mitad de cuadra', 'A 300 mts. de una curva', 'En los pasos peatonales'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Está prohibido efectuar viraje en U en los pasos peatonales.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2071,
    pregunta: 'Cuando los vehículos circulan en caravana o convoy, la distancia entre los vehículos será:',
    opciones: ['Entre 1 a 4 metros', 'La suficiente para que cualquier vehículo que los adelante pueda ocupar la vía sin peligro', 'Ninguna, no se puede circular en caravana o convoy'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La distancia debe ser suficiente para que otro vehículo pueda ocupar la vía sin peligro.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2072,
    pregunta: '¿Qué deberá hacer una persona conductora al iniciar un viraje a la derecha?',
    opciones: ['Acercarse lo más a la izquierda posible', 'Hacerlo desde la pista central', 'Acercarse lo más a la derecha posible'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Para virar a la derecha, debe acercarse lo más posible al costado derecho.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2073,
    pregunta: '¿Qué deberá hacer una persona conductora al iniciar un viraje a la izquierda desde una vía de doble tránsito?',
    opciones: ['Aproximarse al costado derecho del eje o de la línea central de la vía por donde transita', 'Ubicarse al lado izquierdo del eje de la calzada', 'Acercarse lo más a la derecha posible'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Para virar a la izquierda en vía de doble tránsito, debe aproximarse al costado derecho del eje central.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2074,
    pregunta: '¿Cuál es la distancia que debe mantener quien conduce respecto al vehículo de adelante?',
    opciones: ['30 metros', '100 metros', 'Una distancia razonable y prudente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se debe mantener una distancia razonable y prudente respecto al vehículo de adelante.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2075,
    pregunta: 'Para señalizar con el brazo el viraje a la izquierda, se debe colocar:',
    opciones: ['Extendido horizontalmente', 'En ángulo recto hacia arriba', 'Hacia abajo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Para señalizar viraje a la izquierda, el brazo se extiende horizontalmente.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2076,
    pregunta: 'Para señalizar con el brazo la disminución de la velocidad o detención del vehículo, se debe poner:',
    opciones: ['El brazo extendido horizontalmente', 'El brazo en ángulo recto hacia arriba', 'El brazo extendido hacia abajo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Para señalizar detención, el brazo se extiende hacia abajo.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2077,
    pregunta: '¿Cuándo la carga podrá exceder los pesos máximos que las características técnicas del vehículo permitan?',
    opciones: ['Siempre', 'Cuando se pone carga líquida', 'Nunca'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La carga nunca puede exceder los pesos máximos permitidos por las características técnicas del vehículo.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2078,
    pregunta: 'La carga deberá ser estibada y asegurada de manera que:',
    opciones: ['Evite todo riesgo de caída desde el vehículo', 'No se produzcan robos', 'No se deteriore por el sol'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La carga debe estar estibada y asegurada para evitar todo riesgo de caída.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2079,
    pregunta: '¿Cuándo se puede transportar pasajeros en vehículos de carga?',
    opciones: ['Nunca', 'Siempre', 'Solo en casos justificados y adoptando medidas de seguridad adecuadas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se puede transportar pasajeros en vehículos de carga solo en casos justificados con medidas de seguridad.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2080,
    pregunta: '¿Cuándo se podrán transportar cargas peligrosas en vehículos de alquiler o en los destinados al transporte colectivo?',
    opciones: ['Cuando vayan en un envase firme', 'Nunca', 'Solo cuando el vehículo lleve pocas personas a bordo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Nunca se pueden transportar cargas peligrosas en vehículos de alquiler o transporte colectivo.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2081,
    pregunta: 'El color de las luces que proyecten hacia delante los vehículos deben ser:',
    opciones: ['Rojas y blancas', 'Blancas o amarillas', 'Rojas o blancas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las luces delanteras deben ser blancas o amarillas.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2082,
    pregunta: '¿De qué color deben ser las luces de viraje traseras?',
    opciones: ['Blancas', 'Rojas o amarillas', 'Verdes'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las luces de viraje traseras deben ser rojas o amarillas.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2083,
    pregunta: '¿Qué focos o luces se prohíben?',
    opciones: ['Los neblineros', 'Los busca-caminos', 'Todos los que induzcan a error en la conducción'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se prohíben todos los focos o luces que induzcan a error en la conducción.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2084,
    pregunta: '¿Qué tipos de vehículos deben llevar luces amarillas frontales, que indiquen claramente ancho y altura máxima del vehículo?',
    opciones: ['Todos los vehículos', 'Solo los de carga', 'Los vehículos de 2 o más metros de ancho'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de carga deben llevar luces que indiquen su ancho y altura.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2085,
    pregunta: '¿Cuándo se puede hacer uso del aparato sonoro en zona rural?',
    opciones: ['Solo en caso necesario', 'Al llegar a una curva', 'Al entrar a un túnel'],
    respuestaCorrecta: 0,
    explicacionTexto: 'En zona rural, la bocina solo se usa en caso necesario.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2086,
    pregunta: 'Cuando la situación lo requiera, ¿qué luces debe llevar encendidas el vehículo en las vías públicas urbanas?',
    opciones: ['Luces altas', 'Luces bajas', 'Cualquier tipo de luz'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En vías urbanas, se deben llevar luces bajas cuando la situación lo requiera.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2087,
    pregunta: 'Los vehículos que tengan sus neumáticos con las bandas de rodadura desgastadas:',
    opciones: ['Podrán circular solo de noche', 'Podrán circular solo en días despejados', 'No podrán circular'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los vehículos con neumáticos desgastados no deben circular.',
    urlAudio: '',
    categoria: 'Mecánica Básica',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2088,
    pregunta: 'Los vehículos deberán llevar encendidas las luces reglamentarias desde:',
    opciones: ['Media hora antes de la puesta de sol, hasta media hora antes de su salida', 'Media hora después de la puesta de sol, hasta media hora antes de su salida', 'Ninguna de las anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Las luces deben encenderse según lo establecido en la reglamentación vigente.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true
  },
  {
    id: 2089,
    pregunta: 'Cuando circules de noche por caminos y vías rurales con luces encendidas y no te encuentres próximo a ningún otro vehículo, se utilizarán luces:',
    opciones: ['Altas y bajas', 'Altas', 'Bajas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En vías rurales de noche sin vehículos próximos, se usan luces altas.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2090,
    pregunta: '¿Cuántos sistemas de frenos debe tener un vehículo motorizado?',
    opciones: ['A lo menos dos, independientes entre sí', 'Dos, conectados entre sí', 'A lo menos uno'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un vehículo debe tener al menos dos sistemas de frenos independientes entre sí.',
    urlAudio: '',
    categoria: 'Mecánica Básica',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2091,
    pregunta: '¿Qué tipos de luces no se deben usar cuando el vehículo se encuentre en movimiento?',
    opciones: ['De estacionamiento', 'De freno', 'De viraje'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las luces de estacionamiento no se usan con el vehículo en movimiento.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d'],
    oficial: true
  },
  {
    id: 2092,
    pregunta: '¿En qué condiciones debe estar la rueda de repuesto?',
    opciones: ['En buen estado', 'Redibujada', 'Recauchada lisa'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La rueda de repuesto debe estar en buen estado para su uso.',
    urlAudio: '',
    categoria: 'Mecánica Básica',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2093,
    pregunta: 'En general, ¿cómo deben ser los sistemas de freno de un vehículo con remolque, con capacidad de carga superior a 750 kg?',
    opciones: ['Independientes, accionados desde el vehículo tractor', 'Independientes, accionados desde el remolque', 'Ninguna de las anteriores'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los frenos del remolque deben ser independientes, accionados desde el vehículo tractor.',
    urlAudio: '',
    categoria: 'Mecánica Básica',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2094,
    pregunta: 'Si el remolque se desprende del vehículo tractor, ¿cómo deberán accionar los frenos?',
    opciones: ['Manualmente', 'Automáticamente', 'No deberán accionarse'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si el remolque se desprende, los frenos deben accionarse automáticamente.',
    urlAudio: '',
    categoria: 'Mecánica Básica',
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2095,
    pregunta: '¿Qué características deben cumplir los vidrios de seguridad en un vehículo?',
    opciones: ['Permitir relativa visibilidad desde el interior', 'Permitir perfecta visibilidad desde el exterior', 'Permitir perfecta visibilidad desde y hacia el interior del vehículo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los vidrios deben permitir perfecta visibilidad desde y hacia el interior del vehículo.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2096,
    pregunta: '¿En qué parte del túnel se puede hacer uso del aparato sonoro?',
    opciones: ['A la entrada', 'A la salida', 'En ninguna parte'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Solo se puede usar la bocina a la entrada del túnel.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2097,
    pregunta: 'De los siguientes elementos, ¿cuáles deben portarse en los vehículos de locomoción colectiva y de carga?',
    opciones: ['Botiquín y 2 cuñas de seguridad y chaleco reflectante', 'Botiquín, 2 cuñas de seguridad, triángulo reflectante, extintor(es) de incendio y chaleco reflectante', 'Botiquín, 2 cuñas de seguridad, chaleco reflectante y extintor(es) de incendio'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de locomoción colectiva y de carga deben portar botiquín, 2 cuñas, triángulo reflectante, extintor(es) y chaleco reflectante.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2098,
    pregunta: 'La profundidad mínima de las bandas de rodamiento de los neumáticos de taxis debe ser de:',
    opciones: ['3 mm', '2 mm', '1,6 mm'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La profundidad mínima de las bandas de rodamiento de neumáticos de taxis es 1,6 mm.',
    urlAudio: '',
    categoria: 'Mecánica Básica',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2099,
    pregunta: 'En el caso de un servicio de transporte público interurbano de pasajeros, ¿cuánto tiempo como mínimo deben mantenerse los registros del tacógrafo o dispositivo electrónico equivalente?',
    opciones: ['30 días', '60 días', '90 días'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los registros del tacógrafo deben mantenerse un mínimo de 60 días.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2100,
    pregunta: 'El eje de la calzada es:',
    opciones: ['La línea perpendicular a la calzada, demarcada o imaginaria que determina las áreas con sentido de tránsito opuesto', 'La línea longitudinal a la calzada, demarcada o imaginaria que determina las áreas con sentido de tránsito opuesto', 'La línea longitudinal formada por la prolongación de las líneas de edificación'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El eje de la calzada es la línea longitudinal que determina las áreas con sentido de tránsito opuesto.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2101,
    pregunta: 'Adelantamiento es la maniobra efectuada:',
    opciones: ['Por el costado izquierdo del eje de la calzada', 'Por la berma del costado derecho', 'Por el costado derecho del eje de la calzada'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El adelantamiento se efectúa por el costado derecho del eje de la calzada (es decir, por la izquierda del vehículo).',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2102,
    pregunta: 'Estacionar es:',
    opciones: ['Detener momentáneamente un vehículo en la vía pública con o sin la persona que conduce dentro de él', 'Ubicar el vehículo en un lugar determinado', 'Paralizar un vehículo en la vía pública, con o sin la persona que conduce, por un período mayor que el necesario para dejar o recibir pasajeros'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Estacionar es paralizar un vehículo por un período mayor al necesario para dejar o recibir pasajeros.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2103,
    pregunta: 'Cruce regulado es aquel en que existe:',
    opciones: ['Señal PARE o CEDA EL PASO', 'Semáforo intermitente', 'Semáforo funcionando normalmente o Carabinero dirigiendo el tránsito'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un cruce regulado es aquel donde hay un semáforo funcionando o un Carabinero dirigiendo el tránsito.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2104,
    pregunta: 'Intersección es:',
    opciones: ['El área común de calzadas que no se cruzan o divergen', 'El área común de calzadas que se cruzan o convergen', 'Ninguna de las anteriores'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La intersección es el área común de calzadas que se cruzan o convergen.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2105,
    pregunta: 'Derecho preferente de paso es:',
    opciones: ['La prerrogativa de un peatón o quien conduce un vehículo para proseguir su marcha', 'Virar careciendo de preferencia', 'Virar a la izquierda sin detener la marcha'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El derecho preferente de paso es la prerrogativa para proseguir la marcha.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2106,
    pregunta: 'Línea de detención de vehículos es:',
    opciones: ['La línea transversal a la calzada, demarcada o imaginaria, ubicada antes de un paso para peatones o de una intersección', 'El paso de cebra', 'La línea imaginaria, ubicada a menos de un metro después del paso de peatones'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La línea de detención es transversal a la calzada, ubicada antes de un paso peatonal o intersección.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2107,
    pregunta: 'Paso de peatones es:',
    opciones: ['La senda de seguridad formada por la prolongación imaginaria o demarcada de la calzada', 'La senda formada por la prolongación de las líneas de detención', 'La senda de seguridad en la calzada señalizada conforme al reglamento'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El paso de peatones es la senda de seguridad en la calzada señalizada conforme al reglamento.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2108,
    pregunta: 'Sobrepasar es:',
    opciones: ['Situarse detrás de otro vehículo sobrepasando el eje de la calzada', 'Pasar por otro u otros vehículos en el mismo sentido, sin traspasar el eje de la calzada', 'Situarse delante de otro vehículo, traspasando el eje de la calzada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Sobrepasar es pasar a otro vehículo en el mismo sentido sin traspasar el eje de la calzada.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2109,
    pregunta: 'En un cruce no regulado, ¿qué vehículo deberá ceder el derecho preferente de paso?',
    opciones: ['El que llega primero al cruce', 'El de la derecha con respecto al que se acerque por la izquierda', 'El de la izquierda con respecto al que se acerque por la derecha'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En un cruce no regulado, cede el paso el vehículo que viene por la izquierda.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2110,
    pregunta: 'Una persona que conduce, al enfrentar un signo "PARE", deberá:',
    opciones: ['Proseguir su marcha', 'Detenerse', 'Encender luces altas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al enfrentar un signo PARE, debe detenerse completamente.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2111,
    pregunta: 'Una persona que conduce, al enfrentar un signo "CEDA EL PASO", deberá:',
    opciones: ['Detenerse siempre', 'Seguir a la misma velocidad', 'Reducir la velocidad y detenerse si fuese necesario'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al enfrentar CEDA EL PASO, debe reducir la velocidad y detenerse si es necesario.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2112,
    pregunta: 'Un vehículo que se incorpore a la circulación desde un garage particular, carece del derecho preferente de paso:',
    opciones: ['Cuando el vehículo es un camión', 'Siempre', 'Ninguna de las anteriores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un vehículo que sale de un garage particular SIEMPRE carece de derecho preferente de paso.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2113,
    pregunta: 'Cuando se aproxima un vehículo de emergencia haciendo uso de sus señales audibles y visibles en el mismo sentido, quien conduce deberá:',
    opciones: ['Acelerar y circular delante del vehículo de emergencia', 'Frenar bruscamente', 'Conducir el vehículo lo más a la izquierda o a la derecha posible, con el objeto de despejar la vía'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Ante un vehículo de emergencia, debe despejar la vía moviéndose a un costado.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2114,
    pregunta: 'Por regla general, los vehículos deberán estacionarse:',
    opciones: ['A la derecha de la calzada', 'Al centro de la calzada', 'A la izquierda de la calzada'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Por regla general, los vehículos se estacionan a la derecha de la calzada.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2115,
    pregunta: 'Solo se podrá estacionar al lado izquierdo de la calzada cuando:',
    opciones: ['La señalización lo permita', 'No hayan Carabineros en el lugar', 'Ninguna de las anteriores'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Solo se puede estacionar al lado izquierdo cuando la señalización lo permite.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_e'],
    oficial: true
  },
  {
    id: 2116,
    pregunta: 'En la carretera, los vehículos deberán estacionarse:',
    opciones: ['Con la mitad derecha sobre la berma', 'Solo con la parte de atrás sobre la calzada', 'Con toda su estructura sobre la berma'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En carretera, el vehículo debe estacionarse con toda su estructura sobre la berma.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2117,
    pregunta: '¿Cuál es la distancia máxima a la que deben estacionarse los vehículos de la cuneta?',
    opciones: ['20 cm', '60 cm', '30 cm'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los vehículos deben estacionarse a un máximo de 30 cm de la cuneta.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2118,
    pregunta: '¿Qué deberá hacer quien conduce al estacionar un vehículo motorizado?',
    opciones: ['Detener el motor del vehículo', 'Frenarlo y detener el motor', 'Frenar el vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al estacionar, se debe frenar el vehículo y detener el motor.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2119,
    pregunta: 'La distancia mínima entre un vehículo y otro al estacionarse debe ser de:',
    opciones: ['50 cm', '60 cm', '30 cm'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La distancia mínima entre vehículos estacionados es de 60 cm.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2120,
    pregunta: '¿A cuántos metros de un grifo para incendio y de un cuartel de bombas se puede estacionar un vehículo?',
    opciones: ['A menos de 6 metros y 5 metros, respectivamente', 'A más de un metro y 3 metros, respectivamente', 'A más de 5 metros y 10 metros, respectivamente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Se puede estacionar a más de 5 metros de un grifo y a más de 10 metros de un cuartel de bombas.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2121,
    pregunta: '¿A cuántos metros de un cruce ferroviario a nivel se puede estacionar?',
    opciones: ['A más de 5 metros', 'A más de 20 metros', 'A menos de 20 metros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se debe estacionar a más de 20 metros de un cruce ferroviario a nivel.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2122,
    pregunta: '¿A cuántos metros de una esquina y de un signo PARE o CEDA EL PASO se puede estacionar un vehículo motorizado?',
    opciones: ['A más de 10 metros, en ambos casos', 'A menos de 10 a 5 metros, respectivamente', 'A más de 5 y 10 metros, respectivamente'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Se debe estacionar a más de 10 metros de una esquina y de un signo PARE o CEDA EL PASO.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2123,
    pregunta: '¿Bajo qué condiciones un estacionamiento reservado puede ser ocupado por cualquier vehículo?',
    opciones: ['Siempre que sea el mismo tipo de vehículo', 'Nunca, está totalmente prohibido', 'Siempre que quien conduce el vehículo permanezca en él y lo retire cuando llegue el vehículo que goce de la reserva'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Un estacionamiento reservado puede ser ocupado si el conductor permanece y lo retira cuando llegue el vehículo con reserva.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2124,
    pregunta: '¿Cómo se deberá estacionar un vehículo cuando la vía es en subida?',
    opciones: ['Con las ruedas delanteras hacia la cuneta', 'Con las ruedas traseras hacia la calzada', 'Con las ruedas delanteras hacia la calzada'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En subida, las ruedas delanteras deben apuntar hacia la calzada para que el vehículo no ruede.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2125,
    pregunta: 'En un siniestro, el solo hecho de la infracción no determina:',
    opciones: ['La gravedad del siniestro', 'La responsabilidad civil de la persona infractora', 'Ninguna de las anteriores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El solo hecho de la infracción no determina necesariamente la responsabilidad civil.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2126,
    pregunta: 'En caso de siniestro, no prestar atención a las condiciones del tránsito, constituye:',
    opciones: ['Presunción de responsabilidad de quien conduce', 'Causal de cancelación de licencia', 'Ninguna de las anteriores'],
    respuestaCorrecta: 0,
    explicacionTexto: 'No prestar atención al tránsito constituye presunción de responsabilidad del conductor.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_e'],
    oficial: true
  },
  {
    id: 2127,
    pregunta: 'Se presumirá culpabilidad del peatón cuando pase por:',
    opciones: ['Delante de un vehículo detenido habiendo tránsito libre en la vía respectiva', 'Detrás del vehículo en movimiento', 'Ninguna de las anteriores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se presume culpabilidad del peatón que pase detrás de un vehículo en movimiento.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2128,
    pregunta: 'En todo siniestro en que se produzcan daños, quien o quienes participantes estarán obligados a:',
    opciones: ['Huir del sitio del suceso', 'Dar cuenta a la autoridad policial más próxima', 'Llamar al servicio de ambulancias'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En todo siniestro con daños, los participantes deben dar cuenta a la autoridad policial.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2129,
    pregunta: 'Se presumirá culpabilidad del peatón que cruce la calzada en:',
    opciones: ['El paso de cebra', 'Paso de peatones', 'Lugar prohibido'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Se presume culpabilidad del peatón que cruce en lugar prohibido.',
    urlAudio: '',
    categoria: 'Ley de Tránsito',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2130,
    pregunta: 'La luz verde del semáforo indica:',
    opciones: ['Prevención', 'Precaución', 'Paso'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La luz verde del semáforo indica paso.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2131,
    pregunta: 'La luz amarilla del semáforo indica:',
    opciones: ['Prevención', 'Paso', 'Detenerse'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La luz amarilla del semáforo indica prevención.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2132,
    pregunta: '¿Qué indica la luz roja del semáforo?',
    opciones: ['Detención', 'Precaución', 'Paso'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La luz roja del semáforo indica detención.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2133,
    pregunta: '¿Qué condiciones debe tener el cruce para que el vehículo continúe su marcha, no obstante tenga luz verde al frente?',
    opciones: ['Debe existir previamente luz amarilla', 'Debe existir espacio suficiente para no bloquear el cruce', 'No tener el paso de cebra demarcado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Aunque tenga luz verde, debe existir espacio suficiente para no bloquear el cruce.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2134,
    pregunta: 'Los vehículos que enfrenten un semáforo con luz roja y flecha verde, podrán:',
    opciones: ['Entrar cuidadosamente al cruce solo para seguir en la dirección indicada en la flecha verde', 'Entrar cuidadosamente al cruce para continuar directo', 'Ninguna de las anteriores'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Con luz roja y flecha verde, solo se puede seguir en la dirección de la flecha.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2135,
    pregunta: 'La luz roja intermitente del semáforo indica:',
    opciones: ['Precaución', 'Prevención', 'Ceda el paso'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La luz roja intermitente indica que se debe ceder el paso.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2136,
    pregunta: 'La luz amarilla intermitente del semáforo indica:',
    opciones: ['PARE', 'Peligro', 'Ceda el paso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La luz amarilla intermitente indica peligro.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2137,
    pregunta: 'Indica qué significan estas señales: Pare, Zona de curvas a la derecha, Proximidad rotonda.',
    opciones: ['Pare, Pavimento resbaladizo, Curva muy cerrada a la derecha', 'Pare, Zona de curvas a la derecha, Proximidad rotonda', 'Pare, Zona de curvas a la izquierda, Proximidad rotonda'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Las señales corresponden a Pare, Zona de curvas a la izquierda y Proximidad rotonda.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2138,
    pregunta: 'Indica qué significan estas señales: Ceda el paso, Curva a la derecha, No virar en U.',
    opciones: ['Ceda el paso, Salida de Autopista, Prohibido transitar en sentido contrario', 'Ceda el paso, Curva a la derecha, No virar en U', 'Fin Restricción, Permitido Virar, No virar en U'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las señales son: Ceda el paso, Curva a la derecha y No virar en U.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2139,
    pregunta: 'Indica qué significan estas señales: No entrar, Prohibido Estacionar y detenerse, Resalto.',
    opciones: ['No entrar, Prohibido Estacionar, Resalto', 'No entrar, Prohibido Estacionar y detenerse, Pendiente fuerte', 'Tránsito en sentido contrario, Prohibido detenerse, Resalto'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las señales corresponden a No entrar, Prohibido Estacionar y Resalto.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2140,
    pregunta: 'Indica qué significan estas señales: Mantenga su derecha, Silencio, Velocidad máxima.',
    opciones: ['Mantenga su derecha, Silencio, Velocidad sugerida', 'Pista Solo autos, No Molestar, Velocidad mínima', 'Mantenga su derecha, Silencio, Velocidad máxima'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las señales son: Pista Solo autos, No Molestar y Velocidad mínima.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2141,
    pregunta: 'Indica qué significan estas señales: Dirección Obligada, Puente angosto, Zona de Escuela.',
    opciones: ['Viraje a la derecha, Camino angosto, Niños jugando', 'Dirección Obligada, Puente angosto, Zona de Escuela', 'Dirección Obligada, Camino angosto, Zona de Peatones'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Las señales son: Dirección Obligada, Camino angosto y Zona de Peatones.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2142,
    pregunta: 'Indica qué significan estas señales: Cruce ferroviario a nivel sin barreras, No Adelantar, Ancho máximo.',
    opciones: ['Cruce ferroviario a nivel sin barreras, No Adelantar, Ancho máximo', 'Cruce ferroviario a nivel con barreras, Prohibido circular vehículos, Ancho máximo', 'Cruce ferroviario a nivel sin barreras, Fin doble vía, Peso máximo'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las señales son: Cruce ferroviario sin barreras, No Adelantar y Ancho máximo.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2143,
    pregunta: 'Indica qué significan estas señales: Pavimento resbaladizo, Proximidad Cruce, Prohibido estacionar y detenerse.',
    opciones: ['Pavimento resbaladizo, Proximidad Cruce, Prohibido estacionar', 'Proyección de gravilla, Proximidad Iglesia, Prohibido estacionar y detenerse', 'Pavimento resbaladizo, Proximidad Cruce, Prohibido estacionar y detenerse'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Las señales son: Pavimento resbaladizo, Proximidad Cruce y Prohibido estacionar y detenerse.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2144,
    pregunta: 'Indica qué significan estas señales: No virar izquierda, Proximidad señal "Ceda el Paso", Resalto.',
    opciones: ['No virar izquierda, Proximidad de señal "Ceda el Paso", Badén', 'No Entrar, Ceda el Paso, Proximidad Puente', 'No virar izquierda, Proximidad señal "Ceda el Paso", Resalto'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las señales son: No virar izquierda, Proximidad de señal Ceda el Paso y Badén.',
    urlAudio: '',
    categoria: 'Señalización',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2145,
    pregunta: 'Debe considerarse como velocidad razonable y prudente la que contemple:',
    opciones: ['La temperatura ambiente', 'Solo el estado del camino', 'Los riesgos y peligros presentes y posibles'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad razonable y prudente debe contemplar los riesgos y peligros presentes y posibles.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2146,
    pregunta: 'Velocidad razonable y prudente significa:',
    opciones: ['La máxima permitida en la vía', 'Una velocidad que permita controlar el vehículo cuando sea necesario, para evitar siniestros', '30 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Velocidad razonable y prudente es la que permite controlar el vehículo para evitar siniestros.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2147,
    pregunta: 'La velocidad más baja a la que se puede circular es:',
    opciones: ['La que decida quien conduce', '20 km/h', 'La que no impida el desplazamiento normal y adecuado de los demás vehículos'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad mínima es la que no impida el desplazamiento normal de los demás vehículos.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2148,
    pregunta: 'La velocidad máxima de un bus interurbano en una autopista es:',
    opciones: ['100 km/h', '120 km/h', '90 km/h'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La velocidad máxima de un bus interurbano en autopista es 100 km/h.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2149,
    pregunta: '¿Cuál de las siguientes sería la mejor recomendación para una persona conductora que ha ingerido bebidas alcohólicas?',
    opciones: ['Que no conduzca', 'Que espere un rato antes de volver a conducir', 'Que conduzca lenta y muy cuidadosamente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La mejor recomendación es que NO conduzca.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2150,
    pregunta: 'La velocidad máxima permitida en zonas urbanas para vehículos de carga de peso bruto mayor a 3860 kg, de transporte escolar y buses es:',
    opciones: ['70 km/h', '60 km/h', '50 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La velocidad máxima en zona urbana para estos vehículos es 50 km/h.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
    oficial: true
  },
  {
    id: 2151,
    pregunta: '¿Qué aspectos de una persona conductora se ven afectados si ésta consume una pequeña dosis de alcohol?',
    opciones: ['Su capacidad motora y su capacidad de reacción', 'Su capacidad de reacción y su capacidad para percibir el riesgo', 'Su capacidad motora, su capacidad de reacción y su capacidad para percibir el riesgo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El alcohol afecta la capacidad motora, de reacción y de percepción del riesgo, incluso en dosis pequeñas.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2152,
    pregunta: 'En el caso de camión de más de 4.000 kg, la velocidad máxima permitida en una carretera es:',
    opciones: ['110 km/h', '100 km/h', '90 km/h'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Para camiones de más de 4.000 kg, la velocidad máxima en carretera es 90 km/h.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'dificil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2153,
    pregunta: '¿En qué medida se ve afectado el tiempo de reacción de una persona conductora por la ingesta de alcohol?',
    opciones: ['Aumenta, debido a que la comunicación en el sistema nervioso se hace más lenta', 'Disminuye, debido a que la comunicación en el sistema nervioso se acelera', 'De ninguna manera, dado que el alcohol no afecta al tiempo de reacción'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El alcohol aumenta el tiempo de reacción porque hace más lenta la comunicación del sistema nervioso.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'media',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
  {
    id: 2154,
    pregunta: 'El consumo de bebidas alcohólicas, incluso en cantidades pequeñas, ¿qué efectos produce?',
    opciones: ['Mejora la precisión y la coordinación', 'Reduce la percepción del entorno', 'Agudiza los reflejos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El alcohol, incluso en cantidades pequeñas, reduce la percepción del entorno.',
    urlAudio: '',
    categoria: 'Conducción Segura',
    dificultad: 'facil',
    licenseTypes: ['clase_a2', 'clase_d', 'clase_e'],
    oficial: true
  },
];
