import { ImageSourcePropType } from 'react-native';

export interface QuestionVisual {
  type: 'image';
  source: ImageSourcePropType;
}

const IMG = {
  interseccionGiro: require('../assets/images/questions/interseccion-giro.png'),
  senalPare: require('../assets/images/questions/senal-pare.png'),
  velocidadUrbana: require('../assets/images/questions/velocidad-urbana.png'),
  crucePeatonal: require('../assets/images/questions/cruce-peatonal.png'),
  semaforoRojo: require('../assets/images/questions/semaforo-rojo.png'),
  adelantamiento: require('../assets/images/questions/adelantamiento.png'),
  autopista: require('../assets/images/questions/autopista.png'),
  estacionamiento: require('../assets/images/questions/estacionamiento.png'),
  lluvia: require('../assets/images/questions/lluvia.png'),
  conduccionNocturna: require('../assets/images/questions/conduccion-nocturna.png'),
  rotonda: require('../assets/images/questions/rotonda.png'),
  zonaEscolar: require('../assets/images/questions/zona-escolar.png'),
  cruceFerroviario: require('../assets/images/questions/cruce-ferroviario.png'),
  zonaObras: require('../assets/images/questions/zona-obras.png'),
  tablero: require('../assets/images/questions/tablero.png'),
  neumaticos: require('../assets/images/questions/neumaticos.png'),
  trianguloEmergencia: require('../assets/images/questions/triangulo-emergencia.png'),
  cinturon: require('../assets/images/questions/cinturon.png'),
  espejos: require('../assets/images/questions/espejos.png'),
  primerosAuxilios: require('../assets/images/questions/primeros-auxilios.png'),
  cedaPaso: require('../assets/images/questions/ceda-paso.png'),
  motor: require('../assets/images/questions/motor.png'),
  distanciaSegura: require('../assets/images/questions/distancia-segura.png'),
  niebla: require('../assets/images/questions/niebla.png'),
  alcohol: require('../assets/images/questions/alcohol.png'),
  accidente: require('../assets/images/questions/accidente.png'),
  cambioCarril: require('../assets/images/questions/cambio-carril.png'),
  noEstacionar: require('../assets/images/questions/no-estacionar.png'),
  luces: require('../assets/images/questions/luces.png'),
  medioAmbiente: require('../assets/images/questions/medio-ambiente.png'),
  curva: require('../assets/images/questions/curva.png'),
  vehiculoEmergencia: require('../assets/images/questions/vehiculo-emergencia.png'),
  ciclista: require('../assets/images/questions/ciclista.png'),
  volante: require('../assets/images/questions/volante.png'),
  frenos: require('../assets/images/questions/frenos.png'),
  licencia: require('../assets/images/questions/licencia.png'),
  extintor: require('../assets/images/questions/extintor.png'),
  bateria: require('../assets/images/questions/bateria.png'),
  senalesTipos: require('../assets/images/questions/senales-tipos.png'),
  gasolinera: require('../assets/images/questions/gasolinera.png'),
  celular: require('../assets/images/questions/celular.png'),
  sillaInfantil: require('../assets/images/questions/silla-infantil.png'),
  tunel: require('../assets/images/questions/tunel.png'),
  airbag: require('../assets/images/questions/airbag.png'),
  demarcacion: require('../assets/images/questions/demarcacion.png'),
  bus: require('../assets/images/questions/bus.png'),
  motocicleta: require('../assets/images/questions/motocicleta.png'),
  fatiga: require('../assets/images/questions/fatiga.png'),
  mantenimiento: require('../assets/images/questions/mantenimiento.png'),
  vehiculoElectrico: require('../assets/images/questions/vehiculo-electrico.png'),
  puntoCiego: require('../assets/images/questions/punto-ciego.png'),
  viento: require('../assets/images/questions/viento.png'),
  mascotaVehiculo: require('../assets/images/questions/mascota-vehiculo.png'),
  fotoradar: require('../assets/images/questions/fotoradar.png'),
  tagPeaje: require('../assets/images/questions/tag-peaje.png'),
  heimlich: require('../assets/images/questions/heimlich.png'),
  desfibrilador: require('../assets/images/questions/desfibrilador.png'),
  posturaConductor: require('../assets/images/questions/postura-conductor.png'),
  conduccionDefensiva: require('../assets/images/questions/conduccion-defensiva.png'),
  senalesPreventivas: require('../assets/images/questions/senales-preventivas.png'),
  auriculares: require('../assets/images/questions/auriculares.png'),
  tachasReflectantes: require('../assets/images/questions/tachas-reflectantes.png'),
  senalero: require('../assets/images/questions/senalero.png'),
  pasajeros: require('../assets/images/questions/pasajeros.png'),
  direccionAsistida: require('../assets/images/questions/direccion-asistida.png'),
  espEstabilidad: require('../assets/images/questions/esp-estabilidad.png'),
  medicamentos: require('../assets/images/questions/medicamentos.png'),
  visionConduccion: require('../assets/images/questions/vision-conduccion.png'),
};

const KEYWORD_IMAGES: Array<{ kw: string[]; img: ImageSourcePropType }> = [
  { kw: ['pare', 'señal pare', 'octagonal roja', 'octogonal', 'detenerse completamente'], img: IMG.senalPare },
  { kw: ['ceda el paso', 'triángulo invertido', 'ceda paso', 'ceder el paso'], img: IMG.cedaPaso },
  { kw: ['30 km', '30km', '40 km', '40km', '50 km', '50km', '60 km', '60km', '80 km', '80km', '100 km', '100km', '120 km', '120km', 'velocidad máxima', 'límite de velocidad', 'exceso de velocidad'], img: IMG.velocidadUrbana },
  { kw: ['zona urbana'], img: IMG.velocidadUrbana },
  { kw: ['no adelantar', 'prohibido adelantar', 'prohibido sobrepasar', 'adelantar', 'adelantamiento', 'sobrepasar', 'rebasar'], img: IMG.adelantamiento },
  { kw: ['no girar', 'prohibido girar', 'no virar', 'gire derecha', 'solo derecha', 'gire izquierda', 'solo izquierda', 'dirección obligatoria'], img: IMG.interseccionGiro },
  { kw: ['dirección prohibida', 'prohibido el tránsito', 'acceso prohibido', 'no entrar'], img: IMG.senalPare },
  { kw: ['curva', 'curvas', 'curva peligrosa', 'doble curva'], img: IMG.curva },
  { kw: ['rotonda', 'glorieta', 'redondel'], img: IMG.rotonda },
  { kw: ['pendiente', 'bajada', 'cuesta abajo', 'cuesta arriba'], img: IMG.curva },
  { kw: ['doble sentido', 'doble vía', 'ambos sentidos', 'flechas encontradas'], img: IMG.cambioCarril },
  { kw: ['semáforo', 'semaforo', 'señal luminosa', 'luz de tránsito', 'luz roja', 'luz verde', 'luz amarilla', 'ámbar'], img: IMG.semaforoRojo },
  { kw: ['cruce peatonal', 'paso peatonal', 'paso de cebra', 'cruce de peatones', 'peatón', 'peatones', 'peatonal'], img: IMG.crucePeatonal },
  { kw: ['zona escolar', 'escuela', 'niños cruzando', 'zona de niños', 'niños', 'colegio', 'transporte escolar'], img: IMG.zonaEscolar },
  { kw: ['cruce ferroviario', 'paso a nivel', 'ferrocarril', 'vías del tren', 'tren', 'ff.cc.'], img: IMG.cruceFerroviario },
  { kw: ['badén', 'baden', 'lomada', 'resalto', 'reductor de velocidad', 'lomo de toro'], img: IMG.curva },
  { kw: ['estacionamiento prohibido', 'no estacionar', 'prohibido estacionar', '"e" tachada'], img: IMG.noEstacionar },
  { kw: ['estacionar', 'estacionamiento', 'aparcar'], img: IMG.estacionamiento },
  { kw: ['autopista', 'autoexpreso', 'vía rápida', 'carretera'], img: IMG.autopista },
  { kw: ['animales', 'ganado', 'animal en la vía'], img: IMG.curva },
  { kw: ['obras', 'trabajo vial', 'trabajadores', 'zona de trabajo', 'construcción', 'fondo anaranjado'], img: IMG.zonaObras },
  { kw: ['hospital', 'centro de salud', 'clínica'], img: IMG.vehiculoEmergencia },
  { kw: ['gasolinera', 'estación de servicio', 'bencinera', 'combustible', 'gasolina', 'bencina'], img: IMG.gasolinera },
  { kw: ['bicicleta', 'ciclista', 'ciclovía'], img: IMG.ciclista },
  { kw: ['calle sin salida', 'sin salida'], img: IMG.senalesTipos },
  { kw: ['virar en u', 'giro en u', 'vuelta en u'], img: IMG.interseccionGiro },

  { kw: ['teléfono celular', 'telefono celular', 'celular mientras', 'teléfono móvil', 'uso del celular', 'hablar por teléfono', 'manos libres'], img: IMG.celular },
  { kw: ['audífonos', 'auriculares', 'conducir con audífonos'], img: IMG.auriculares },
  { kw: ['retención infantil', 'silla infantil', 'silla de niño', 'silla para niño', 'asiento infantil', 'menor de 12 años', 'asiento delantero'], img: IMG.sillaInfantil },
  { kw: ['señalero', 'luz intermitente', 'intermitente', 'indicador de viraje'], img: IMG.senalero },
  { kw: ['cuántas personas', 'pasajeros', 'personas pueden viajar', 'capacidad del vehículo', 'ocupantes'], img: IMG.pasajeros },
  { kw: ['túnel', 'tunel'], img: IMG.tunel },
  { kw: ['airbag', 'bolsa de aire', 'air bag', 'colisiones laterales'], img: IMG.airbag },
  { kw: ['punto ciego', 'puntos ciegos', 'ángulo muerto'], img: IMG.puntoCiego },
  { kw: ['viento', 'viento fuerte', 'viento lateral', 'ráfaga'], img: IMG.viento },
  { kw: ['perro', 'mascota', 'animal doméstico', 'transportarse un perro'], img: IMG.mascotaVehiculo },
  { kw: ['fotorradar', 'fotoradar', 'foto radar', 'cámara de velocidad'], img: IMG.fotoradar },
  { kw: ['tag', 'peaje', 'telepeaje'], img: IMG.tagPeaje },
  { kw: ['motocicleta', 'moto ', 'motoneta', 'clase b conducir una moto'], img: IMG.motocicleta },
  { kw: ['bus', 'transporte público', 'paradero', 'vías exclusivas'], img: IMG.bus },

  { kw: ['línea continua amarilla', 'línea continua', 'doble línea continua', 'línea segmentada', 'línea continua blanca', 'demarcación', 'líneas diagonales'], img: IMG.demarcacion },
  { kw: ['tachas reflectantes', 'tachas', 'reflectantes en el pavimento', 'cat eye'], img: IMG.tachasReflectantes },
  { kw: ['lento', 'pintada en el pavimento', 'palabra en el pavimento'], img: IMG.demarcacion },
  { kw: ['fondo café', 'señal con fondo café', 'carpa', 'mirador', 'turístic'], img: IMG.senalesTipos },
  { kw: ['circular azul', 'circular roja con', 'rectangular azul', 'rectangular blanca', 'sentido único', 'flecha blanca'], img: IMG.senalesTipos },
  { kw: ['cadenas para nieve', 'nieve'], img: IMG.lluvia },
  { kw: ['confirmación de ruta'], img: IMG.senalesTipos },
  { kw: ['flechas horizontales', 'flechas verticales', 'dos flechas'], img: IMG.senalesTipos },
  { kw: ['manga de viento'], img: IMG.viento },
  { kw: ['resbaladizo', 'camino resbaladizo', 'derrapar', 'derrape', 'derrapando', 'auto derrapando'], img: IMG.senalesPreventivas },
  { kw: ['estrechamiento', 'angostamiento'], img: IMG.senalesPreventivas },
  { kw: ['señal triangular', 'silueta de un animal', 'piedras cayendo', 'derrumbe'], img: IMG.senalesPreventivas },
  { kw: ['señal naranja', 'figura de un trabajador', 'flecha diagonal'], img: IMG.zonaObras },
  { kw: ['tachón reflectante', 'color de tachón'], img: IMG.tachasReflectantes },
  { kw: ['señal verde', 'salida', 'nombres de ciudades', 'distancias en kilómetros', 'sos'], img: IMG.senalesTipos },
  { kw: ['señal azul con una h', 'símbolo de cubiertos', 'tenedor y cuchillo', 'símbolo de una cama', 'llave inglesa', 'símbolo de un teléfono'], img: IMG.senalesTipos },
  { kw: ['panel complementario', 'con metros'], img: IMG.senalesTipos },
  { kw: ['autos enfrentados', 'avión', 'puente levadizo', 'muelle', 'ribera', 'zigzag', 'camino de tierra', 'no pavimentado'], img: IMG.senalesPreventivas },
  { kw: ['letra p blanca', 'letra p'], img: IMG.estacionamiento },
  { kw: ['línea discontinua', 'línea segmentada', 'discontinua'], img: IMG.demarcacion },
  { kw: ['flechas pintadas', 'flechas en el pavimento'], img: IMG.demarcacion },
  { kw: ['zigzag amarillas', 'líneas en zigzag'], img: IMG.demarcacion },
  { kw: ['altura máxima', 'ancho máximo'], img: IMG.senalesTipos },

  { kw: ['cinturón', 'cinturon', 'cinturón de seguridad', 'abrocharse', 'abrochar'], img: IMG.cinturon },
  { kw: ['casco', 'casco protector'], img: IMG.cinturon },
  { kw: ['espejo', 'espejos', 'retrovisor', 'retrovisores'], img: IMG.espejos },
  { kw: ['volante', 'manos al volante'], img: IMG.volante },
  { kw: ['luces', 'focos', 'faros', 'luces altas', 'luces bajas', 'luces de cruce', 'luces largas', 'luces cortas', 'encender luces', 'iluminación'], img: IMG.luces },
  { kw: ['neumático', 'neumatico', 'neumáticos', 'llanta', 'llantas', 'rueda', 'presión de los neumáticos', 'banda de rodadura'], img: IMG.neumaticos },
  { kw: ['freno', 'frenos', 'frenado', 'frenar', 'freno de mano', 'distancia de frenado', 'abs', 'sistema de frenos', 'líquido de frenos', 'pastillas', 'frenada regenerativa'], img: IMG.frenos },
  { kw: ['motor', 'encender el motor', 'apagar el motor', 'revoluciones', 'arranque'], img: IMG.motor },
  { kw: ['aceite', 'lubricante', 'lubricación', 'nivel de aceite'], img: IMG.motor },
  { kw: ['batería', 'bateria', 'alternador'], img: IMG.bateria },
  { kw: ['temperatura', 'sobrecalentamiento', 'recalentamiento', 'refrigerante', 'termómetro', 'radiador', 'sistema de refrigeración', 'enfriamiento'], img: IMG.tablero },
  { kw: ['embrague', 'clutch', 'pedal de embrague'], img: IMG.motor },
  { kw: ['transmisión', 'caja de cambios', 'cambio de marcha', 'engranaje', 'marcha'], img: IMG.motor },
  { kw: ['suspensión', 'amortiguador', 'amortiguadores'], img: IMG.motor },
  { kw: ['tablero', 'indicador', 'instrumento', 'testigo', 'luz de advertencia', 'panel de control'], img: IMG.tablero },
  { kw: ['dirección asistida', 'dirección hidráulica', 'power steering', 'servo dirección', 'servodirección', 'dirección del vehículo', 'dirección se siente'], img: IMG.direccionAsistida },
  { kw: ['esp', 'control de estabilidad', 'estabilidad electrónic', 'tracción'], img: IMG.espEstabilidad },
  { kw: ['limpiaparabrisas', 'parabrisas', 'plumillas'], img: IMG.mantenimiento },
  { kw: ['viaje largo', 'verificar antes', 'revisión del vehículo', 'inspección vehicular', 'mantener siempre limpios'], img: IMG.mantenimiento },
  { kw: ['inyección electrónica', 'inyección', 'intercooler', 'turbo'], img: IMG.motor },
  { kw: ['caja automática', 'automático'], img: IMG.motor },
  { kw: ['diferencial'], img: IMG.motor },
  { kw: ['filtro de aire', 'filtro de habitáculo', 'filtro'], img: IMG.mantenimiento },
  { kw: ['correa de distribución', 'correa'], img: IMG.motor },
  { kw: ['cámara de retroceso', 'sensor de retroceso'], img: IMG.espejos },
  { kw: ['start/stop', 'start stop'], img: IMG.motor },
  { kw: ['olor a huevos', 'olor extraño', 'olor'], img: IMG.tablero },
  { kw: ['remolcar', 'remolque'], img: IMG.autopista },
  { kw: ['zapatos', 'calzado'], img: IMG.volante },
  { kw: ['se desvía', 'desvía hacia'], img: IMG.frenos },

  { kw: ['alcohol', 'alcoholemia', 'ebriedad', 'estado de ebriedad', 'ley emilia', 'tolerancia cero', 'conducir ebrio', 'alcotest', 'alcoholímetro', 'bajo los efectos de drogas', 'narcotest'], img: IMG.alcohol },
  { kw: ['licencia', 'licencia de conducir', 'permiso de conducir', 'renovar licencia', 'clase b'], img: IMG.licencia },
  { kw: ['multa', 'infracción', 'sanción', 'parte', 'penalización', 'infracciones gravísimas', 'categorías de infracciones'], img: IMG.licencia },
  { kw: ['accidente', 'colisión', 'choque', 'siniestro', 'volcamiento', 'atropello'], img: IMG.accidente },
  { kw: ['distancia de seguimiento', 'distancia prudente', 'distancia segura', 'metros de distancia', 'distancia entre vehículos', '2 segundos', 'tres segundos', 'dos segundos', '3 segundos', 'regla de los 3'], img: IMG.distanciaSegura },
  { kw: ['intersección', 'cruce de calles', 'cruce', 'preferencia de paso', 'derecho de vía', 'prioridad'], img: IMG.interseccionGiro },
  { kw: ['lluvia', 'piso mojado', 'superficie mojada', 'mojado', 'aquaplaning', 'hidroplaneo'], img: IMG.lluvia },
  { kw: ['niebla', 'neblina', 'visibilidad reducida', 'poca visibilidad'], img: IMG.niebla },
  { kw: ['noche', 'nocturna', 'oscuridad', 'conducir de noche', 'deslumbramiento'], img: IMG.conduccionNocturna },
  { kw: ['carga', 'camión', 'transporte de carga', 'peso máximo', 'sobrecarga', 'remolque', 'camioneta'], img: IMG.autopista },
  { kw: ['documentos', 'documentación', 'revisión técnica', 'permiso de circulación', 'seguro obligatorio', 'soap', 'homologación vehicular', 'certificado'], img: IMG.licencia },
  { kw: ['viraje', 'girar', 'doblar', 'cambio de pista', 'cambio de carril', 'señalizar', 'incorporarse'], img: IMG.cambioCarril },
  { kw: ['retroceder', 'reversa', 'marcha atrás'], img: IMG.estacionamiento },
  { kw: ['carril', 'pista'], img: IMG.cambioCarril },
  { kw: ['vehículo de emergencia', 'sirena', 'paso de emergencia', 'ambulancia', 'bomberos', 'carabineros'], img: IMG.vehiculoEmergencia },
  { kw: ['vidrios polarizados', 'vidrios oscuros', 'polarizado'], img: IMG.mantenimiento },
  { kw: ['conducir descalzo', 'descalzo'], img: IMG.volante },
  { kw: ['convivencia vial', 'jerarquía de usuarios'], img: IMG.crucePeatonal },
  { kw: ['tránsito calmado', 'zona 30'], img: IMG.velocidadUrbana },
  { kw: ['cortejo fúnebre', 'fúnebre'], img: IMG.distanciaSegura },
  { kw: ['consumir alimentos', 'comer mientras', 'comida mientras'], img: IMG.celular },
  { kw: ['conducción temeraria', 'temeraria'], img: IMG.accidente },
  { kw: ['panne', 'avería', 'descompuesto'], img: IMG.trianguloEmergencia },
  { kw: ['vehículos de colección', 'históricos'], img: IMG.licencia },

  { kw: ['primeros auxilios', 'primer auxilio', 'socorrer', 'socorro', 'auxilio'], img: IMG.primerosAuxilios },
  { kw: ['rcp', 'reanimación', 'respiración artificial', 'resucitación', 'masaje cardíaco', 'paro cardíaco'], img: IMG.primerosAuxilios },
  { kw: ['hemorragia', 'sangrado', 'sangre', 'torniquete'], img: IMG.primerosAuxilios },
  { kw: ['fractura', 'hueso roto', 'inmovilizar', 'férula', 'esguince', 'luxación'], img: IMG.primerosAuxilios },
  { kw: ['quemadura', 'quemado'], img: IMG.primerosAuxilios },
  { kw: ['extintor', 'extinguidor', 'incendio', 'fuego'], img: IMG.extintor },
  { kw: ['triángulo', 'triangulo', 'señalización de emergencia', 'baliza'], img: IMG.trianguloEmergencia },
  { kw: ['herido', 'víctima', 'lesionado', 'inconsciente', 'conmoción', 'shock', 'desmayo'], img: IMG.primerosAuxilios },
  { kw: ['posición lateral', 'posición de seguridad', 'posición de recuperación'], img: IMG.primerosAuxilios },
  { kw: ['botiquín', 'kit de emergencia', 'kit de primeros auxilios'], img: IMG.primerosAuxilios },
  { kw: ['heimlich', 'atraganta', 'atragantamiento', 'asfixia', 'obstrucción de vía aérea'], img: IMG.heimlich },
  { kw: ['dea', 'desfibrilador', 'desfibrilación'], img: IMG.desfibrilador },
  { kw: ['lesión de columna', 'columna vertebral', 'lesión cervical', 'lesión espinal'], img: IMG.primerosAuxilios },
  { kw: ['dificultad para respirar', 'respirar', 'respiración'], img: IMG.primerosAuxilios },
  { kw: ['infarto', 'paro', 'cardíaco'], img: IMG.desfibrilador },
  { kw: ['parto', 'parto de emergencia'], img: IMG.primerosAuxilios },
  { kw: ['consciente', 'está consciente', 'verificar conciencia'], img: IMG.primerosAuxilios },
  { kw: ['traumatismo', 'craneoencefálico', 'trauma craneal'], img: IMG.primerosAuxilios },
  { kw: ['golpe de calor', 'insolación'], img: IMG.primerosAuxilios },
  { kw: ['hipotermia', 'congelamiento'], img: IMG.primerosAuxilios },
  { kw: ['epiléptica', 'epilepsia', 'convulsiones', 'convulsión'], img: IMG.primerosAuxilios },
  { kw: ['anafilaxia', 'alérgica', 'alergia'], img: IMG.primerosAuxilios },
  { kw: ['ahogamiento', 'ahogado'], img: IMG.primerosAuxilios },
  { kw: ['electrocución', 'eléctrica', 'descarga'], img: IMG.primerosAuxilios },
  { kw: ['mordedura', 'serpiente', 'picadura'], img: IMG.primerosAuxilios },
  { kw: ['vendaje', 'venda', 'vendaje triangular', 'vendaje en ocho'], img: IMG.primerosAuxilios },
  { kw: ['camilla', 'improvisar camilla'], img: IMG.primerosAuxilios },
  { kw: ['amputación', 'amputado'], img: IMG.primerosAuxilios },
  { kw: ['cuerpo extraño', 'objeto en el ojo', 'ojo'], img: IMG.primerosAuxilios },
  { kw: ['niño accidentado', 'atender a un niño'], img: IMG.primerosAuxilios },
  { kw: ['no se debe mover', 'no mover', 'mover a un accidentado'], img: IMG.primerosAuxilios },
  { kw: ['objeto clavado', 'clavado en el cuerpo'], img: IMG.primerosAuxilios },
  { kw: ['herida abierta', 'lavar una herida'], img: IMG.primerosAuxilios },
  { kw: ['manta térmica', 'manta de emergencia'], img: IMG.primerosAuxilios },
  { kw: ['contusión'], img: IMG.primerosAuxilios },
  { kw: ['ropa de un accidentado', 'ropa'], img: IMG.primerosAuxilios },
  { kw: ['asma', 'inhalador'], img: IMG.primerosAuxilios },
  { kw: ['cadena de supervivencia'], img: IMG.primerosAuxilios },

  { kw: ['fatiga', 'cansancio', 'somnolencia', 'sueño', 'adormecimiento', 'dormirse', 'microsueño'], img: IMG.fatiga },
  { kw: ['descansar', 'pausa', 'pausas'], img: IMG.fatiga },
  { kw: ['estrés', 'estres'], img: IMG.fatiga },
  { kw: ['distracción', 'distracc', 'distraído'], img: IMG.celular },
  { kw: ['medicamentos', 'medicamento', 'antihistamínicos', 'contraindicados', 'fármacos'], img: IMG.medicamentos },
  { kw: ['brazo fuera', 'ventanilla'], img: IMG.cinturon },
  { kw: ['postura', 'posición correcta', 'ergonomía', 'ergonómic'], img: IMG.posturaConductor },
  { kw: ['visión amplia', 'visión periférica', 'campo visual', 'campo de visión', 'visión estereoscópica', 'visibilidad'], img: IMG.visionConduccion },
  { kw: ['conducción defensiva', 'conducir a la defensiva', 'anticipar', 'anticipación', 'ipde', 'conducción predictiva'], img: IMG.conduccionDefensiva },
  { kw: ['hacerse ver', 'ser visible'], img: IMG.luces },
  { kw: ['comportamiento agresivo', 'agresivo', 'agresividad'], img: IMG.conduccionDefensiva },
  { kw: ['conductores mayores', 'edad avanzada', 'personas mayores'], img: IMG.conduccionDefensiva },
  { kw: ['discapacidad', 'adaptaciones'], img: IMG.conduccionDefensiva },
  { kw: ['error de otro conductor', 'error de otro', 'actitud'], img: IMG.conduccionDefensiva },
  { kw: ['zona más segura', 'posicionar su vehículo'], img: IMG.conduccionDefensiva },
  { kw: ['pelotón', 'conducir en grupo'], img: IMG.distanciaSegura },
  { kw: ['alimentación', 'comer', 'comida'], img: IMG.fatiga },
  { kw: ['riesgo', 'factores de riesgo', 'factores aumentan'], img: IMG.conduccionDefensiva },
  { kw: ['sin visibilidad', 'vapor'], img: IMG.niebla },
  { kw: ['distancia de reacción', 'tiempo de reacción', 'reacción promedio'], img: IMG.distanciaSegura },
  { kw: ['distancia de detención', 'detención total', 'distancia total'], img: IMG.distanciaSegura },
  { kw: ['distancia mínima', 'distancia de seguimiento'], img: IMG.distanciaSegura },
  { kw: ['vado', 'zona inundada', 'inundación'], img: IMG.lluvia },
  { kw: ['objetos sueltos', 'habitáculo', 'objetos en el habitáculo'], img: IMG.cinturon },
  { kw: ['reposacabezas', 'apoyacabezas'], img: IMG.posturaConductor },
  { kw: ['energía cinética', 'peso del vehículo'], img: IMG.velocidadUrbana },
  { kw: ['seguridad activa', 'seguridad pasiva', 'zonas de deformación', 'deformación programada'], img: IMG.airbag },
  { kw: ['adelanta peligrosamente', 'adelantamiento peligroso'], img: IMG.adelantamiento },
  { kw: ['zona residencial', 'residencial'], img: IMG.velocidadUrbana },
  { kw: ['abrir la puerta', 'bajarse del vehículo', 'puerta del vehículo'], img: IMG.estacionamiento },
  { kw: ['cerca del vehículo de adelante', 'muy cerca'], img: IMG.distanciaSegura },
  { kw: ['usuario vulnerable', 'vulnerable de la vía'], img: IMG.crucePeatonal },
  { kw: ['efectos emocionales', 'ira', 'tristeza', 'euforia', 'emociones'], img: IMG.conduccionDefensiva },
  { kw: ['errática', 'forma errática', 'conducción errática'], img: IMG.conduccionDefensiva },
  { kw: ['comunicar con otros conductores', 'comunicar', 'comunicación'], img: IMG.cambioCarril },
  { kw: ['mirada lejana', 'técnica de la mirada'], img: IMG.visionConduccion },
  { kw: ['negarse', 'alcohotest'], img: IMG.alcohol },

  { kw: ['contaminación', 'emisiones', 'gases', 'monóxido', 'co2', 'escape', 'tubo de escape', 'polución', 'óxidos de nitrógeno', 'nox'], img: IMG.medioAmbiente },
  { kw: ['catalizador', 'catalítico', 'convertidor catalítico'], img: IMG.medioAmbiente },
  { kw: ['reciclaje', 'reciclar', 'desechos', 'residuos', 'vida útil'], img: IMG.medioAmbiente },
  { kw: ['medio ambiente', 'ambiental', 'ecológico', 'eco-conducción', 'ahorro de combustible', 'eficiencia energética', 'eco-driving', 'eco-eficiente', 'huella de carbono'], img: IMG.medioAmbiente },
  { kw: ['ruido', 'contaminación acústica', 'sonora', 'bocina', 'claxon'], img: IMG.medioAmbiente },
  { kw: ['sello verde', 'restricción vehicular', 'normas de emisión', 'euro'], img: IMG.medioAmbiente },
  { kw: ['vehículo eléctrico', 'vehículos eléctricos', 'autonomía', 'carga eléctric', 'enchufable', 'plug-in'], img: IMG.vehiculoElectrico },
  { kw: ['híbrido', 'hibrido', 'vehículo híbrido', 'vehículos híbridos'], img: IMG.vehiculoElectrico },
  { kw: ['etiquetado energético', 'impuesto verde', 'baja emisión', 'zbe', 'incentivos'], img: IMG.medioAmbiente },
  { kw: ['transporte', 'pasajero-kilómetro', 'modos de transporte'], img: IMG.medioAmbiente },

  { kw: ['señal reglamentaria', 'reglamentarias', 'forma circular', 'fondo blanco', 'borde rojo'], img: IMG.senalesTipos },
  { kw: ['señal preventiva', 'preventivas', 'forma de diamante', 'fondo amarillo', 'romboidales'], img: IMG.senalesPreventivas },
  { kw: ['señal informativa', 'informativas', 'fondo azul', 'rectángulo'], img: IMG.senalesTipos },
  { kw: ['señalización', 'señales de tránsito', 'tipos de señales', 'señalética'], img: IMG.senalesTipos },
  { kw: ['velocidad'], img: IMG.velocidadUrbana },
  { kw: ['número en blanco', 'número blanco'], img: IMG.senalesTipos },
  { kw: ['tachada', 'tachado'], img: IMG.noEstacionar },
  { kw: ['cebra', 'tipo cebra'], img: IMG.crucePeatonal },

  { kw: ['minibús', 'minibus', 'viaje de pie', 'servicio de transporte de pasajeros'], img: IMG.bus },
  { kw: ['jornada de servicio', 'iniciar cada jornada'], img: IMG.mantenimiento },
  { kw: ['pasajero se siente mal', 'pasajero enfermo'], img: IMG.primerosAuxilios },
  { kw: ['puertas del minibús', 'puertas no cierran'], img: IMG.bus },
  { kw: ['falla mecánica grave', 'falla mecánica'], img: IMG.trianguloEmergencia },
  { kw: ['técnica de observación'], img: IMG.visionConduccion },
  { kw: ['descanse adecuadamente', 'descansar antes de conducir'], img: IMG.fatiga },
  { kw: ['samu', 'número de emergencia'], img: IMG.primerosAuxilios },

  { kw: ['restricción horaria', 'camiones en zonas urbanas'], img: IMG.licencia },
  { kw: ['tanque parcialmente lleno', 'tanque parcialmente'], img: IMG.autopista },
  { kw: ['peso por eje', 'peso máximo por eje'], img: IMG.autopista },
  { kw: ['fines de semana largos', 'feriados'], img: IMG.licencia },
  { kw: ['carta de porte'], img: IMG.licencia },

  { kw: ['maquinaria pesada', 'maquinaria automotriz', 'operador de maquinaria'], img: IMG.zonaObras },
  { kw: ['tendidos eléctricos', 'cables eléctricos aéreos'], img: IMG.zonaObras },
  { kw: ['orugas', 'sistema de orugas'], img: IMG.zonaObras },
  { kw: ['sistema hidráulico', 'hidráulico'], img: IMG.motor },
  { kw: ['protección personal', 'elementos de protección'], img: IMG.cinturon },
  { kw: ['subir o bajar', 'en movimiento'], img: IMG.zonaObras },
  { kw: ['estabilizadores', 'gatos hidráulicos', 'grúa móvil'], img: IMG.zonaObras },
  { kw: ['terreno blando', 'lodoso', 'atrapada'], img: IMG.zonaObras },
  { kw: ['rops', 'estructura rops'], img: IMG.zonaObras },
  { kw: ['cruzar un puente'], img: IMG.autopista },
  { kw: ['redes de servicios subterráneos', 'servicios subterráneos'], img: IMG.zonaObras },
  { kw: ['seguro adicional', 'seguro para la operación'], img: IMG.licencia },
  { kw: ['objetos que caen', 'fops', 'protege al operador'], img: IMG.zonaObras },

  { kw: ['animal de tiro', 'tracción animal', 'vehículo de tracción animal'], img: IMG.curva },
  { kw: ['herraduras', 'herradura'], img: IMG.mantenimiento },
  { kw: ['se niega a avanzar', 'animal se niega'], img: IMG.curva },
  { kw: ['dar agua al animal', 'bienestar animal'], img: IMG.medioAmbiente },
];

const CATEGORY_DEFAULTS: Record<string, ImageSourcePropType> = {
  'Señalización': IMG.senalesTipos,
  'Señales Reglamentarias': IMG.senalPare,
  'Señales Preventivas': IMG.senalesPreventivas,
  'Señales Informativas': IMG.senalesTipos,
  'Ley de Tránsito': IMG.licencia,
  'Conducción Segura': IMG.cinturon,
  'Conducción Defensiva': IMG.conduccionDefensiva,
  'Mecánica Básica': IMG.motor,
  'Medio Ambiente': IMG.medioAmbiente,
  'Primeros Auxilios': IMG.primerosAuxilios,
};

export function getQuestionImage(question: { pregunta: string; categoria: string; id: number }): QuestionVisual {
  const text = question.pregunta.toLowerCase();

  for (const { kw, img } of KEYWORD_IMAGES) {
    for (const k of kw) {
      if (text.includes(k.toLowerCase())) {
        return { type: 'image', source: img };
      }
    }
  }

  const fallback = CATEGORY_DEFAULTS[question.categoria];
  return { type: 'image', source: fallback || IMG.senalesTipos };
}
